* This file was automatically generated by Zimpl
* param Q2 := 1;
* do print file2;
* param nC := read file1 as "1n" use 1;
* param nI := read file1 as "2n" use 1;
* param m  := read file1 as "3n" use 1;
* param nT := read file1 as "4n" use 1;
* param nP := read file2 as "1n" use 1;
* set C := { 1 .. nC };
* set I := { 1 .. nI };
* set T0 := { 0 .. nT };
* set T := { 1 .. nT };
* set P := { 1 .. nP };
* param inveCost[I] := read file1 as "<1n> 2n" skip 1 use nI;
* param backCost[I] := read file1 as "<1n> 2n" skip nI+1 use nI;
* param demand[C*I*T] := read file1 as "<1n,2n,3n> 4n" skip 2*nI+1;
* param q[P*I] := read file2 as "<1n,2n> 3n" skip 1;
* param D[<c,i> in C*I] := ceil( sum <t> in T : demand[c,i,t]/Q2 );
* set Pc[<c> in C] := inter <i> in { <i> in I with ( sum <t> in T : demand[c,i,t] ) > 0 } : { <p> in P with q[p,i] > 0 };
* param M[<c,p> in C*P] := max <i> in I with q[p,i] > 0: ceil( sum <t> in T : demand[c,i,t]/Q2/q[p,i] );
* var r[C*I*T0] >= 0;
* var s[C*I*T0] >= 0;
* var x[C*I*T] integer >= 0;
* var y[C*P*T] integer >= 0;
* var z[P] binary;
* minimize cost: sum <i> in I: ( sum <t> in T: (sum <c> in C : (inveCost[i] * s[c,i,t]  + backCost[i] * r[c,i,t]) ));
* subto select:       sum <p> in P: z[p] <= m;
* subto balance:    forall <c,i,t> in C*I*T with t>=1 do       s[c,i,t-1] - r[c,i,t-1] + Q1*Q2*x[c,i,t] + Q2 * (sum <p> in Pc[c
* ]: q[p,i] * y[c,p,t]) == demand[c,i,t] + s[c,i,t] - r[c,i,t];
* subto valid:    forall <c,i> in C*I do       sum <t> in T: ( min(Q1, D[c,i]) * x[c,i,t] + sum <p> in Pc[c]: ( min(q[p,i], D[c
* ,i] ) * y[c,p,t]) ) >= D[c,i];
* subto BigM:    forall <c,p,t> in C*P*T with t>=1 do       y[c,p,t] <= M[c,p] * z[p];
* subto init1:    forall <c,i> in C*I do       s[c,i,0] == 0;
* subto init2:    forall <c,i> in C*I do       r[c,i,0] == 0;
* subto init3:    forall <c,i> in C*I do       r[c,i,nT] == 0;
NAME          mpdp.zpl
ROWS
 N  OBJECTIV          
 L  select_1          
 E  balanc@1          
 E  balanc@2          
 E  balanc@3          
 E  balanc@4          
 E  balanc@5          
 E  balanc@6          
 E  balanc@7          
 E  balanc@8          
 E  balanc@9          
 E  balanc@a          
 E  balanc@b          
 E  balanc@c          
 E  balanc@d          
 E  balanc@e          
 E  balanc@f          
 E  balan@10          
 E  balan@11          
 E  balan@12          
 E  balan@13          
 E  balan@14          
 E  balan@15          
 E  balan@16          
 E  balan@17          
 E  balan@18          
 E  balan@19          
 E  balan@1a          
 E  balan@1b          
 E  balan@1c          
 E  balan@1d          
 E  balan@1e          
 E  balan@1f          
 E  balan@20          
 E  balan@21          
 E  balan@22          
 E  balan@23          
 E  balan@24          
 E  balan@25          
 E  balan@26          
 E  balan@27          
 E  balan@28          
 G  valid_1           
 G  valid_2           
 G  valid_3           
 G  valid_4           
 G  valid_5           
 G  valid_6           
 L  BigM_1            
 L  BigM_2            
 L  BigM_3            
 L  BigM_4            
 L  BigM_5            
 L  BigM_6            
 L  BigM_7            
 L  BigM_8            
 L  BigM_9            
 L  BigM_10           
 L  BigM_11           
 L  BigM_12           
 L  BigM_13           
 L  BigM_14           
 L  BigM_15           
 L  BigM_16           
 L  BigM_17           
 L  BigM_18           
 L  BigM_19           
 L  BigM_20           
 L  BigM_21           
 L  BigM_22           
 L  BigM_23           
 L  BigM_24           
 L  BigM_25           
 L  BigM_26           
 L  BigM_27           
 L  BigM_28           
 L  BigM_29           
 L  BigM_30           
 L  BigM_31           
 L  BigM_32           
 L  BigM_33           
 L  BigM_34           
 L  BigM_35           
 L  BigM_36           
 L  BigM_37           
 L  BigM_38           
 L  BigM_39           
 L  BigM_40           
 L  BigM_41           
 L  BigM_42           
 L  BigM_43           
 L  BigM_44           
 L  BigM_45           
 L  BigM_46           
 L  BigM_47           
 L  BigM_48           
 L  BigM_49           
 L  BigM_50           
 L  BigM_51           
 L  BigM_52           
 L  BigM_53           
 L  BigM_54           
 L  BigM_55           
 L  BigM_56           
 L  BigM_57           
 L  BigM_58           
 L  BigM_59           
 L  BigM_60           
 L  BigM_61           
 L  BigM_62           
 L  BigM_63           
 L  BigM_64           
 L  BigM_65           
 L  BigM_66           
 L  BigM_67           
 L  BigM_68           
 L  BigM_69           
 L  BigM_70           
 L  BigM_71           
 L  BigM_72           
 L  BigM_73           
 L  BigM_74           
 L  BigM_75           
 L  BigM_76           
 L  BigM_77           
 L  BigM_78           
 L  BigM_79           
 L  BigM_80           
 L  BigM_81           
 L  BigM_82           
 L  BigM_83           
 L  BigM_84           
 L  BigM_85           
 L  BigM_86           
 L  BigM_87           
 L  BigM_88           
 L  BigM_89           
 L  BigM_90           
 L  BigM_91           
 L  BigM_92           
 L  BigM_93           
 L  BigM_94           
 L  BigM_95           
 L  BigM_96           
 L  BigM_97           
 L  BigM_98           
 L  BigM_99           
 L  BigM_100          
 E  init1_1           
 E  init1_2           
 E  init1_3           
 E  init1_4           
 E  init1_5           
 E  init1_6           
 E  init1_7           
 E  init1_8           
 E  init2_1           
 E  init2_2           
 E  init2_3           
 E  init2_4           
 E  init2_5           
 E  init2_6           
 E  init2_7           
 E  init2_8           
 E  init3_1           
 E  init3_2           
 E  init3_3           
 E  init3_4           
 E  init3_5           
 E  init3_6           
 E  init3_7           
 E  init3_8           
COLUMNS
    MARK0000  'MARKER'                 'INTORG'
    x#1#1#1   valid_1             72
    x#1#1#1   balanc@1            72
    x#1#1#2   valid_1             72
    x#1#1#2   balanc@2            72
    x#1#1#3   valid_1             72
    x#1#1#3   balanc@3            72
    x#1#1#4   valid_1             72
    x#1#1#4   balanc@4            72
    x#1#1#5   valid_1             72
    x#1#1#5   balanc@5            72
    x#1#2#1   balanc@6            72
    x#1#2#2   balanc@7            72
    x#1#2#3   balanc@8            72
    x#1#2#4   balanc@9            72
    x#1#2#5   balanc@a            72
    x#2#1#1   valid_2             72
    x#2#1#1   balanc@b            72
    x#2#1#2   valid_2             72
    x#2#1#2   balanc@c            72
    x#2#1#3   valid_2             72
    x#2#1#3   balanc@d            72
    x#2#1#4   valid_2             72
    x#2#1#4   balanc@e            72
    x#2#1#5   valid_2             72
    x#2#1#5   balanc@f            72
    x#2#2#1   valid_3             72
    x#2#2#1   balan@10            72
    x#2#2#2   valid_3             72
    x#2#2#2   balan@11            72
    x#2#2#3   valid_3             72
    x#2#2#3   balan@12            72
    x#2#2#4   valid_3             72
    x#2#2#4   balan@13            72
    x#2#2#5   valid_3             72
    x#2#2#5   balan@14            72
    x#3#1#1   valid_4             72
    x#3#1#1   balan@15            72
    x#3#1#2   valid_4             72
    x#3#1#2   balan@16            72
    x#3#1#3   valid_4             72
    x#3#1#3   balan@17            72
    x#3#1#4   valid_4             72
    x#3#1#4   balan@18            72
    x#3#1#5   valid_4             72
    x#3#1#5   balan@19            72
    x#3#2#1   valid_5             72
    x#3#2#1   balan@1a            72
    x#3#2#2   valid_5             72
    x#3#2#2   balan@1b            72
    x#3#2#3   valid_5             72
    x#3#2#3   balan@1c            72
    x#3#2#4   valid_5             72
    x#3#2#4   balan@1d            72
    x#3#2#5   valid_5             72
    x#3#2#5   balan@1e            72
    x#4#1#1   balan@1f            72
    x#4#1#2   balan@20            72
    x#4#1#3   balan@21            72
    x#4#1#4   balan@22            72
    x#4#1#5   balan@23            72
    x#4#2#1   valid_6             72
    x#4#2#1   balan@24            72
    x#4#2#2   valid_6             72
    x#4#2#2   balan@25            72
    x#4#2#3   valid_6             72
    x#4#2#3   balan@26            72
    x#4#2#4   valid_6             72
    x#4#2#4   balan@27            72
    x#4#2#5   valid_6             72
    x#4#2#5   balan@28            72
    y#1#1#1   BigM_1               1
    y#1#1#1   valid_1             35
    y#1#1#1   balanc@6            37
    y#1#1#1   balanc@1            35
    y#1#1#2   BigM_2               1
    y#1#1#2   valid_1             35
    y#1#1#2   balanc@7            37
    y#1#1#2   balanc@2            35
    y#1#1#3   BigM_3               1
    y#1#1#3   valid_1             35
    y#1#1#3   balanc@8            37
    y#1#1#3   balanc@3            35
    y#1#1#4   BigM_4               1
    y#1#1#4   valid_1             35
    y#1#1#4   balanc@9            37
    y#1#1#4   balanc@4            35
    y#1#1#5   BigM_5               1
    y#1#1#5   valid_1             35
    y#1#1#5   balanc@a            37
    y#1#1#5   balanc@5            35
    y#1#2#1   BigM_6               1
    y#1#2#1   valid_1             49
    y#1#2#1   balanc@6            23
    y#1#2#1   balanc@1            49
    y#1#2#2   BigM_7               1
    y#1#2#2   valid_1             49
    y#1#2#2   balanc@7            23
    y#1#2#2   balanc@2            49
    y#1#2#3   BigM_8               1
    y#1#2#3   valid_1             49
    y#1#2#3   balanc@8            23
    y#1#2#3   balanc@3            49
    y#1#2#4   BigM_9               1
    y#1#2#4   valid_1             49
    y#1#2#4   balanc@9            23
    y#1#2#4   balanc@4            49
    y#1#2#5   BigM_10              1
    y#1#2#5   valid_1             49
    y#1#2#5   balanc@a            23
    y#1#2#5   balanc@5            49
    y#1#3#1   BigM_11              1
    y#1#3#1   valid_1             41
    y#1#3#1   balanc@6            31
    y#1#3#1   balanc@1            41
    y#1#3#2   BigM_12              1
    y#1#3#2   valid_1             41
    y#1#3#2   balanc@7            31
    y#1#3#2   balanc@2            41
    y#1#3#3   BigM_13              1
    y#1#3#3   valid_1             41
    y#1#3#3   balanc@8            31
    y#1#3#3   balanc@3            41
    y#1#3#4   BigM_14              1
    y#1#3#4   valid_1             41
    y#1#3#4   balanc@9            31
    y#1#3#4   balanc@4            41
    y#1#3#5   BigM_15              1
    y#1#3#5   valid_1             41
    y#1#3#5   balanc@a            31
    y#1#3#5   balanc@5            41
    y#1#4#1   BigM_16              1
    y#1#4#1   valid_1             12
    y#1#4#1   balanc@6            60
    y#1#4#1   balanc@1            12
    y#1#4#2   BigM_17              1
    y#1#4#2   valid_1             12
    y#1#4#2   balanc@7            60
    y#1#4#2   balanc@2            12
    y#1#4#3   BigM_18              1
    y#1#4#3   valid_1             12
    y#1#4#3   balanc@8            60
    y#1#4#3   balanc@3            12
    y#1#4#4   BigM_19              1
    y#1#4#4   valid_1             12
    y#1#4#4   balanc@9            60
    y#1#4#4   balanc@4            12
    y#1#4#5   BigM_20              1
    y#1#4#5   valid_1             12
    y#1#4#5   balanc@a            60
    y#1#4#5   balanc@5            12
    y#1#5#1   BigM_21              1
    y#1#5#1   valid_1             24
    y#1#5#1   balanc@6            48
    y#1#5#1   balanc@1            24
    y#1#5#2   BigM_22              1
    y#1#5#2   valid_1             24
    y#1#5#2   balanc@7            48
    y#1#5#2   balanc@2            24
    y#1#5#3   BigM_23              1
    y#1#5#3   valid_1             24
    y#1#5#3   balanc@8            48
    y#1#5#3   balanc@3            24
    y#1#5#4   BigM_24              1
    y#1#5#4   valid_1             24
    y#1#5#4   balanc@9            48
    y#1#5#4   balanc@4            24
    y#1#5#5   BigM_25              1
    y#1#5#5   valid_1             24
    y#1#5#5   balanc@a            48
    y#1#5#5   balanc@5            24
    y#2#1#1   BigM_26              1
    y#2#1#1   valid_3             37
    y#2#1#1   valid_2             35
    y#2#1#1   balan@10            37
    y#2#1#1   balanc@b            35
    y#2#1#2   BigM_27              1
    y#2#1#2   valid_3             37
    y#2#1#2   valid_2             35
    y#2#1#2   balan@11            37
    y#2#1#2   balanc@c            35
    y#2#1#3   BigM_28              1
    y#2#1#3   valid_3             37
    y#2#1#3   valid_2             35
    y#2#1#3   balan@12            37
    y#2#1#3   balanc@d            35
    y#2#1#4   BigM_29              1
    y#2#1#4   valid_3             37
    y#2#1#4   valid_2             35
    y#2#1#4   balan@13            37
    y#2#1#4   balanc@e            35
    y#2#1#5   BigM_30              1
    y#2#1#5   valid_3             37
    y#2#1#5   valid_2             35
    y#2#1#5   balan@14            37
    y#2#1#5   balanc@f            35
    y#2#2#1   BigM_31              1
    y#2#2#1   valid_3             23
    y#2#2#1   valid_2             49
    y#2#2#1   balan@10            23
    y#2#2#1   balanc@b            49
    y#2#2#2   BigM_32              1
    y#2#2#2   valid_3             23
    y#2#2#2   valid_2             49
    y#2#2#2   balan@11            23
    y#2#2#2   balanc@c            49
    y#2#2#3   BigM_33              1
    y#2#2#3   valid_3             23
    y#2#2#3   valid_2             49
    y#2#2#3   balan@12            23
    y#2#2#3   balanc@d            49
    y#2#2#4   BigM_34              1
    y#2#2#4   valid_3             23
    y#2#2#4   valid_2             49
    y#2#2#4   balan@13            23
    y#2#2#4   balanc@e            49
    y#2#2#5   BigM_35              1
    y#2#2#5   valid_3             23
    y#2#2#5   valid_2             49
    y#2#2#5   balan@14            23
    y#2#2#5   balanc@f            49
    y#2#3#1   BigM_36              1
    y#2#3#1   valid_3             31
    y#2#3#1   valid_2             41
    y#2#3#1   balan@10            31
    y#2#3#1   balanc@b            41
    y#2#3#2   BigM_37              1
    y#2#3#2   valid_3             31
    y#2#3#2   valid_2             41
    y#2#3#2   balan@11            31
    y#2#3#2   balanc@c            41
    y#2#3#3   BigM_38              1
    y#2#3#3   valid_3             31
    y#2#3#3   valid_2             41
    y#2#3#3   balan@12            31
    y#2#3#3   balanc@d            41
    y#2#3#4   BigM_39              1
    y#2#3#4   valid_3             31
    y#2#3#4   valid_2             41
    y#2#3#4   balan@13            31
    y#2#3#4   balanc@e            41
    y#2#3#5   BigM_40              1
    y#2#3#5   valid_3             31
    y#2#3#5   valid_2             41
    y#2#3#5   balan@14            31
    y#2#3#5   balanc@f            41
    y#2#4#1   BigM_41              1
    y#2#4#1   valid_3             60
    y#2#4#1   valid_2             12
    y#2#4#1   balan@10            60
    y#2#4#1   balanc@b            12
    y#2#4#2   BigM_42              1
    y#2#4#2   valid_3             60
    y#2#4#2   valid_2             12
    y#2#4#2   balan@11            60
    y#2#4#2   balanc@c            12
    y#2#4#3   BigM_43              1
    y#2#4#3   valid_3             60
    y#2#4#3   valid_2             12
    y#2#4#3   balan@12            60
    y#2#4#3   balanc@d            12
    y#2#4#4   BigM_44              1
    y#2#4#4   valid_3             60
    y#2#4#4   valid_2             12
    y#2#4#4   balan@13            60
    y#2#4#4   balanc@e            12
    y#2#4#5   BigM_45              1
    y#2#4#5   valid_3             60
    y#2#4#5   valid_2             12
    y#2#4#5   balan@14            60
    y#2#4#5   balanc@f            12
    y#2#5#1   BigM_46              1
    y#2#5#1   valid_3             48
    y#2#5#1   valid_2             24
    y#2#5#1   balan@10            48
    y#2#5#1   balanc@b            24
    y#2#5#2   BigM_47              1
    y#2#5#2   valid_3             48
    y#2#5#2   valid_2             24
    y#2#5#2   balan@11            48
    y#2#5#2   balanc@c            24
    y#2#5#3   BigM_48              1
    y#2#5#3   valid_3             48
    y#2#5#3   valid_2             24
    y#2#5#3   balan@12            48
    y#2#5#3   balanc@d            24
    y#2#5#4   BigM_49              1
    y#2#5#4   valid_3             48
    y#2#5#4   valid_2             24
    y#2#5#4   balan@13            48
    y#2#5#4   balanc@e            24
    y#2#5#5   BigM_50              1
    y#2#5#5   valid_3             48
    y#2#5#5   valid_2             24
    y#2#5#5   balan@14            48
    y#2#5#5   balanc@f            24
    y#3#1#1   BigM_51              1
    y#3#1#1   valid_5             37
    y#3#1#1   valid_4             35
    y#3#1#1   balan@1a            37
    y#3#1#1   balan@15            35
    y#3#1#2   BigM_52              1
    y#3#1#2   valid_5             37
    y#3#1#2   valid_4             35
    y#3#1#2   balan@1b            37
    y#3#1#2   balan@16            35
    y#3#1#3   BigM_53              1
    y#3#1#3   valid_5             37
    y#3#1#3   valid_4             35
    y#3#1#3   balan@1c            37
    y#3#1#3   balan@17            35
    y#3#1#4   BigM_54              1
    y#3#1#4   valid_5             37
    y#3#1#4   valid_4             35
    y#3#1#4   balan@1d            37
    y#3#1#4   balan@18            35
    y#3#1#5   BigM_55              1
    y#3#1#5   valid_5             37
    y#3#1#5   valid_4             35
    y#3#1#5   balan@1e            37
    y#3#1#5   balan@19            35
    y#3#2#1   BigM_56              1
    y#3#2#1   valid_5             23
    y#3#2#1   valid_4             49
    y#3#2#1   balan@1a            23
    y#3#2#1   balan@15            49
    y#3#2#2   BigM_57              1
    y#3#2#2   valid_5             23
    y#3#2#2   valid_4             49
    y#3#2#2   balan@1b            23
    y#3#2#2   balan@16            49
    y#3#2#3   BigM_58              1
    y#3#2#3   valid_5             23
    y#3#2#3   valid_4             49
    y#3#2#3   balan@1c            23
    y#3#2#3   balan@17            49
    y#3#2#4   BigM_59              1
    y#3#2#4   valid_5             23
    y#3#2#4   valid_4             49
    y#3#2#4   balan@1d            23
    y#3#2#4   balan@18            49
    y#3#2#5   BigM_60              1
    y#3#2#5   valid_5             23
    y#3#2#5   valid_4             49
    y#3#2#5   balan@1e            23
    y#3#2#5   balan@19            49
    y#3#3#1   BigM_61              1
    y#3#3#1   valid_5             31
    y#3#3#1   valid_4             41
    y#3#3#1   balan@1a            31
    y#3#3#1   balan@15            41
    y#3#3#2   BigM_62              1
    y#3#3#2   valid_5             31
    y#3#3#2   valid_4             41
    y#3#3#2   balan@1b            31
    y#3#3#2   balan@16            41
    y#3#3#3   BigM_63              1
    y#3#3#3   valid_5             31
    y#3#3#3   valid_4             41
    y#3#3#3   balan@1c            31
    y#3#3#3   balan@17            41
    y#3#3#4   BigM_64              1
    y#3#3#4   valid_5             31
    y#3#3#4   valid_4             41
    y#3#3#4   balan@1d            31
    y#3#3#4   balan@18            41
    y#3#3#5   BigM_65              1
    y#3#3#5   valid_5             31
    y#3#3#5   valid_4             41
    y#3#3#5   balan@1e            31
    y#3#3#5   balan@19            41
    y#3#4#1   BigM_66              1
    y#3#4#1   valid_5             60
    y#3#4#1   valid_4             12
    y#3#4#1   balan@1a            60
    y#3#4#1   balan@15            12
    y#3#4#2   BigM_67              1
    y#3#4#2   valid_5             60
    y#3#4#2   valid_4             12
    y#3#4#2   balan@1b            60
    y#3#4#2   balan@16            12
    y#3#4#3   BigM_68              1
    y#3#4#3   valid_5             60
    y#3#4#3   valid_4             12
    y#3#4#3   balan@1c            60
    y#3#4#3   balan@17            12
    y#3#4#4   BigM_69              1
    y#3#4#4   valid_5             60
    y#3#4#4   valid_4             12
    y#3#4#4   balan@1d            60
    y#3#4#4   balan@18            12
    y#3#4#5   BigM_70              1
    y#3#4#5   valid_5             60
    y#3#4#5   valid_4             12
    y#3#4#5   balan@1e            60
    y#3#4#5   balan@19            12
    y#3#5#1   BigM_71              1
    y#3#5#1   valid_5             48
    y#3#5#1   valid_4             24
    y#3#5#1   balan@1a            48
    y#3#5#1   balan@15            24
    y#3#5#2   BigM_72              1
    y#3#5#2   valid_5             48
    y#3#5#2   valid_4             24
    y#3#5#2   balan@1b            48
    y#3#5#2   balan@16            24
    y#3#5#3   BigM_73              1
    y#3#5#3   valid_5             48
    y#3#5#3   valid_4             24
    y#3#5#3   balan@1c            48
    y#3#5#3   balan@17            24
    y#3#5#4   BigM_74              1
    y#3#5#4   valid_5             48
    y#3#5#4   valid_4             24
    y#3#5#4   balan@1d            48
    y#3#5#4   balan@18            24
    y#3#5#5   BigM_75              1
    y#3#5#5   valid_5             48
    y#3#5#5   valid_4             24
    y#3#5#5   balan@1e            48
    y#3#5#5   balan@19            24
    y#4#1#1   BigM_76              1
    y#4#1#1   valid_6             37
    y#4#1#1   balan@24            37
    y#4#1#1   balan@1f            35
    y#4#1#2   BigM_77              1
    y#4#1#2   valid_6             37
    y#4#1#2   balan@25            37
    y#4#1#2   balan@20            35
    y#4#1#3   BigM_78              1
    y#4#1#3   valid_6             37
    y#4#1#3   balan@26            37
    y#4#1#3   balan@21            35
    y#4#1#4   BigM_79              1
    y#4#1#4   valid_6             37
    y#4#1#4   balan@27            37
    y#4#1#4   balan@22            35
    y#4#1#5   BigM_80              1
    y#4#1#5   valid_6             37
    y#4#1#5   balan@28            37
    y#4#1#5   balan@23            35
    y#4#2#1   BigM_81              1
    y#4#2#1   valid_6             23
    y#4#2#1   balan@24            23
    y#4#2#1   balan@1f            49
    y#4#2#2   BigM_82              1
    y#4#2#2   valid_6             23
    y#4#2#2   balan@25            23
    y#4#2#2   balan@20            49
    y#4#2#3   BigM_83              1
    y#4#2#3   valid_6             23
    y#4#2#3   balan@26            23
    y#4#2#3   balan@21            49
    y#4#2#4   BigM_84              1
    y#4#2#4   valid_6             23
    y#4#2#4   balan@27            23
    y#4#2#4   balan@22            49
    y#4#2#5   BigM_85              1
    y#4#2#5   valid_6             23
    y#4#2#5   balan@28            23
    y#4#2#5   balan@23            49
    y#4#3#1   BigM_86              1
    y#4#3#1   valid_6             31
    y#4#3#1   balan@24            31
    y#4#3#1   balan@1f            41
    y#4#3#2   BigM_87              1
    y#4#3#2   valid_6             31
    y#4#3#2   balan@25            31
    y#4#3#2   balan@20            41
    y#4#3#3   BigM_88              1
    y#4#3#3   valid_6             31
    y#4#3#3   balan@26            31
    y#4#3#3   balan@21            41
    y#4#3#4   BigM_89              1
    y#4#3#4   valid_6             31
    y#4#3#4   balan@27            31
    y#4#3#4   balan@22            41
    y#4#3#5   BigM_90              1
    y#4#3#5   valid_6             31
    y#4#3#5   balan@28            31
    y#4#3#5   balan@23            41
    y#4#4#1   BigM_91              1
    y#4#4#1   valid_6             60
    y#4#4#1   balan@24            60
    y#4#4#1   balan@1f            12
    y#4#4#2   BigM_92              1
    y#4#4#2   valid_6             60
    y#4#4#2   balan@25            60
    y#4#4#2   balan@20            12
    y#4#4#3   BigM_93              1
    y#4#4#3   valid_6             60
    y#4#4#3   balan@26            60
    y#4#4#3   balan@21            12
    y#4#4#4   BigM_94              1
    y#4#4#4   valid_6             60
    y#4#4#4   balan@27            60
    y#4#4#4   balan@22            12
    y#4#4#5   BigM_95              1
    y#4#4#5   valid_6             60
    y#4#4#5   balan@28            60
    y#4#4#5   balan@23            12
    y#4#5#1   BigM_96              1
    y#4#5#1   valid_6             48
    y#4#5#1   balan@24            48
    y#4#5#1   balan@1f            24
    y#4#5#2   BigM_97              1
    y#4#5#2   valid_6             48
    y#4#5#2   balan@25            48
    y#4#5#2   balan@20            24
    y#4#5#3   BigM_98              1
    y#4#5#3   valid_6             48
    y#4#5#3   balan@26            48
    y#4#5#3   balan@21            24
    y#4#5#4   BigM_99              1
    y#4#5#4   valid_6             48
    y#4#5#4   balan@27            48
    y#4#5#4   balan@22            24
    y#4#5#5   BigM_100             1
    y#4#5#5   valid_6             48
    y#4#5#5   balan@28            48
    y#4#5#5   balan@23            24
    z#1       BigM_80            -80
    z#1       BigM_79            -80
    z#1       BigM_78            -80
    z#1       BigM_77            -80
    z#1       BigM_76            -80
    z#1       BigM_55            -59
    z#1       BigM_54            -59
    z#1       BigM_53            -59
    z#1       BigM_52            -59
    z#1       BigM_51            -59
    z#1       BigM_30            -72
    z#1       BigM_29            -72
    z#1       BigM_28            -72
    z#1       BigM_27            -72
    z#1       BigM_26            -72
    z#1       BigM_5             -63
    z#1       BigM_4             -63
    z#1       BigM_3             -63
    z#1       BigM_2             -63
    z#1       BigM_1             -63
    z#1       select_1             1
    z#2       BigM_85           -128
    z#2       BigM_84           -128
    z#2       BigM_83           -128
    z#2       BigM_82           -128
    z#2       BigM_81           -128
    z#2       BigM_60            -95
    z#2       BigM_59            -95
    z#2       BigM_58            -95
    z#2       BigM_57            -95
    z#2       BigM_56            -95
    z#2       BigM_35            -81
    z#2       BigM_34            -81
    z#2       BigM_33            -81
    z#2       BigM_32            -81
    z#2       BigM_31            -81
    z#2       BigM_10            -45
    z#2       BigM_9             -45
    z#2       BigM_8             -45
    z#2       BigM_7             -45
    z#2       BigM_6             -45
    z#2       select_1             1
    z#3       BigM_90            -95
    z#3       BigM_89            -95
    z#3       BigM_88            -95
    z#3       BigM_87            -95
    z#3       BigM_86            -95
    z#3       BigM_65            -71
    z#3       BigM_64            -71
    z#3       BigM_63            -71
    z#3       BigM_62            -71
    z#3       BigM_61            -71
    z#3       BigM_40            -62
    z#3       BigM_39            -62
    z#3       BigM_38            -62
    z#3       BigM_37            -62
    z#3       BigM_36            -62
    z#3       BigM_15            -53
    z#3       BigM_14            -53
    z#3       BigM_13            -53
    z#3       BigM_12            -53
    z#3       BigM_11            -53
    z#3       select_1             1
    z#4       BigM_95            -49
    z#4       BigM_94            -49
    z#4       BigM_93            -49
    z#4       BigM_92            -49
    z#4       BigM_91            -49
    z#4       BigM_70           -128
    z#4       BigM_69           -128
    z#4       BigM_68           -128
    z#4       BigM_67           -128
    z#4       BigM_66           -128
    z#4       BigM_45           -209
    z#4       BigM_44           -209
    z#4       BigM_43           -209
    z#4       BigM_42           -209
    z#4       BigM_41           -209
    z#4       BigM_20           -181
    z#4       BigM_19           -181
    z#4       BigM_18           -181
    z#4       BigM_17           -181
    z#4       BigM_16           -181
    z#4       select_1             1
    z#5       BigM_100           -61
    z#5       BigM_99            -61
    z#5       BigM_98            -61
    z#5       BigM_97            -61
    z#5       BigM_96            -61
    z#5       BigM_75            -64
    z#5       BigM_74            -64
    z#5       BigM_73            -64
    z#5       BigM_72            -64
    z#5       BigM_71            -64
    z#5       BigM_50           -105
    z#5       BigM_49           -105
    z#5       BigM_48           -105
    z#5       BigM_47           -105
    z#5       BigM_46           -105
    z#5       BigM_25            -91
    z#5       BigM_24            -91
    z#5       BigM_23            -91
    z#5       BigM_22            -91
    z#5       BigM_21            -91
    z#5       select_1             1
    MARK0001  'MARKER'                 'INTEND'
    r#1#1#0   init2_1              1
    r#1#1#0   balanc@1            -1
    r#1#1#1   OBJECTIV             5
    r#1#1#1   balanc@2            -1
    r#1#1#1   balanc@1             1
    r#1#1#2   OBJECTIV             5
    r#1#1#2   balanc@3            -1
    r#1#1#2   balanc@2             1
    r#1#1#3   OBJECTIV             5
    r#1#1#3   balanc@4            -1
    r#1#1#3   balanc@3             1
    r#1#1#4   OBJECTIV             5
    r#1#1#4   balanc@5            -1
    r#1#1#4   balanc@4             1
    r#1#1#5   OBJECTIV             5
    r#1#1#5   init3_1              1
    r#1#1#5   balanc@5             1
    r#1#2#0   init2_2              1
    r#1#2#0   balanc@6            -1
    r#1#2#1   OBJECTIV           5.5
    r#1#2#1   balanc@7            -1
    r#1#2#1   balanc@6             1
    r#1#2#2   OBJECTIV           5.5
    r#1#2#2   balanc@8            -1
    r#1#2#2   balanc@7             1
    r#1#2#3   OBJECTIV           5.5
    r#1#2#3   balanc@9            -1
    r#1#2#3   balanc@8             1
    r#1#2#4   OBJECTIV           5.5
    r#1#2#4   balanc@a            -1
    r#1#2#4   balanc@9             1
    r#1#2#5   OBJECTIV           5.5
    r#1#2#5   init3_2              1
    r#1#2#5   balanc@a             1
    r#2#1#0   init2_3              1
    r#2#1#0   balanc@b            -1
    r#2#1#1   OBJECTIV             5
    r#2#1#1   balanc@c            -1
    r#2#1#1   balanc@b             1
    r#2#1#2   OBJECTIV             5
    r#2#1#2   balanc@d            -1
    r#2#1#2   balanc@c             1
    r#2#1#3   OBJECTIV             5
    r#2#1#3   balanc@e            -1
    r#2#1#3   balanc@d             1
    r#2#1#4   OBJECTIV             5
    r#2#1#4   balanc@f            -1
    r#2#1#4   balanc@e             1
    r#2#1#5   OBJECTIV             5
    r#2#1#5   init3_3              1
    r#2#1#5   balanc@f             1
    r#2#2#0   init2_4              1
    r#2#2#0   balan@10            -1
    r#2#2#1   OBJECTIV           5.5
    r#2#2#1   balan@11            -1
    r#2#2#1   balan@10             1
    r#2#2#2   OBJECTIV           5.5
    r#2#2#2   balan@12            -1
    r#2#2#2   balan@11             1
    r#2#2#3   OBJECTIV           5.5
    r#2#2#3   balan@13            -1
    r#2#2#3   balan@12             1
    r#2#2#4   OBJECTIV           5.5
    r#2#2#4   balan@14            -1
    r#2#2#4   balan@13             1
    r#2#2#5   OBJECTIV           5.5
    r#2#2#5   init3_4              1
    r#2#2#5   balan@14             1
    r#3#1#0   init2_5              1
    r#3#1#0   balan@15            -1
    r#3#1#1   OBJECTIV             5
    r#3#1#1   balan@16            -1
    r#3#1#1   balan@15             1
    r#3#1#2   OBJECTIV             5
    r#3#1#2   balan@17            -1
    r#3#1#2   balan@16             1
    r#3#1#3   OBJECTIV             5
    r#3#1#3   balan@18            -1
    r#3#1#3   balan@17             1
    r#3#1#4   OBJECTIV             5
    r#3#1#4   balan@19            -1
    r#3#1#4   balan@18             1
    r#3#1#5   OBJECTIV             5
    r#3#1#5   init3_5              1
    r#3#1#5   balan@19             1
    r#3#2#0   init2_6              1
    r#3#2#0   balan@1a            -1
    r#3#2#1   OBJECTIV           5.5
    r#3#2#1   balan@1b            -1
    r#3#2#1   balan@1a             1
    r#3#2#2   OBJECTIV           5.5
    r#3#2#2   balan@1c            -1
    r#3#2#2   balan@1b             1
    r#3#2#3   OBJECTIV           5.5
    r#3#2#3   balan@1d            -1
    r#3#2#3   balan@1c             1
    r#3#2#4   OBJECTIV           5.5
    r#3#2#4   balan@1e            -1
    r#3#2#4   balan@1d             1
    r#3#2#5   OBJECTIV           5.5
    r#3#2#5   init3_6              1
    r#3#2#5   balan@1e             1
    r#4#1#0   init2_7              1
    r#4#1#0   balan@1f            -1
    r#4#1#1   OBJECTIV             5
    r#4#1#1   balan@20            -1
    r#4#1#1   balan@1f             1
    r#4#1#2   OBJECTIV             5
    r#4#1#2   balan@21            -1
    r#4#1#2   balan@20             1
    r#4#1#3   OBJECTIV             5
    r#4#1#3   balan@22            -1
    r#4#1#3   balan@21             1
    r#4#1#4   OBJECTIV             5
    r#4#1#4   balan@23            -1
    r#4#1#4   balan@22             1
    r#4#1#5   OBJECTIV             5
    r#4#1#5   init3_7              1
    r#4#1#5   balan@23             1
    r#4#2#0   init2_8              1
    r#4#2#0   balan@24            -1
    r#4#2#1   OBJECTIV           5.5
    r#4#2#1   balan@25            -1
    r#4#2#1   balan@24             1
    r#4#2#2   OBJECTIV           5.5
    r#4#2#2   balan@26            -1
    r#4#2#2   balan@25             1
    r#4#2#3   OBJECTIV           5.5
    r#4#2#3   balan@27            -1
    r#4#2#3   balan@26             1
    r#4#2#4   OBJECTIV           5.5
    r#4#2#4   balan@28            -1
    r#4#2#4   balan@27             1
    r#4#2#5   OBJECTIV           5.5
    r#4#2#5   init3_8              1
    r#4#2#5   balan@28             1
    s#1#1#0   init1_1              1
    s#1#1#0   balanc@1             1
    s#1#1#1   OBJECTIV             1
    s#1#1#1   balanc@2             1
    s#1#1#1   balanc@1            -1
    s#1#1#2   OBJECTIV             1
    s#1#1#2   balanc@3             1
    s#1#1#2   balanc@2            -1
    s#1#1#3   OBJECTIV             1
    s#1#1#3   balanc@4             1
    s#1#1#3   balanc@3            -1
    s#1#1#4   OBJECTIV             1
    s#1#1#4   balanc@5             1
    s#1#1#4   balanc@4            -1
    s#1#1#5   OBJECTIV             1
    s#1#1#5   balanc@5            -1
    s#1#2#0   init1_2              1
    s#1#2#0   balanc@6             1
    s#1#2#1   OBJECTIV           1.1
    s#1#2#1   balanc@7             1
    s#1#2#1   balanc@6            -1
    s#1#2#2   OBJECTIV           1.1
    s#1#2#2   balanc@8             1
    s#1#2#2   balanc@7            -1
    s#1#2#3   OBJECTIV           1.1
    s#1#2#3   balanc@9             1
    s#1#2#3   balanc@8            -1
    s#1#2#4   OBJECTIV           1.1
    s#1#2#4   balanc@a             1
    s#1#2#4   balanc@9            -1
    s#1#2#5   OBJECTIV           1.1
    s#1#2#5   balanc@a            -1
    s#2#1#0   init1_3              1
    s#2#1#0   balanc@b             1
    s#2#1#1   OBJECTIV             1
    s#2#1#1   balanc@c             1
    s#2#1#1   balanc@b            -1
    s#2#1#2   OBJECTIV             1
    s#2#1#2   balanc@d             1
    s#2#1#2   balanc@c            -1
    s#2#1#3   OBJECTIV             1
    s#2#1#3   balanc@e             1
    s#2#1#3   balanc@d            -1
    s#2#1#4   OBJECTIV             1
    s#2#1#4   balanc@f             1
    s#2#1#4   balanc@e            -1
    s#2#1#5   OBJECTIV             1
    s#2#1#5   balanc@f            -1
    s#2#2#0   init1_4              1
    s#2#2#0   balan@10             1
    s#2#2#1   OBJECTIV           1.1
    s#2#2#1   balan@11             1
    s#2#2#1   balan@10            -1
    s#2#2#2   OBJECTIV           1.1
    s#2#2#2   balan@12             1
    s#2#2#2   balan@11            -1
    s#2#2#3   OBJECTIV           1.1
    s#2#2#3   balan@13             1
    s#2#2#3   balan@12            -1
    s#2#2#4   OBJECTIV           1.1
    s#2#2#4   balan@14             1
    s#2#2#4   balan@13            -1
    s#2#2#5   OBJECTIV           1.1
    s#2#2#5   balan@14            -1
    s#3#1#0   init1_5              1
    s#3#1#0   balan@15             1
    s#3#1#1   OBJECTIV             1
    s#3#1#1   balan@16             1
    s#3#1#1   balan@15            -1
    s#3#1#2   OBJECTIV             1
    s#3#1#2   balan@17             1
    s#3#1#2   balan@16            -1
    s#3#1#3   OBJECTIV             1
    s#3#1#3   balan@18             1
    s#3#1#3   balan@17            -1
    s#3#1#4   OBJECTIV             1
    s#3#1#4   balan@19             1
    s#3#1#4   balan@18            -1
    s#3#1#5   OBJECTIV             1
    s#3#1#5   balan@19            -1
    s#3#2#0   init1_6              1
    s#3#2#0   balan@1a             1
    s#3#2#1   OBJECTIV           1.1
    s#3#2#1   balan@1b             1
    s#3#2#1   balan@1a            -1
    s#3#2#2   OBJECTIV           1.1
    s#3#2#2   balan@1c             1
    s#3#2#2   balan@1b            -1
    s#3#2#3   OBJECTIV           1.1
    s#3#2#3   balan@1d             1
    s#3#2#3   balan@1c            -1
    s#3#2#4   OBJECTIV           1.1
    s#3#2#4   balan@1e             1
    s#3#2#4   balan@1d            -1
    s#3#2#5   OBJECTIV           1.1
    s#3#2#5   balan@1e            -1
    s#4#1#0   init1_7              1
    s#4#1#0   balan@1f             1
    s#4#1#1   OBJECTIV             1
    s#4#1#1   balan@20             1
    s#4#1#1   balan@1f            -1
    s#4#1#2   OBJECTIV             1
    s#4#1#2   balan@21             1
    s#4#1#2   balan@20            -1
    s#4#1#3   OBJECTIV             1
    s#4#1#3   balan@22             1
    s#4#1#3   balan@21            -1
    s#4#1#4   OBJECTIV             1
    s#4#1#4   balan@23             1
    s#4#1#4   balan@22            -1
    s#4#1#5   OBJECTIV             1
    s#4#1#5   balan@23            -1
    s#4#2#0   init1_8              1
    s#4#2#0   balan@24             1
    s#4#2#1   OBJECTIV           1.1
    s#4#2#1   balan@25             1
    s#4#2#1   balan@24            -1
    s#4#2#2   OBJECTIV           1.1
    s#4#2#2   balan@26             1
    s#4#2#2   balan@25            -1
    s#4#2#3   OBJECTIV           1.1
    s#4#2#3   balan@27             1
    s#4#2#3   balan@26            -1
    s#4#2#4   OBJECTIV           1.1
    s#4#2#4   balan@28             1
    s#4#2#4   balan@27            -1
    s#4#2#5   OBJECTIV           1.1
    s#4#2#5   balan@28            -1
RHS
    RHS       select_1             1
    RHS       balanc@1           964
    RHS       balanc@2            21
    RHS       balanc@3           337
    RHS       balanc@4           669
    RHS       balanc@5           180
    RHS       balanc@b           333
    RHS       balanc@c           776
    RHS       balanc@d           466
    RHS       balanc@e           764
    RHS       balanc@f           166
    RHS       balan@10           239
    RHS       balan@11           425
    RHS       balan@12           220
    RHS       balan@13           452
    RHS       balan@14           519
    RHS       balan@15           136
    RHS       balan@16           621
    RHS       balan@17           192
    RHS       balan@18            74
    RHS       balan@19           510
    RHS       balan@1a             7
    RHS       balan@1b            27
    RHS       balan@1c           934
    RHS       balan@1d           620
    RHS       balan@1e           585
    RHS       balan@24           914
    RHS       balan@25           988
    RHS       balan@26           465
    RHS       balan@27           318
    RHS       balan@28           243
    RHS       valid_1           2171
    RHS       valid_2           2505
    RHS       valid_3           1855
    RHS       valid_4           1533
    RHS       valid_5           2173
    RHS       valid_6           2928
BOUNDS
 LO BOUND     r#1#1#0              0
 PL BOUND     r#1#1#0 
 LO BOUND     r#1#1#1              0
 PL BOUND     r#1#1#1 
 LO BOUND     r#1#1#2              0
 PL BOUND     r#1#1#2 
 LO BOUND     r#1#1#3              0
 PL BOUND     r#1#1#3 
 LO BOUND     r#1#1#4              0
 PL BOUND     r#1#1#4 
 LO BOUND     r#1#1#5              0
 PL BOUND     r#1#1#5 
 LO BOUND     r#1#2#0              0
 PL BOUND     r#1#2#0 
 LO BOUND     r#1#2#1              0
 PL BOUND     r#1#2#1 
 LO BOUND     r#1#2#2              0
 PL BOUND     r#1#2#2 
 LO BOUND     r#1#2#3              0
 PL BOUND     r#1#2#3 
 LO BOUND     r#1#2#4              0
 PL BOUND     r#1#2#4 
 LO BOUND     r#1#2#5              0
 PL BOUND     r#1#2#5 
 LO BOUND     r#2#1#0              0
 PL BOUND     r#2#1#0 
 LO BOUND     r#2#1#1              0
 PL BOUND     r#2#1#1 
 LO BOUND     r#2#1#2              0
 PL BOUND     r#2#1#2 
 LO BOUND     r#2#1#3              0
 PL BOUND     r#2#1#3 
 LO BOUND     r#2#1#4              0
 PL BOUND     r#2#1#4 
 LO BOUND     r#2#1#5              0
 PL BOUND     r#2#1#5 
 LO BOUND     r#2#2#0              0
 PL BOUND     r#2#2#0 
 LO BOUND     r#2#2#1              0
 PL BOUND     r#2#2#1 
 LO BOUND     r#2#2#2              0
 PL BOUND     r#2#2#2 
 LO BOUND     r#2#2#3              0
 PL BOUND     r#2#2#3 
 LO BOUND     r#2#2#4              0
 PL BOUND     r#2#2#4 
 LO BOUND     r#2#2#5              0
 PL BOUND     r#2#2#5 
 LO BOUND     r#3#1#0              0
 PL BOUND     r#3#1#0 
 LO BOUND     r#3#1#1              0
 PL BOUND     r#3#1#1 
 LO BOUND     r#3#1#2              0
 PL BOUND     r#3#1#2 
 LO BOUND     r#3#1#3              0
 PL BOUND     r#3#1#3 
 LO BOUND     r#3#1#4              0
 PL BOUND     r#3#1#4 
 LO BOUND     r#3#1#5              0
 PL BOUND     r#3#1#5 
 LO BOUND     r#3#2#0              0
 PL BOUND     r#3#2#0 
 LO BOUND     r#3#2#1              0
 PL BOUND     r#3#2#1 
 LO BOUND     r#3#2#2              0
 PL BOUND     r#3#2#2 
 LO BOUND     r#3#2#3              0
 PL BOUND     r#3#2#3 
 LO BOUND     r#3#2#4              0
 PL BOUND     r#3#2#4 
 LO BOUND     r#3#2#5              0
 PL BOUND     r#3#2#5 
 LO BOUND     r#4#1#0              0
 PL BOUND     r#4#1#0 
 LO BOUND     r#4#1#1              0
 PL BOUND     r#4#1#1 
 LO BOUND     r#4#1#2              0
 PL BOUND     r#4#1#2 
 LO BOUND     r#4#1#3              0
 PL BOUND     r#4#1#3 
 LO BOUND     r#4#1#4              0
 PL BOUND     r#4#1#4 
 LO BOUND     r#4#1#5              0
 PL BOUND     r#4#1#5 
 LO BOUND     r#4#2#0              0
 PL BOUND     r#4#2#0 
 LO BOUND     r#4#2#1              0
 PL BOUND     r#4#2#1 
 LO BOUND     r#4#2#2              0
 PL BOUND     r#4#2#2 
 LO BOUND     r#4#2#3              0
 PL BOUND     r#4#2#3 
 LO BOUND     r#4#2#4              0
 PL BOUND     r#4#2#4 
 LO BOUND     r#4#2#5              0
 PL BOUND     r#4#2#5 
 LO BOUND     s#1#1#0              0
 PL BOUND     s#1#1#0 
 LO BOUND     s#1#1#1              0
 PL BOUND     s#1#1#1 
 LO BOUND     s#1#1#2              0
 PL BOUND     s#1#1#2 
 LO BOUND     s#1#1#3              0
 PL BOUND     s#1#1#3 
 LO BOUND     s#1#1#4              0
 PL BOUND     s#1#1#4 
 LO BOUND     s#1#1#5              0
 PL BOUND     s#1#1#5 
 LO BOUND     s#1#2#0              0
 PL BOUND     s#1#2#0 
 LO BOUND     s#1#2#1              0
 PL BOUND     s#1#2#1 
 LO BOUND     s#1#2#2              0
 PL BOUND     s#1#2#2 
 LO BOUND     s#1#2#3              0
 PL BOUND     s#1#2#3 
 LO BOUND     s#1#2#4              0
 PL BOUND     s#1#2#4 
 LO BOUND     s#1#2#5              0
 PL BOUND     s#1#2#5 
 LO BOUND     s#2#1#0              0
 PL BOUND     s#2#1#0 
 LO BOUND     s#2#1#1              0
 PL BOUND     s#2#1#1 
 LO BOUND     s#2#1#2              0
 PL BOUND     s#2#1#2 
 LO BOUND     s#2#1#3              0
 PL BOUND     s#2#1#3 
 LO BOUND     s#2#1#4              0
 PL BOUND     s#2#1#4 
 LO BOUND     s#2#1#5              0
 PL BOUND     s#2#1#5 
 LO BOUND     s#2#2#0              0
 PL BOUND     s#2#2#0 
 LO BOUND     s#2#2#1              0
 PL BOUND     s#2#2#1 
 LO BOUND     s#2#2#2              0
 PL BOUND     s#2#2#2 
 LO BOUND     s#2#2#3              0
 PL BOUND     s#2#2#3 
 LO BOUND     s#2#2#4              0
 PL BOUND     s#2#2#4 
 LO BOUND     s#2#2#5              0
 PL BOUND     s#2#2#5 
 LO BOUND     s#3#1#0              0
 PL BOUND     s#3#1#0 
 LO BOUND     s#3#1#1              0
 PL BOUND     s#3#1#1 
 LO BOUND     s#3#1#2              0
 PL BOUND     s#3#1#2 
 LO BOUND     s#3#1#3              0
 PL BOUND     s#3#1#3 
 LO BOUND     s#3#1#4              0
 PL BOUND     s#3#1#4 
 LO BOUND     s#3#1#5              0
 PL BOUND     s#3#1#5 
 LO BOUND     s#3#2#0              0
 PL BOUND     s#3#2#0 
 LO BOUND     s#3#2#1              0
 PL BOUND     s#3#2#1 
 LO BOUND     s#3#2#2              0
 PL BOUND     s#3#2#2 
 LO BOUND     s#3#2#3              0
 PL BOUND     s#3#2#3 
 LO BOUND     s#3#2#4              0
 PL BOUND     s#3#2#4 
 LO BOUND     s#3#2#5              0
 PL BOUND     s#3#2#5 
 LO BOUND     s#4#1#0              0
 PL BOUND     s#4#1#0 
 LO BOUND     s#4#1#1              0
 PL BOUND     s#4#1#1 
 LO BOUND     s#4#1#2              0
 PL BOUND     s#4#1#2 
 LO BOUND     s#4#1#3              0
 PL BOUND     s#4#1#3 
 LO BOUND     s#4#1#4              0
 PL BOUND     s#4#1#4 
 LO BOUND     s#4#1#5              0
 PL BOUND     s#4#1#5 
 LO BOUND     s#4#2#0              0
 PL BOUND     s#4#2#0 
 LO BOUND     s#4#2#1              0
 PL BOUND     s#4#2#1 
 LO BOUND     s#4#2#2              0
 PL BOUND     s#4#2#2 
 LO BOUND     s#4#2#3              0
 PL BOUND     s#4#2#3 
 LO BOUND     s#4#2#4              0
 PL BOUND     s#4#2#4 
 LO BOUND     s#4#2#5              0
 PL BOUND     s#4#2#5 
 LO BOUND     x#1#1#1              0
 PL BOUND     x#1#1#1 
 LO BOUND     x#1#1#2              0
 PL BOUND     x#1#1#2 
 LO BOUND     x#1#1#3              0
 PL BOUND     x#1#1#3 
 LO BOUND     x#1#1#4              0
 PL BOUND     x#1#1#4 
 LO BOUND     x#1#1#5              0
 PL BOUND     x#1#1#5 
 LO BOUND     x#1#2#1              0
 PL BOUND     x#1#2#1 
 LO BOUND     x#1#2#2              0
 PL BOUND     x#1#2#2 
 LO BOUND     x#1#2#3              0
 PL BOUND     x#1#2#3 
 LO BOUND     x#1#2#4              0
 PL BOUND     x#1#2#4 
 LO BOUND     x#1#2#5              0
 PL BOUND     x#1#2#5 
 LO BOUND     x#2#1#1              0
 PL BOUND     x#2#1#1 
 LO BOUND     x#2#1#2              0
 PL BOUND     x#2#1#2 
 LO BOUND     x#2#1#3              0
 PL BOUND     x#2#1#3 
 LO BOUND     x#2#1#4              0
 PL BOUND     x#2#1#4 
 LO BOUND     x#2#1#5              0
 PL BOUND     x#2#1#5 
 LO BOUND     x#2#2#1              0
 PL BOUND     x#2#2#1 
 LO BOUND     x#2#2#2              0
 PL BOUND     x#2#2#2 
 LO BOUND     x#2#2#3              0
 PL BOUND     x#2#2#3 
 LO BOUND     x#2#2#4              0
 PL BOUND     x#2#2#4 
 LO BOUND     x#2#2#5              0
 PL BOUND     x#2#2#5 
 LO BOUND     x#3#1#1              0
 PL BOUND     x#3#1#1 
 LO BOUND     x#3#1#2              0
 PL BOUND     x#3#1#2 
 LO BOUND     x#3#1#3              0
 PL BOUND     x#3#1#3 
 LO BOUND     x#3#1#4              0
 PL BOUND     x#3#1#4 
 LO BOUND     x#3#1#5              0
 PL BOUND     x#3#1#5 
 LO BOUND     x#3#2#1              0
 PL BOUND     x#3#2#1 
 LO BOUND     x#3#2#2              0
 PL BOUND     x#3#2#2 
 LO BOUND     x#3#2#3              0
 PL BOUND     x#3#2#3 
 LO BOUND     x#3#2#4              0
 PL BOUND     x#3#2#4 
 LO BOUND     x#3#2#5              0
 PL BOUND     x#3#2#5 
 LO BOUND     x#4#1#1              0
 PL BOUND     x#4#1#1 
 LO BOUND     x#4#1#2              0
 PL BOUND     x#4#1#2 
 LO BOUND     x#4#1#3              0
 PL BOUND     x#4#1#3 
 LO BOUND     x#4#1#4              0
 PL BOUND     x#4#1#4 
 LO BOUND     x#4#1#5              0
 PL BOUND     x#4#1#5 
 LO BOUND     x#4#2#1              0
 PL BOUND     x#4#2#1 
 LO BOUND     x#4#2#2              0
 PL BOUND     x#4#2#2 
 LO BOUND     x#4#2#3              0
 PL BOUND     x#4#2#3 
 LO BOUND     x#4#2#4              0
 PL BOUND     x#4#2#4 
 LO BOUND     x#4#2#5              0
 PL BOUND     x#4#2#5 
 LO BOUND     y#1#1#1              0
 PL BOUND     y#1#1#1 
 LO BOUND     y#1#1#2              0
 PL BOUND     y#1#1#2 
 LO BOUND     y#1#1#3              0
 PL BOUND     y#1#1#3 
 LO BOUND     y#1#1#4              0
 PL BOUND     y#1#1#4 
 LO BOUND     y#1#1#5              0
 PL BOUND     y#1#1#5 
 LO BOUND     y#1#2#1              0
 PL BOUND     y#1#2#1 
 LO BOUND     y#1#2#2              0
 PL BOUND     y#1#2#2 
 LO BOUND     y#1#2#3              0
 PL BOUND     y#1#2#3 
 LO BOUND     y#1#2#4              0
 PL BOUND     y#1#2#4 
 LO BOUND     y#1#2#5              0
 PL BOUND     y#1#2#5 
 LO BOUND     y#1#3#1              0
 PL BOUND     y#1#3#1 
 LO BOUND     y#1#3#2              0
 PL BOUND     y#1#3#2 
 LO BOUND     y#1#3#3              0
 PL BOUND     y#1#3#3 
 LO BOUND     y#1#3#4              0
 PL BOUND     y#1#3#4 
 LO BOUND     y#1#3#5              0
 PL BOUND     y#1#3#5 
 LO BOUND     y#1#4#1              0
 PL BOUND     y#1#4#1 
 LO BOUND     y#1#4#2              0
 PL BOUND     y#1#4#2 
 LO BOUND     y#1#4#3              0
 PL BOUND     y#1#4#3 
 LO BOUND     y#1#4#4              0
 PL BOUND     y#1#4#4 
 LO BOUND     y#1#4#5              0
 PL BOUND     y#1#4#5 
 LO BOUND     y#1#5#1              0
 PL BOUND     y#1#5#1 
 LO BOUND     y#1#5#2              0
 PL BOUND     y#1#5#2 
 LO BOUND     y#1#5#3              0
 PL BOUND     y#1#5#3 
 LO BOUND     y#1#5#4              0
 PL BOUND     y#1#5#4 
 LO BOUND     y#1#5#5              0
 PL BOUND     y#1#5#5 
 LO BOUND     y#2#1#1              0
 PL BOUND     y#2#1#1 
 LO BOUND     y#2#1#2              0
 PL BOUND     y#2#1#2 
 LO BOUND     y#2#1#3              0
 PL BOUND     y#2#1#3 
 LO BOUND     y#2#1#4              0
 PL BOUND     y#2#1#4 
 LO BOUND     y#2#1#5              0
 PL BOUND     y#2#1#5 
 LO BOUND     y#2#2#1              0
 PL BOUND     y#2#2#1 
 LO BOUND     y#2#2#2              0
 PL BOUND     y#2#2#2 
 LO BOUND     y#2#2#3              0
 PL BOUND     y#2#2#3 
 LO BOUND     y#2#2#4              0
 PL BOUND     y#2#2#4 
 LO BOUND     y#2#2#5              0
 PL BOUND     y#2#2#5 
 LO BOUND     y#2#3#1              0
 PL BOUND     y#2#3#1 
 LO BOUND     y#2#3#2              0
 PL BOUND     y#2#3#2 
 LO BOUND     y#2#3#3              0
 PL BOUND     y#2#3#3 
 LO BOUND     y#2#3#4              0
 PL BOUND     y#2#3#4 
 LO BOUND     y#2#3#5              0
 PL BOUND     y#2#3#5 
 LO BOUND     y#2#4#1              0
 PL BOUND     y#2#4#1 
 LO BOUND     y#2#4#2              0
 PL BOUND     y#2#4#2 
 LO BOUND     y#2#4#3              0
 PL BOUND     y#2#4#3 
 LO BOUND     y#2#4#4              0
 PL BOUND     y#2#4#4 
 LO BOUND     y#2#4#5              0
 PL BOUND     y#2#4#5 
 LO BOUND     y#2#5#1              0
 PL BOUND     y#2#5#1 
 LO BOUND     y#2#5#2              0
 PL BOUND     y#2#5#2 
 LO BOUND     y#2#5#3              0
 PL BOUND     y#2#5#3 
 LO BOUND     y#2#5#4              0
 PL BOUND     y#2#5#4 
 LO BOUND     y#2#5#5              0
 PL BOUND     y#2#5#5 
 LO BOUND     y#3#1#1              0
 PL BOUND     y#3#1#1 
 LO BOUND     y#3#1#2              0
 PL BOUND     y#3#1#2 
 LO BOUND     y#3#1#3              0
 PL BOUND     y#3#1#3 
 LO BOUND     y#3#1#4              0
 PL BOUND     y#3#1#4 
 LO BOUND     y#3#1#5              0
 PL BOUND     y#3#1#5 
 LO BOUND     y#3#2#1              0
 PL BOUND     y#3#2#1 
 LO BOUND     y#3#2#2              0
 PL BOUND     y#3#2#2 
 LO BOUND     y#3#2#3              0
 PL BOUND     y#3#2#3 
 LO BOUND     y#3#2#4              0
 PL BOUND     y#3#2#4 
 LO BOUND     y#3#2#5              0
 PL BOUND     y#3#2#5 
 LO BOUND     y#3#3#1              0
 PL BOUND     y#3#3#1 
 LO BOUND     y#3#3#2              0
 PL BOUND     y#3#3#2 
 LO BOUND     y#3#3#3              0
 PL BOUND     y#3#3#3 
 LO BOUND     y#3#3#4              0
 PL BOUND     y#3#3#4 
 LO BOUND     y#3#3#5              0
 PL BOUND     y#3#3#5 
 LO BOUND     y#3#4#1              0
 PL BOUND     y#3#4#1 
 LO BOUND     y#3#4#2              0
 PL BOUND     y#3#4#2 
 LO BOUND     y#3#4#3              0
 PL BOUND     y#3#4#3 
 LO BOUND     y#3#4#4              0
 PL BOUND     y#3#4#4 
 LO BOUND     y#3#4#5              0
 PL BOUND     y#3#4#5 
 LO BOUND     y#3#5#1              0
 PL BOUND     y#3#5#1 
 LO BOUND     y#3#5#2              0
 PL BOUND     y#3#5#2 
 LO BOUND     y#3#5#3              0
 PL BOUND     y#3#5#3 
 LO BOUND     y#3#5#4              0
 PL BOUND     y#3#5#4 
 LO BOUND     y#3#5#5              0
 PL BOUND     y#3#5#5 
 LO BOUND     y#4#1#1              0
 PL BOUND     y#4#1#1 
 LO BOUND     y#4#1#2              0
 PL BOUND     y#4#1#2 
 LO BOUND     y#4#1#3              0
 PL BOUND     y#4#1#3 
 LO BOUND     y#4#1#4              0
 PL BOUND     y#4#1#4 
 LO BOUND     y#4#1#5              0
 PL BOUND     y#4#1#5 
 LO BOUND     y#4#2#1              0
 PL BOUND     y#4#2#1 
 LO BOUND     y#4#2#2              0
 PL BOUND     y#4#2#2 
 LO BOUND     y#4#2#3              0
 PL BOUND     y#4#2#3 
 LO BOUND     y#4#2#4              0
 PL BOUND     y#4#2#4 
 LO BOUND     y#4#2#5              0
 PL BOUND     y#4#2#5 
 LO BOUND     y#4#3#1              0
 PL BOUND     y#4#3#1 
 LO BOUND     y#4#3#2              0
 PL BOUND     y#4#3#2 
 LO BOUND     y#4#3#3              0
 PL BOUND     y#4#3#3 
 LO BOUND     y#4#3#4              0
 PL BOUND     y#4#3#4 
 LO BOUND     y#4#3#5              0
 PL BOUND     y#4#3#5 
 LO BOUND     y#4#4#1              0
 PL BOUND     y#4#4#1 
 LO BOUND     y#4#4#2              0
 PL BOUND     y#4#4#2 
 LO BOUND     y#4#4#3              0
 PL BOUND     y#4#4#3 
 LO BOUND     y#4#4#4              0
 PL BOUND     y#4#4#4 
 LO BOUND     y#4#4#5              0
 PL BOUND     y#4#4#5 
 LO BOUND     y#4#5#1              0
 PL BOUND     y#4#5#1 
 LO BOUND     y#4#5#2              0
 PL BOUND     y#4#5#2 
 LO BOUND     y#4#5#3              0
 PL BOUND     y#4#5#3 
 LO BOUND     y#4#5#4              0
 PL BOUND     y#4#5#4 
 LO BOUND     y#4#5#5              0
 PL BOUND     y#4#5#5 
 LO BOUND     z#1                  0
 UP BOUND     z#1                  1
 LO BOUND     z#2                  0
 UP BOUND     z#2                  1
 LO BOUND     z#3                  0
 UP BOUND     z#3                  1
 LO BOUND     z#4                  0
 UP BOUND     z#4                  1
 LO BOUND     z#5                  0
 UP BOUND     z#5                  1
ENDATA
