* This file was automatically generated by Zimpl
* param Q2 := 1;
* do print file2;
* param nC := read file1 as "1n" use 1;
* param nI := read file1 as "2n" use 1;
* param m  := read file1 as "3n" use 1;
* param nT := read file1 as "4n" use 1;
* param nP := read file2 as "1n" use 1;
* set C := { 1 .. nC };
* set I := { 1 .. nI };
* set T0 := { 0 .. nT };
* set T := { 1 .. nT };
* set P := { 1 .. nP };
* param inveCost[I] := read file1 as "<1n> 2n" skip 1 use nI;
* param backCost[I] := read file1 as "<1n> 2n" skip nI+1 use nI;
* param demand[C*I*T] := read file1 as "<1n,2n,3n> 4n" skip 2*nI+1;
* param q[P*I] := read file2 as "<1n,2n> 3n" skip 1;
* param D[<c,i> in C*I] := ceil( sum <t> in T : demand[c,i,t]/Q2 );
* set Pc[<c> in C] := inter <i> in { <i> in I with ( sum <t> in T : demand[c,i,t] ) > 0 } : { <p> in P with q[p,i] > 0 };
* param M[<c,p> in C*P] := max <i> in I with q[p,i] > 0: ceil( sum <t> in T : demand[c,i,t]/Q2/q[p,i] );
* var r[C*I*T0] >= 0;
* var s[C*I*T0] >= 0;
* var x[C*I*T] integer >= 0;
* var y[C*P*T] integer >= 0;
* var z[P] binary;
* minimize cost: sum <i> in I: ( sum <t> in T: (sum <c> in C : (inveCost[i] * s[c,i,t]  + backCost[i] * r[c,i,t]) ));
* subto select:       sum <p> in P: z[p] <= m;
* subto balance:    forall <c,i,t> in C*I*T with t>=1 do       s[c,i,t-1] - r[c,i,t-1] + Q1*Q2*x[c,i,t] + Q2 * (sum <p> in Pc[c
* ]: q[p,i] * y[c,p,t]) == demand[c,i,t] + s[c,i,t] - r[c,i,t];
* subto valid:    forall <c,i> in C*I do       sum <t> in T: ( min(Q1, D[c,i]) * x[c,i,t] + sum <p> in Pc[c]: ( min(q[p,i], D[c
* ,i] ) * y[c,p,t]) ) >= D[c,i];
* subto BigM:    forall <c,p,t> in C*P*T with t>=1 do       y[c,p,t] <= M[c,p] * z[p];
* subto init1:    forall <c,i> in C*I do       s[c,i,0] == 0;
* subto init2:    forall <c,i> in C*I do       r[c,i,0] == 0;
* subto init3:    forall <c,i> in C*I do       r[c,i,nT] == 0;
NAME          mpdp.zpl
ROWS
 N  OBJECTIV          
 L  select_1          
 E  balanc@1          
 E  balanc@2          
 E  balanc@3          
 E  balanc@4          
 E  balanc@5          
 E  balanc@6          
 E  balanc@7          
 E  balanc@8          
 E  balanc@9          
 E  balanc@a          
 E  balanc@b          
 E  balanc@c          
 E  balanc@d          
 E  balanc@e          
 E  balanc@f          
 E  balan@10          
 E  balan@11          
 E  balan@12          
 E  balan@13          
 E  balan@14          
 E  balan@15          
 E  balan@16          
 E  balan@17          
 E  balan@18          
 E  balan@19          
 E  balan@1a          
 E  balan@1b          
 E  balan@1c          
 E  balan@1d          
 E  balan@1e          
 E  balan@1f          
 E  balan@20          
 E  balan@21          
 E  balan@22          
 E  balan@23          
 E  balan@24          
 E  balan@25          
 E  balan@26          
 E  balan@27          
 E  balan@28          
 G  valid_1           
 G  valid_2           
 G  valid_3           
 G  valid_4           
 G  valid_5           
 G  valid_6           
 G  valid_7           
 G  valid_8           
 L  BigM_1            
 L  BigM_2            
 L  BigM_3            
 L  BigM_4            
 L  BigM_5            
 L  BigM_6            
 L  BigM_7            
 L  BigM_8            
 L  BigM_9            
 L  BigM_10           
 L  BigM_11           
 L  BigM_12           
 L  BigM_13           
 L  BigM_14           
 L  BigM_15           
 L  BigM_16           
 L  BigM_17           
 L  BigM_18           
 L  BigM_19           
 L  BigM_20           
 L  BigM_21           
 L  BigM_22           
 L  BigM_23           
 L  BigM_24           
 L  BigM_25           
 L  BigM_26           
 L  BigM_27           
 L  BigM_28           
 L  BigM_29           
 L  BigM_30           
 L  BigM_31           
 L  BigM_32           
 L  BigM_33           
 L  BigM_34           
 L  BigM_35           
 L  BigM_36           
 L  BigM_37           
 L  BigM_38           
 L  BigM_39           
 L  BigM_40           
 L  BigM_41           
 L  BigM_42           
 L  BigM_43           
 L  BigM_44           
 L  BigM_45           
 L  BigM_46           
 L  BigM_47           
 L  BigM_48           
 L  BigM_49           
 L  BigM_50           
 L  BigM_51           
 L  BigM_52           
 L  BigM_53           
 L  BigM_54           
 L  BigM_55           
 L  BigM_56           
 L  BigM_57           
 L  BigM_58           
 L  BigM_59           
 L  BigM_60           
 L  BigM_61           
 L  BigM_62           
 L  BigM_63           
 L  BigM_64           
 L  BigM_65           
 L  BigM_66           
 L  BigM_67           
 L  BigM_68           
 L  BigM_69           
 L  BigM_70           
 L  BigM_71           
 L  BigM_72           
 L  BigM_73           
 L  BigM_74           
 L  BigM_75           
 L  BigM_76           
 L  BigM_77           
 L  BigM_78           
 L  BigM_79           
 L  BigM_80           
 L  BigM_81           
 L  BigM_82           
 L  BigM_83           
 L  BigM_84           
 L  BigM_85           
 L  BigM_86           
 L  BigM_87           
 L  BigM_88           
 L  BigM_89           
 L  BigM_90           
 L  BigM_91           
 L  BigM_92           
 L  BigM_93           
 L  BigM_94           
 L  BigM_95           
 L  BigM_96           
 L  BigM_97           
 L  BigM_98           
 L  BigM_99           
 L  BigM_100          
 E  init1_1           
 E  init1_2           
 E  init1_3           
 E  init1_4           
 E  init1_5           
 E  init1_6           
 E  init1_7           
 E  init1_8           
 E  init1_9           
 E  init1_10          
 E  init2_1           
 E  init2_2           
 E  init2_3           
 E  init2_4           
 E  init2_5           
 E  init2_6           
 E  init2_7           
 E  init2_8           
 E  init2_9           
 E  init2_10          
 E  init3_1           
 E  init3_2           
 E  init3_3           
 E  init3_4           
 E  init3_5           
 E  init3_6           
 E  init3_7           
 E  init3_8           
 E  init3_9           
 E  init3_10          
COLUMNS
    MARK0000  'MARKER'                 'INTORG'
    x#1#1#1   valid_1             72
    x#1#1#1   balanc@1            72
    x#1#1#2   valid_1             72
    x#1#1#2   balanc@2            72
    x#1#1#3   valid_1             72
    x#1#1#3   balanc@3            72
    x#1#1#4   valid_1             72
    x#1#1#4   balanc@4            72
    x#1#2#1   valid_2             72
    x#1#2#1   balanc@5            72
    x#1#2#2   valid_2             72
    x#1#2#2   balanc@6            72
    x#1#2#3   valid_2             72
    x#1#2#3   balanc@7            72
    x#1#2#4   valid_2             72
    x#1#2#4   balanc@8            72
    x#2#1#1   valid_3             72
    x#2#1#1   balanc@9            72
    x#2#1#2   valid_3             72
    x#2#1#2   balanc@a            72
    x#2#1#3   valid_3             72
    x#2#1#3   balanc@b            72
    x#2#1#4   valid_3             72
    x#2#1#4   balanc@c            72
    x#2#2#1   valid_4             72
    x#2#2#1   balanc@d            72
    x#2#2#2   valid_4             72
    x#2#2#2   balanc@e            72
    x#2#2#3   valid_4             72
    x#2#2#3   balanc@f            72
    x#2#2#4   valid_4             72
    x#2#2#4   balan@10            72
    x#3#1#1   balan@11            72
    x#3#1#2   balan@12            72
    x#3#1#3   balan@13            72
    x#3#1#4   balan@14            72
    x#3#2#1   valid_5             72
    x#3#2#1   balan@15            72
    x#3#2#2   valid_5             72
    x#3#2#2   balan@16            72
    x#3#2#3   valid_5             72
    x#3#2#3   balan@17            72
    x#3#2#4   valid_5             72
    x#3#2#4   balan@18            72
    x#4#1#1   valid_6             72
    x#4#1#1   balan@19            72
    x#4#1#2   valid_6             72
    x#4#1#2   balan@1a            72
    x#4#1#3   valid_6             72
    x#4#1#3   balan@1b            72
    x#4#1#4   valid_6             72
    x#4#1#4   balan@1c            72
    x#4#2#1   valid_7             72
    x#4#2#1   balan@1d            72
    x#4#2#2   valid_7             72
    x#4#2#2   balan@1e            72
    x#4#2#3   valid_7             72
    x#4#2#3   balan@1f            72
    x#4#2#4   valid_7             72
    x#4#2#4   balan@20            72
    x#5#1#1   valid_8             72
    x#5#1#1   balan@21            72
    x#5#1#2   valid_8             72
    x#5#1#2   balan@22            72
    x#5#1#3   valid_8             72
    x#5#1#3   balan@23            72
    x#5#1#4   valid_8             72
    x#5#1#4   balan@24            72
    x#5#2#1   balan@25            72
    x#5#2#2   balan@26            72
    x#5#2#3   balan@27            72
    x#5#2#4   balan@28            72
    y#1#1#1   BigM_1               1
    y#1#1#1   valid_2             34
    y#1#1#1   valid_1             38
    y#1#1#1   balanc@5            34
    y#1#1#1   balanc@1            38
    y#1#1#2   BigM_2               1
    y#1#1#2   valid_2             34
    y#1#1#2   valid_1             38
    y#1#1#2   balanc@6            34
    y#1#1#2   balanc@2            38
    y#1#1#3   BigM_3               1
    y#1#1#3   valid_2             34
    y#1#1#3   valid_1             38
    y#1#1#3   balanc@7            34
    y#1#1#3   balanc@3            38
    y#1#1#4   BigM_4               1
    y#1#1#4   valid_2             34
    y#1#1#4   valid_1             38
    y#1#1#4   balanc@8            34
    y#1#1#4   balanc@4            38
    y#1#2#1   BigM_5               1
    y#1#2#1   valid_2             24
    y#1#2#1   valid_1             48
    y#1#2#1   balanc@5            24
    y#1#2#1   balanc@1            48
    y#1#2#2   BigM_6               1
    y#1#2#2   valid_2             24
    y#1#2#2   valid_1             48
    y#1#2#2   balanc@6            24
    y#1#2#2   balanc@2            48
    y#1#2#3   BigM_7               1
    y#1#2#3   valid_2             24
    y#1#2#3   valid_1             48
    y#1#2#3   balanc@7            24
    y#1#2#3   balanc@3            48
    y#1#2#4   BigM_8               1
    y#1#2#4   valid_2             24
    y#1#2#4   valid_1             48
    y#1#2#4   balanc@8            24
    y#1#2#4   balanc@4            48
    y#1#3#1   BigM_9               1
    y#1#3#1   valid_2             19
    y#1#3#1   valid_1             53
    y#1#3#1   balanc@5            19
    y#1#3#1   balanc@1            53
    y#1#3#2   BigM_10              1
    y#1#3#2   valid_2             19
    y#1#3#2   valid_1             53
    y#1#3#2   balanc@6            19
    y#1#3#2   balanc@2            53
    y#1#3#3   BigM_11              1
    y#1#3#3   valid_2             19
    y#1#3#3   valid_1             53
    y#1#3#3   balanc@7            19
    y#1#3#3   balanc@3            53
    y#1#3#4   BigM_12              1
    y#1#3#4   valid_2             19
    y#1#3#4   valid_1             53
    y#1#3#4   balanc@8            19
    y#1#3#4   balanc@4            53
    y#1#4#1   BigM_13              1
    y#1#4#1   valid_2             47
    y#1#4#1   valid_1             25
    y#1#4#1   balanc@5            47
    y#1#4#1   balanc@1            25
    y#1#4#2   BigM_14              1
    y#1#4#2   valid_2             47
    y#1#4#2   valid_1             25
    y#1#4#2   balanc@6            47
    y#1#4#2   balanc@2            25
    y#1#4#3   BigM_15              1
    y#1#4#3   valid_2             47
    y#1#4#3   valid_1             25
    y#1#4#3   balanc@7            47
    y#1#4#3   balanc@3            25
    y#1#4#4   BigM_16              1
    y#1#4#4   valid_2             47
    y#1#4#4   valid_1             25
    y#1#4#4   balanc@8            47
    y#1#4#4   balanc@4            25
    y#1#5#1   BigM_17              1
    y#1#5#1   valid_2             10
    y#1#5#1   valid_1             62
    y#1#5#1   balanc@5            10
    y#1#5#1   balanc@1            62
    y#1#5#2   BigM_18              1
    y#1#5#2   valid_2             10
    y#1#5#2   valid_1             62
    y#1#5#2   balanc@6            10
    y#1#5#2   balanc@2            62
    y#1#5#3   BigM_19              1
    y#1#5#3   valid_2             10
    y#1#5#3   valid_1             62
    y#1#5#3   balanc@7            10
    y#1#5#3   balanc@3            62
    y#1#5#4   BigM_20              1
    y#1#5#4   valid_2             10
    y#1#5#4   valid_1             62
    y#1#5#4   balanc@8            10
    y#1#5#4   balanc@4            62
    y#2#1#1   BigM_21              1
    y#2#1#1   valid_4             34
    y#2#1#1   valid_3             38
    y#2#1#1   balanc@d            34
    y#2#1#1   balanc@9            38
    y#2#1#2   BigM_22              1
    y#2#1#2   valid_4             34
    y#2#1#2   valid_3             38
    y#2#1#2   balanc@e            34
    y#2#1#2   balanc@a            38
    y#2#1#3   BigM_23              1
    y#2#1#3   valid_4             34
    y#2#1#3   valid_3             38
    y#2#1#3   balanc@f            34
    y#2#1#3   balanc@b            38
    y#2#1#4   BigM_24              1
    y#2#1#4   valid_4             34
    y#2#1#4   valid_3             38
    y#2#1#4   balan@10            34
    y#2#1#4   balanc@c            38
    y#2#2#1   BigM_25              1
    y#2#2#1   valid_4             24
    y#2#2#1   valid_3             48
    y#2#2#1   balanc@d            24
    y#2#2#1   balanc@9            48
    y#2#2#2   BigM_26              1
    y#2#2#2   valid_4             24
    y#2#2#2   valid_3             48
    y#2#2#2   balanc@e            24
    y#2#2#2   balanc@a            48
    y#2#2#3   BigM_27              1
    y#2#2#3   valid_4             24
    y#2#2#3   valid_3             48
    y#2#2#3   balanc@f            24
    y#2#2#3   balanc@b            48
    y#2#2#4   BigM_28              1
    y#2#2#4   valid_4             24
    y#2#2#4   valid_3             48
    y#2#2#4   balan@10            24
    y#2#2#4   balanc@c            48
    y#2#3#1   BigM_29              1
    y#2#3#1   valid_4             19
    y#2#3#1   valid_3             53
    y#2#3#1   balanc@d            19
    y#2#3#1   balanc@9            53
    y#2#3#2   BigM_30              1
    y#2#3#2   valid_4             19
    y#2#3#2   valid_3             53
    y#2#3#2   balanc@e            19
    y#2#3#2   balanc@a            53
    y#2#3#3   BigM_31              1
    y#2#3#3   valid_4             19
    y#2#3#3   valid_3             53
    y#2#3#3   balanc@f            19
    y#2#3#3   balanc@b            53
    y#2#3#4   BigM_32              1
    y#2#3#4   valid_4             19
    y#2#3#4   valid_3             53
    y#2#3#4   balan@10            19
    y#2#3#4   balanc@c            53
    y#2#4#1   BigM_33              1
    y#2#4#1   valid_4             47
    y#2#4#1   valid_3             25
    y#2#4#1   balanc@d            47
    y#2#4#1   balanc@9            25
    y#2#4#2   BigM_34              1
    y#2#4#2   valid_4             47
    y#2#4#2   valid_3             25
    y#2#4#2   balanc@e            47
    y#2#4#2   balanc@a            25
    y#2#4#3   BigM_35              1
    y#2#4#3   valid_4             47
    y#2#4#3   valid_3             25
    y#2#4#3   balanc@f            47
    y#2#4#3   balanc@b            25
    y#2#4#4   BigM_36              1
    y#2#4#4   valid_4             47
    y#2#4#4   valid_3             25
    y#2#4#4   balan@10            47
    y#2#4#4   balanc@c            25
    y#2#5#1   BigM_37              1
    y#2#5#1   valid_4             10
    y#2#5#1   valid_3             62
    y#2#5#1   balanc@d            10
    y#2#5#1   balanc@9            62
    y#2#5#2   BigM_38              1
    y#2#5#2   valid_4             10
    y#2#5#2   valid_3             62
    y#2#5#2   balanc@e            10
    y#2#5#2   balanc@a            62
    y#2#5#3   BigM_39              1
    y#2#5#3   valid_4             10
    y#2#5#3   valid_3             62
    y#2#5#3   balanc@f            10
    y#2#5#3   balanc@b            62
    y#2#5#4   BigM_40              1
    y#2#5#4   valid_4             10
    y#2#5#4   valid_3             62
    y#2#5#4   balan@10            10
    y#2#5#4   balanc@c            62
    y#3#1#1   BigM_41              1
    y#3#1#1   valid_5             34
    y#3#1#1   balan@15            34
    y#3#1#1   balan@11            38
    y#3#1#2   BigM_42              1
    y#3#1#2   valid_5             34
    y#3#1#2   balan@16            34
    y#3#1#2   balan@12            38
    y#3#1#3   BigM_43              1
    y#3#1#3   valid_5             34
    y#3#1#3   balan@17            34
    y#3#1#3   balan@13            38
    y#3#1#4   BigM_44              1
    y#3#1#4   valid_5             34
    y#3#1#4   balan@18            34
    y#3#1#4   balan@14            38
    y#3#2#1   BigM_45              1
    y#3#2#1   valid_5             24
    y#3#2#1   balan@15            24
    y#3#2#1   balan@11            48
    y#3#2#2   BigM_46              1
    y#3#2#2   valid_5             24
    y#3#2#2   balan@16            24
    y#3#2#2   balan@12            48
    y#3#2#3   BigM_47              1
    y#3#2#3   valid_5             24
    y#3#2#3   balan@17            24
    y#3#2#3   balan@13            48
    y#3#2#4   BigM_48              1
    y#3#2#4   valid_5             24
    y#3#2#4   balan@18            24
    y#3#2#4   balan@14            48
    y#3#3#1   BigM_49              1
    y#3#3#1   valid_5             19
    y#3#3#1   balan@15            19
    y#3#3#1   balan@11            53
    y#3#3#2   BigM_50              1
    y#3#3#2   valid_5             19
    y#3#3#2   balan@16            19
    y#3#3#2   balan@12            53
    y#3#3#3   BigM_51              1
    y#3#3#3   valid_5             19
    y#3#3#3   balan@17            19
    y#3#3#3   balan@13            53
    y#3#3#4   BigM_52              1
    y#3#3#4   valid_5             19
    y#3#3#4   balan@18            19
    y#3#3#4   balan@14            53
    y#3#4#1   BigM_53              1
    y#3#4#1   valid_5             47
    y#3#4#1   balan@15            47
    y#3#4#1   balan@11            25
    y#3#4#2   BigM_54              1
    y#3#4#2   valid_5             47
    y#3#4#2   balan@16            47
    y#3#4#2   balan@12            25
    y#3#4#3   BigM_55              1
    y#3#4#3   valid_5             47
    y#3#4#3   balan@17            47
    y#3#4#3   balan@13            25
    y#3#4#4   BigM_56              1
    y#3#4#4   valid_5             47
    y#3#4#4   balan@18            47
    y#3#4#4   balan@14            25
    y#3#5#1   BigM_57              1
    y#3#5#1   valid_5             10
    y#3#5#1   balan@15            10
    y#3#5#1   balan@11            62
    y#3#5#2   BigM_58              1
    y#3#5#2   valid_5             10
    y#3#5#2   balan@16            10
    y#3#5#2   balan@12            62
    y#3#5#3   BigM_59              1
    y#3#5#3   valid_5             10
    y#3#5#3   balan@17            10
    y#3#5#3   balan@13            62
    y#3#5#4   BigM_60              1
    y#3#5#4   valid_5             10
    y#3#5#4   balan@18            10
    y#3#5#4   balan@14            62
    y#4#1#1   BigM_61              1
    y#4#1#1   valid_7             34
    y#4#1#1   valid_6             38
    y#4#1#1   balan@1d            34
    y#4#1#1   balan@19            38
    y#4#1#2   BigM_62              1
    y#4#1#2   valid_7             34
    y#4#1#2   valid_6             38
    y#4#1#2   balan@1e            34
    y#4#1#2   balan@1a            38
    y#4#1#3   BigM_63              1
    y#4#1#3   valid_7             34
    y#4#1#3   valid_6             38
    y#4#1#3   balan@1f            34
    y#4#1#3   balan@1b            38
    y#4#1#4   BigM_64              1
    y#4#1#4   valid_7             34
    y#4#1#4   valid_6             38
    y#4#1#4   balan@20            34
    y#4#1#4   balan@1c            38
    y#4#2#1   BigM_65              1
    y#4#2#1   valid_7             24
    y#4#2#1   valid_6             48
    y#4#2#1   balan@1d            24
    y#4#2#1   balan@19            48
    y#4#2#2   BigM_66              1
    y#4#2#2   valid_7             24
    y#4#2#2   valid_6             48
    y#4#2#2   balan@1e            24
    y#4#2#2   balan@1a            48
    y#4#2#3   BigM_67              1
    y#4#2#3   valid_7             24
    y#4#2#3   valid_6             48
    y#4#2#3   balan@1f            24
    y#4#2#3   balan@1b            48
    y#4#2#4   BigM_68              1
    y#4#2#4   valid_7             24
    y#4#2#4   valid_6             48
    y#4#2#4   balan@20            24
    y#4#2#4   balan@1c            48
    y#4#3#1   BigM_69              1
    y#4#3#1   valid_7             19
    y#4#3#1   valid_6             53
    y#4#3#1   balan@1d            19
    y#4#3#1   balan@19            53
    y#4#3#2   BigM_70              1
    y#4#3#2   valid_7             19
    y#4#3#2   valid_6             53
    y#4#3#2   balan@1e            19
    y#4#3#2   balan@1a            53
    y#4#3#3   BigM_71              1
    y#4#3#3   valid_7             19
    y#4#3#3   valid_6             53
    y#4#3#3   balan@1f            19
    y#4#3#3   balan@1b            53
    y#4#3#4   BigM_72              1
    y#4#3#4   valid_7             19
    y#4#3#4   valid_6             53
    y#4#3#4   balan@20            19
    y#4#3#4   balan@1c            53
    y#4#4#1   BigM_73              1
    y#4#4#1   valid_7             47
    y#4#4#1   valid_6             25
    y#4#4#1   balan@1d            47
    y#4#4#1   balan@19            25
    y#4#4#2   BigM_74              1
    y#4#4#2   valid_7             47
    y#4#4#2   valid_6             25
    y#4#4#2   balan@1e            47
    y#4#4#2   balan@1a            25
    y#4#4#3   BigM_75              1
    y#4#4#3   valid_7             47
    y#4#4#3   valid_6             25
    y#4#4#3   balan@1f            47
    y#4#4#3   balan@1b            25
    y#4#4#4   BigM_76              1
    y#4#4#4   valid_7             47
    y#4#4#4   valid_6             25
    y#4#4#4   balan@20            47
    y#4#4#4   balan@1c            25
    y#4#5#1   BigM_77              1
    y#4#5#1   valid_7             10
    y#4#5#1   valid_6             62
    y#4#5#1   balan@1d            10
    y#4#5#1   balan@19            62
    y#4#5#2   BigM_78              1
    y#4#5#2   valid_7             10
    y#4#5#2   valid_6             62
    y#4#5#2   balan@1e            10
    y#4#5#2   balan@1a            62
    y#4#5#3   BigM_79              1
    y#4#5#3   valid_7             10
    y#4#5#3   valid_6             62
    y#4#5#3   balan@1f            10
    y#4#5#3   balan@1b            62
    y#4#5#4   BigM_80              1
    y#4#5#4   valid_7             10
    y#4#5#4   valid_6             62
    y#4#5#4   balan@20            10
    y#4#5#4   balan@1c            62
    y#5#1#1   BigM_81              1
    y#5#1#1   valid_8             38
    y#5#1#1   balan@25            34
    y#5#1#1   balan@21            38
    y#5#1#2   BigM_82              1
    y#5#1#2   valid_8             38
    y#5#1#2   balan@26            34
    y#5#1#2   balan@22            38
    y#5#1#3   BigM_83              1
    y#5#1#3   valid_8             38
    y#5#1#3   balan@27            34
    y#5#1#3   balan@23            38
    y#5#1#4   BigM_84              1
    y#5#1#4   valid_8             38
    y#5#1#4   balan@28            34
    y#5#1#4   balan@24            38
    y#5#2#1   BigM_85              1
    y#5#2#1   valid_8             48
    y#5#2#1   balan@25            24
    y#5#2#1   balan@21            48
    y#5#2#2   BigM_86              1
    y#5#2#2   valid_8             48
    y#5#2#2   balan@26            24
    y#5#2#2   balan@22            48
    y#5#2#3   BigM_87              1
    y#5#2#3   valid_8             48
    y#5#2#3   balan@27            24
    y#5#2#3   balan@23            48
    y#5#2#4   BigM_88              1
    y#5#2#4   valid_8             48
    y#5#2#4   balan@28            24
    y#5#2#4   balan@24            48
    y#5#3#1   BigM_89              1
    y#5#3#1   valid_8             53
    y#5#3#1   balan@25            19
    y#5#3#1   balan@21            53
    y#5#3#2   BigM_90              1
    y#5#3#2   valid_8             53
    y#5#3#2   balan@26            19
    y#5#3#2   balan@22            53
    y#5#3#3   BigM_91              1
    y#5#3#3   valid_8             53
    y#5#3#3   balan@27            19
    y#5#3#3   balan@23            53
    y#5#3#4   BigM_92              1
    y#5#3#4   valid_8             53
    y#5#3#4   balan@28            19
    y#5#3#4   balan@24            53
    y#5#4#1   BigM_93              1
    y#5#4#1   valid_8             25
    y#5#4#1   balan@25            47
    y#5#4#1   balan@21            25
    y#5#4#2   BigM_94              1
    y#5#4#2   valid_8             25
    y#5#4#2   balan@26            47
    y#5#4#2   balan@22            25
    y#5#4#3   BigM_95              1
    y#5#4#3   valid_8             25
    y#5#4#3   balan@27            47
    y#5#4#3   balan@23            25
    y#5#4#4   BigM_96              1
    y#5#4#4   valid_8             25
    y#5#4#4   balan@28            47
    y#5#4#4   balan@24            25
    y#5#5#1   BigM_97              1
    y#5#5#1   valid_8             62
    y#5#5#1   balan@25            10
    y#5#5#1   balan@21            62
    y#5#5#2   BigM_98              1
    y#5#5#2   valid_8             62
    y#5#5#2   balan@26            10
    y#5#5#2   balan@22            62
    y#5#5#3   BigM_99              1
    y#5#5#3   valid_8             62
    y#5#5#3   balan@27            10
    y#5#5#3   balan@23            62
    y#5#5#4   BigM_100             1
    y#5#5#4   valid_8             62
    y#5#5#4   balan@28            10
    y#5#5#4   balan@24            62
    z#1       BigM_84            -79
    z#1       BigM_83            -79
    z#1       BigM_82            -79
    z#1       BigM_81            -79
    z#1       BigM_64            -63
    z#1       BigM_63            -63
    z#1       BigM_62            -63
    z#1       BigM_61            -63
    z#1       BigM_44            -70
    z#1       BigM_43            -70
    z#1       BigM_42            -70
    z#1       BigM_41            -70
    z#1       BigM_24            -78
    z#1       BigM_23            -78
    z#1       BigM_22            -78
    z#1       BigM_21            -78
    z#1       BigM_4             -73
    z#1       BigM_3             -73
    z#1       BigM_2             -73
    z#1       BigM_1             -73
    z#1       select_1             1
    z#2       BigM_88            -62
    z#2       BigM_87            -62
    z#2       BigM_86            -62
    z#2       BigM_85            -62
    z#2       BigM_68            -89
    z#2       BigM_67            -89
    z#2       BigM_66            -89
    z#2       BigM_65            -89
    z#2       BigM_48            -98
    z#2       BigM_47            -98
    z#2       BigM_46            -98
    z#2       BigM_45            -98
    z#2       BigM_28            -67
    z#2       BigM_27            -67
    z#2       BigM_26            -67
    z#2       BigM_25            -67
    z#2       BigM_8            -103
    z#2       BigM_7            -103
    z#2       BigM_6            -103
    z#2       BigM_5            -103
    z#2       select_1             1
    z#3       BigM_92            -57
    z#3       BigM_91            -57
    z#3       BigM_90            -57
    z#3       BigM_89            -57
    z#3       BigM_72           -113
    z#3       BigM_71           -113
    z#3       BigM_70           -113
    z#3       BigM_69           -113
    z#3       BigM_52           -124
    z#3       BigM_51           -124
    z#3       BigM_50           -124
    z#3       BigM_49           -124
    z#3       BigM_32            -85
    z#3       BigM_31            -85
    z#3       BigM_30            -85
    z#3       BigM_29            -85
    z#3       BigM_12           -130
    z#3       BigM_11           -130
    z#3       BigM_10           -130
    z#3       BigM_9            -130
    z#3       select_1             1
    z#4       BigM_96           -119
    z#4       BigM_95           -119
    z#4       BigM_94           -119
    z#4       BigM_93           -119
    z#4       BigM_76            -64
    z#4       BigM_75            -64
    z#4       BigM_74            -64
    z#4       BigM_73            -64
    z#4       BigM_56            -50
    z#4       BigM_55            -50
    z#4       BigM_54            -50
    z#4       BigM_53            -50
    z#4       BigM_36           -118
    z#4       BigM_35           -118
    z#4       BigM_34           -118
    z#4       BigM_33           -118
    z#4       BigM_16            -96
    z#4       BigM_15            -96
    z#4       BigM_14            -96
    z#4       BigM_13            -96
    z#4       select_1             1
    z#5       BigM_100           -48
    z#5       BigM_99            -48
    z#5       BigM_98            -48
    z#5       BigM_97            -48
    z#5       BigM_80           -214
    z#5       BigM_79           -214
    z#5       BigM_78           -214
    z#5       BigM_77           -214
    z#5       BigM_60           -235
    z#5       BigM_59           -235
    z#5       BigM_58           -235
    z#5       BigM_57           -235
    z#5       BigM_40           -160
    z#5       BigM_39           -160
    z#5       BigM_38           -160
    z#5       BigM_37           -160
    z#5       BigM_20           -247
    z#5       BigM_19           -247
    z#5       BigM_18           -247
    z#5       BigM_17           -247
    z#5       select_1             1
    MARK0001  'MARKER'                 'INTEND'
    r#1#1#0   init2_1              1
    r#1#1#0   balanc@1            -1
    r#1#1#1   OBJECTIV             5
    r#1#1#1   balanc@2            -1
    r#1#1#1   balanc@1             1
    r#1#1#2   OBJECTIV             5
    r#1#1#2   balanc@3            -1
    r#1#1#2   balanc@2             1
    r#1#1#3   OBJECTIV             5
    r#1#1#3   balanc@4            -1
    r#1#1#3   balanc@3             1
    r#1#1#4   OBJECTIV             5
    r#1#1#4   init3_1              1
    r#1#1#4   balanc@4             1
    r#1#2#0   init2_2              1
    r#1#2#0   balanc@5            -1
    r#1#2#1   OBJECTIV             6
    r#1#2#1   balanc@6            -1
    r#1#2#1   balanc@5             1
    r#1#2#2   OBJECTIV             6
    r#1#2#2   balanc@7            -1
    r#1#2#2   balanc@6             1
    r#1#2#3   OBJECTIV             6
    r#1#2#3   balanc@8            -1
    r#1#2#3   balanc@7             1
    r#1#2#4   OBJECTIV             6
    r#1#2#4   init3_2              1
    r#1#2#4   balanc@8             1
    r#2#1#0   init2_3              1
    r#2#1#0   balanc@9            -1
    r#2#1#1   OBJECTIV             5
    r#2#1#1   balanc@a            -1
    r#2#1#1   balanc@9             1
    r#2#1#2   OBJECTIV             5
    r#2#1#2   balanc@b            -1
    r#2#1#2   balanc@a             1
    r#2#1#3   OBJECTIV             5
    r#2#1#3   balanc@c            -1
    r#2#1#3   balanc@b             1
    r#2#1#4   OBJECTIV             5
    r#2#1#4   init3_3              1
    r#2#1#4   balanc@c             1
    r#2#2#0   init2_4              1
    r#2#2#0   balanc@d            -1
    r#2#2#1   OBJECTIV             6
    r#2#2#1   balanc@e            -1
    r#2#2#1   balanc@d             1
    r#2#2#2   OBJECTIV             6
    r#2#2#2   balanc@f            -1
    r#2#2#2   balanc@e             1
    r#2#2#3   OBJECTIV             6
    r#2#2#3   balan@10            -1
    r#2#2#3   balanc@f             1
    r#2#2#4   OBJECTIV             6
    r#2#2#4   init3_4              1
    r#2#2#4   balan@10             1
    r#3#1#0   init2_5              1
    r#3#1#0   balan@11            -1
    r#3#1#1   OBJECTIV             5
    r#3#1#1   balan@12            -1
    r#3#1#1   balan@11             1
    r#3#1#2   OBJECTIV             5
    r#3#1#2   balan@13            -1
    r#3#1#2   balan@12             1
    r#3#1#3   OBJECTIV             5
    r#3#1#3   balan@14            -1
    r#3#1#3   balan@13             1
    r#3#1#4   OBJECTIV             5
    r#3#1#4   init3_5              1
    r#3#1#4   balan@14             1
    r#3#2#0   init2_6              1
    r#3#2#0   balan@15            -1
    r#3#2#1   OBJECTIV             6
    r#3#2#1   balan@16            -1
    r#3#2#1   balan@15             1
    r#3#2#2   OBJECTIV             6
    r#3#2#2   balan@17            -1
    r#3#2#2   balan@16             1
    r#3#2#3   OBJECTIV             6
    r#3#2#3   balan@18            -1
    r#3#2#3   balan@17             1
    r#3#2#4   OBJECTIV             6
    r#3#2#4   init3_6              1
    r#3#2#4   balan@18             1
    r#4#1#0   init2_7              1
    r#4#1#0   balan@19            -1
    r#4#1#1   OBJECTIV             5
    r#4#1#1   balan@1a            -1
    r#4#1#1   balan@19             1
    r#4#1#2   OBJECTIV             5
    r#4#1#2   balan@1b            -1
    r#4#1#2   balan@1a             1
    r#4#1#3   OBJECTIV             5
    r#4#1#3   balan@1c            -1
    r#4#1#3   balan@1b             1
    r#4#1#4   OBJECTIV             5
    r#4#1#4   init3_7              1
    r#4#1#4   balan@1c             1
    r#4#2#0   init2_8              1
    r#4#2#0   balan@1d            -1
    r#4#2#1   OBJECTIV             6
    r#4#2#1   balan@1e            -1
    r#4#2#1   balan@1d             1
    r#4#2#2   OBJECTIV             6
    r#4#2#2   balan@1f            -1
    r#4#2#2   balan@1e             1
    r#4#2#3   OBJECTIV             6
    r#4#2#3   balan@20            -1
    r#4#2#3   balan@1f             1
    r#4#2#4   OBJECTIV             6
    r#4#2#4   init3_8              1
    r#4#2#4   balan@20             1
    r#5#1#0   init2_9              1
    r#5#1#0   balan@21            -1
    r#5#1#1   OBJECTIV             5
    r#5#1#1   balan@22            -1
    r#5#1#1   balan@21             1
    r#5#1#2   OBJECTIV             5
    r#5#1#2   balan@23            -1
    r#5#1#2   balan@22             1
    r#5#1#3   OBJECTIV             5
    r#5#1#3   balan@24            -1
    r#5#1#3   balan@23             1
    r#5#1#4   OBJECTIV             5
    r#5#1#4   init3_9              1
    r#5#1#4   balan@24             1
    r#5#2#0   init2_10             1
    r#5#2#0   balan@25            -1
    r#5#2#1   OBJECTIV             6
    r#5#2#1   balan@26            -1
    r#5#2#1   balan@25             1
    r#5#2#2   OBJECTIV             6
    r#5#2#2   balan@27            -1
    r#5#2#2   balan@26             1
    r#5#2#3   OBJECTIV             6
    r#5#2#3   balan@28            -1
    r#5#2#3   balan@27             1
    r#5#2#4   OBJECTIV             6
    r#5#2#4   init3_10             1
    r#5#2#4   balan@28             1
    s#1#1#0   init1_1              1
    s#1#1#0   balanc@1             1
    s#1#1#1   OBJECTIV             1
    s#1#1#1   balanc@2             1
    s#1#1#1   balanc@1            -1
    s#1#1#2   OBJECTIV             1
    s#1#1#2   balanc@3             1
    s#1#1#2   balanc@2            -1
    s#1#1#3   OBJECTIV             1
    s#1#1#3   balanc@4             1
    s#1#1#3   balanc@3            -1
    s#1#1#4   OBJECTIV             1
    s#1#1#4   balanc@4            -1
    s#1#2#0   init1_2              1
    s#1#2#0   balanc@5             1
    s#1#2#1   OBJECTIV           1.2
    s#1#2#1   balanc@6             1
    s#1#2#1   balanc@5            -1
    s#1#2#2   OBJECTIV           1.2
    s#1#2#2   balanc@7             1
    s#1#2#2   balanc@6            -1
    s#1#2#3   OBJECTIV           1.2
    s#1#2#3   balanc@8             1
    s#1#2#3   balanc@7            -1
    s#1#2#4   OBJECTIV           1.2
    s#1#2#4   balanc@8            -1
    s#2#1#0   init1_3              1
    s#2#1#0   balanc@9             1
    s#2#1#1   OBJECTIV             1
    s#2#1#1   balanc@a             1
    s#2#1#1   balanc@9            -1
    s#2#1#2   OBJECTIV             1
    s#2#1#2   balanc@b             1
    s#2#1#2   balanc@a            -1
    s#2#1#3   OBJECTIV             1
    s#2#1#3   balanc@c             1
    s#2#1#3   balanc@b            -1
    s#2#1#4   OBJECTIV             1
    s#2#1#4   balanc@c            -1
    s#2#2#0   init1_4              1
    s#2#2#0   balanc@d             1
    s#2#2#1   OBJECTIV           1.2
    s#2#2#1   balanc@e             1
    s#2#2#1   balanc@d            -1
    s#2#2#2   OBJECTIV           1.2
    s#2#2#2   balanc@f             1
    s#2#2#2   balanc@e            -1
    s#2#2#3   OBJECTIV           1.2
    s#2#2#3   balan@10             1
    s#2#2#3   balanc@f            -1
    s#2#2#4   OBJECTIV           1.2
    s#2#2#4   balan@10            -1
    s#3#1#0   init1_5              1
    s#3#1#0   balan@11             1
    s#3#1#1   OBJECTIV             1
    s#3#1#1   balan@12             1
    s#3#1#1   balan@11            -1
    s#3#1#2   OBJECTIV             1
    s#3#1#2   balan@13             1
    s#3#1#2   balan@12            -1
    s#3#1#3   OBJECTIV             1
    s#3#1#3   balan@14             1
    s#3#1#3   balan@13            -1
    s#3#1#4   OBJECTIV             1
    s#3#1#4   balan@14            -1
    s#3#2#0   init1_6              1
    s#3#2#0   balan@15             1
    s#3#2#1   OBJECTIV           1.2
    s#3#2#1   balan@16             1
    s#3#2#1   balan@15            -1
    s#3#2#2   OBJECTIV           1.2
    s#3#2#2   balan@17             1
    s#3#2#2   balan@16            -1
    s#3#2#3   OBJECTIV           1.2
    s#3#2#3   balan@18             1
    s#3#2#3   balan@17            -1
    s#3#2#4   OBJECTIV           1.2
    s#3#2#4   balan@18            -1
    s#4#1#0   init1_7              1
    s#4#1#0   balan@19             1
    s#4#1#1   OBJECTIV             1
    s#4#1#1   balan@1a             1
    s#4#1#1   balan@19            -1
    s#4#1#2   OBJECTIV             1
    s#4#1#2   balan@1b             1
    s#4#1#2   balan@1a            -1
    s#4#1#3   OBJECTIV             1
    s#4#1#3   balan@1c             1
    s#4#1#3   balan@1b            -1
    s#4#1#4   OBJECTIV             1
    s#4#1#4   balan@1c            -1
    s#4#2#0   init1_8              1
    s#4#2#0   balan@1d             1
    s#4#2#1   OBJECTIV           1.2
    s#4#2#1   balan@1e             1
    s#4#2#1   balan@1d            -1
    s#4#2#2   OBJECTIV           1.2
    s#4#2#2   balan@1f             1
    s#4#2#2   balan@1e            -1
    s#4#2#3   OBJECTIV           1.2
    s#4#2#3   balan@20             1
    s#4#2#3   balan@1f            -1
    s#4#2#4   OBJECTIV           1.2
    s#4#2#4   balan@20            -1
    s#5#1#0   init1_9              1
    s#5#1#0   balan@21             1
    s#5#1#1   OBJECTIV             1
    s#5#1#1   balan@22             1
    s#5#1#1   balan@21            -1
    s#5#1#2   OBJECTIV             1
    s#5#1#2   balan@23             1
    s#5#1#2   balan@22            -1
    s#5#1#3   OBJECTIV             1
    s#5#1#3   balan@24             1
    s#5#1#3   balan@23            -1
    s#5#1#4   OBJECTIV             1
    s#5#1#4   balan@24            -1
    s#5#2#0   init1_10             1
    s#5#2#0   balan@25             1
    s#5#2#1   OBJECTIV           1.2
    s#5#2#1   balan@26             1
    s#5#2#1   balan@25            -1
    s#5#2#2   OBJECTIV           1.2
    s#5#2#2   balan@27             1
    s#5#2#2   balan@26            -1
    s#5#2#3   OBJECTIV           1.2
    s#5#2#3   balan@28             1
    s#5#2#3   balan@27            -1
    s#5#2#4   OBJECTIV           1.2
    s#5#2#4   balan@28            -1
RHS
    RHS       select_1             1
    RHS       balanc@1           940
    RHS       balanc@2           714
    RHS       balanc@3           630
    RHS       balanc@4            96
    RHS       balanc@5           951
    RHS       balanc@6           779
    RHS       balanc@7           384
    RHS       balanc@8           347
    RHS       balanc@9           897
    RHS       balanc@a           863
    RHS       balanc@b           911
    RHS       balanc@c           260
    RHS       balanc@d            51
    RHS       balanc@e           600
    RHS       balanc@f           244
    RHS       balan@10           702
    RHS       balan@15           598
    RHS       balan@16           201
    RHS       balan@17           618
    RHS       balan@18           931
    RHS       balan@19            71
    RHS       balan@1a           768
    RHS       balan@1b           574
    RHS       balan@1c           184
    RHS       balan@1d            43
    RHS       balan@1e           538
    RHS       balan@1f           695
    RHS       balan@20           855
    RHS       balan@21           972
    RHS       balan@22           540
    RHS       balan@23           804
    RHS       balan@24           659
    RHS       valid_1           2380
    RHS       valid_2           2461
    RHS       valid_3           2931
    RHS       valid_4           1597
    RHS       valid_5           2348
    RHS       valid_6           1597
    RHS       valid_7           2131
    RHS       valid_8           2975
BOUNDS
 LO BOUND     r#1#1#0              0
 PL BOUND     r#1#1#0 
 LO BOUND     r#1#1#1              0
 PL BOUND     r#1#1#1 
 LO BOUND     r#1#1#2              0
 PL BOUND     r#1#1#2 
 LO BOUND     r#1#1#3              0
 PL BOUND     r#1#1#3 
 LO BOUND     r#1#1#4              0
 PL BOUND     r#1#1#4 
 LO BOUND     r#1#2#0              0
 PL BOUND     r#1#2#0 
 LO BOUND     r#1#2#1              0
 PL BOUND     r#1#2#1 
 LO BOUND     r#1#2#2              0
 PL BOUND     r#1#2#2 
 LO BOUND     r#1#2#3              0
 PL BOUND     r#1#2#3 
 LO BOUND     r#1#2#4              0
 PL BOUND     r#1#2#4 
 LO BOUND     r#2#1#0              0
 PL BOUND     r#2#1#0 
 LO BOUND     r#2#1#1              0
 PL BOUND     r#2#1#1 
 LO BOUND     r#2#1#2              0
 PL BOUND     r#2#1#2 
 LO BOUND     r#2#1#3              0
 PL BOUND     r#2#1#3 
 LO BOUND     r#2#1#4              0
 PL BOUND     r#2#1#4 
 LO BOUND     r#2#2#0              0
 PL BOUND     r#2#2#0 
 LO BOUND     r#2#2#1              0
 PL BOUND     r#2#2#1 
 LO BOUND     r#2#2#2              0
 PL BOUND     r#2#2#2 
 LO BOUND     r#2#2#3              0
 PL BOUND     r#2#2#3 
 LO BOUND     r#2#2#4              0
 PL BOUND     r#2#2#4 
 LO BOUND     r#3#1#0              0
 PL BOUND     r#3#1#0 
 LO BOUND     r#3#1#1              0
 PL BOUND     r#3#1#1 
 LO BOUND     r#3#1#2              0
 PL BOUND     r#3#1#2 
 LO BOUND     r#3#1#3              0
 PL BOUND     r#3#1#3 
 LO BOUND     r#3#1#4              0
 PL BOUND     r#3#1#4 
 LO BOUND     r#3#2#0              0
 PL BOUND     r#3#2#0 
 LO BOUND     r#3#2#1              0
 PL BOUND     r#3#2#1 
 LO BOUND     r#3#2#2              0
 PL BOUND     r#3#2#2 
 LO BOUND     r#3#2#3              0
 PL BOUND     r#3#2#3 
 LO BOUND     r#3#2#4              0
 PL BOUND     r#3#2#4 
 LO BOUND     r#4#1#0              0
 PL BOUND     r#4#1#0 
 LO BOUND     r#4#1#1              0
 PL BOUND     r#4#1#1 
 LO BOUND     r#4#1#2              0
 PL BOUND     r#4#1#2 
 LO BOUND     r#4#1#3              0
 PL BOUND     r#4#1#3 
 LO BOUND     r#4#1#4              0
 PL BOUND     r#4#1#4 
 LO BOUND     r#4#2#0              0
 PL BOUND     r#4#2#0 
 LO BOUND     r#4#2#1              0
 PL BOUND     r#4#2#1 
 LO BOUND     r#4#2#2              0
 PL BOUND     r#4#2#2 
 LO BOUND     r#4#2#3              0
 PL BOUND     r#4#2#3 
 LO BOUND     r#4#2#4              0
 PL BOUND     r#4#2#4 
 LO BOUND     r#5#1#0              0
 PL BOUND     r#5#1#0 
 LO BOUND     r#5#1#1              0
 PL BOUND     r#5#1#1 
 LO BOUND     r#5#1#2              0
 PL BOUND     r#5#1#2 
 LO BOUND     r#5#1#3              0
 PL BOUND     r#5#1#3 
 LO BOUND     r#5#1#4              0
 PL BOUND     r#5#1#4 
 LO BOUND     r#5#2#0              0
 PL BOUND     r#5#2#0 
 LO BOUND     r#5#2#1              0
 PL BOUND     r#5#2#1 
 LO BOUND     r#5#2#2              0
 PL BOUND     r#5#2#2 
 LO BOUND     r#5#2#3              0
 PL BOUND     r#5#2#3 
 LO BOUND     r#5#2#4              0
 PL BOUND     r#5#2#4 
 LO BOUND     s#1#1#0              0
 PL BOUND     s#1#1#0 
 LO BOUND     s#1#1#1              0
 PL BOUND     s#1#1#1 
 LO BOUND     s#1#1#2              0
 PL BOUND     s#1#1#2 
 LO BOUND     s#1#1#3              0
 PL BOUND     s#1#1#3 
 LO BOUND     s#1#1#4              0
 PL BOUND     s#1#1#4 
 LO BOUND     s#1#2#0              0
 PL BOUND     s#1#2#0 
 LO BOUND     s#1#2#1              0
 PL BOUND     s#1#2#1 
 LO BOUND     s#1#2#2              0
 PL BOUND     s#1#2#2 
 LO BOUND     s#1#2#3              0
 PL BOUND     s#1#2#3 
 LO BOUND     s#1#2#4              0
 PL BOUND     s#1#2#4 
 LO BOUND     s#2#1#0              0
 PL BOUND     s#2#1#0 
 LO BOUND     s#2#1#1              0
 PL BOUND     s#2#1#1 
 LO BOUND     s#2#1#2              0
 PL BOUND     s#2#1#2 
 LO BOUND     s#2#1#3              0
 PL BOUND     s#2#1#3 
 LO BOUND     s#2#1#4              0
 PL BOUND     s#2#1#4 
 LO BOUND     s#2#2#0              0
 PL BOUND     s#2#2#0 
 LO BOUND     s#2#2#1              0
 PL BOUND     s#2#2#1 
 LO BOUND     s#2#2#2              0
 PL BOUND     s#2#2#2 
 LO BOUND     s#2#2#3              0
 PL BOUND     s#2#2#3 
 LO BOUND     s#2#2#4              0
 PL BOUND     s#2#2#4 
 LO BOUND     s#3#1#0              0
 PL BOUND     s#3#1#0 
 LO BOUND     s#3#1#1              0
 PL BOUND     s#3#1#1 
 LO BOUND     s#3#1#2              0
 PL BOUND     s#3#1#2 
 LO BOUND     s#3#1#3              0
 PL BOUND     s#3#1#3 
 LO BOUND     s#3#1#4              0
 PL BOUND     s#3#1#4 
 LO BOUND     s#3#2#0              0
 PL BOUND     s#3#2#0 
 LO BOUND     s#3#2#1              0
 PL BOUND     s#3#2#1 
 LO BOUND     s#3#2#2              0
 PL BOUND     s#3#2#2 
 LO BOUND     s#3#2#3              0
 PL BOUND     s#3#2#3 
 LO BOUND     s#3#2#4              0
 PL BOUND     s#3#2#4 
 LO BOUND     s#4#1#0              0
 PL BOUND     s#4#1#0 
 LO BOUND     s#4#1#1              0
 PL BOUND     s#4#1#1 
 LO BOUND     s#4#1#2              0
 PL BOUND     s#4#1#2 
 LO BOUND     s#4#1#3              0
 PL BOUND     s#4#1#3 
 LO BOUND     s#4#1#4              0
 PL BOUND     s#4#1#4 
 LO BOUND     s#4#2#0              0
 PL BOUND     s#4#2#0 
 LO BOUND     s#4#2#1              0
 PL BOUND     s#4#2#1 
 LO BOUND     s#4#2#2              0
 PL BOUND     s#4#2#2 
 LO BOUND     s#4#2#3              0
 PL BOUND     s#4#2#3 
 LO BOUND     s#4#2#4              0
 PL BOUND     s#4#2#4 
 LO BOUND     s#5#1#0              0
 PL BOUND     s#5#1#0 
 LO BOUND     s#5#1#1              0
 PL BOUND     s#5#1#1 
 LO BOUND     s#5#1#2              0
 PL BOUND     s#5#1#2 
 LO BOUND     s#5#1#3              0
 PL BOUND     s#5#1#3 
 LO BOUND     s#5#1#4              0
 PL BOUND     s#5#1#4 
 LO BOUND     s#5#2#0              0
 PL BOUND     s#5#2#0 
 LO BOUND     s#5#2#1              0
 PL BOUND     s#5#2#1 
 LO BOUND     s#5#2#2              0
 PL BOUND     s#5#2#2 
 LO BOUND     s#5#2#3              0
 PL BOUND     s#5#2#3 
 LO BOUND     s#5#2#4              0
 PL BOUND     s#5#2#4 
 LO BOUND     x#1#1#1              0
 PL BOUND     x#1#1#1 
 LO BOUND     x#1#1#2              0
 PL BOUND     x#1#1#2 
 LO BOUND     x#1#1#3              0
 PL BOUND     x#1#1#3 
 LO BOUND     x#1#1#4              0
 PL BOUND     x#1#1#4 
 LO BOUND     x#1#2#1              0
 PL BOUND     x#1#2#1 
 LO BOUND     x#1#2#2              0
 PL BOUND     x#1#2#2 
 LO BOUND     x#1#2#3              0
 PL BOUND     x#1#2#3 
 LO BOUND     x#1#2#4              0
 PL BOUND     x#1#2#4 
 LO BOUND     x#2#1#1              0
 PL BOUND     x#2#1#1 
 LO BOUND     x#2#1#2              0
 PL BOUND     x#2#1#2 
 LO BOUND     x#2#1#3              0
 PL BOUND     x#2#1#3 
 LO BOUND     x#2#1#4              0
 PL BOUND     x#2#1#4 
 LO BOUND     x#2#2#1              0
 PL BOUND     x#2#2#1 
 LO BOUND     x#2#2#2              0
 PL BOUND     x#2#2#2 
 LO BOUND     x#2#2#3              0
 PL BOUND     x#2#2#3 
 LO BOUND     x#2#2#4              0
 PL BOUND     x#2#2#4 
 LO BOUND     x#3#1#1              0
 PL BOUND     x#3#1#1 
 LO BOUND     x#3#1#2              0
 PL BOUND     x#3#1#2 
 LO BOUND     x#3#1#3              0
 PL BOUND     x#3#1#3 
 LO BOUND     x#3#1#4              0
 PL BOUND     x#3#1#4 
 LO BOUND     x#3#2#1              0
 PL BOUND     x#3#2#1 
 LO BOUND     x#3#2#2              0
 PL BOUND     x#3#2#2 
 LO BOUND     x#3#2#3              0
 PL BOUND     x#3#2#3 
 LO BOUND     x#3#2#4              0
 PL BOUND     x#3#2#4 
 LO BOUND     x#4#1#1              0
 PL BOUND     x#4#1#1 
 LO BOUND     x#4#1#2              0
 PL BOUND     x#4#1#2 
 LO BOUND     x#4#1#3              0
 PL BOUND     x#4#1#3 
 LO BOUND     x#4#1#4              0
 PL BOUND     x#4#1#4 
 LO BOUND     x#4#2#1              0
 PL BOUND     x#4#2#1 
 LO BOUND     x#4#2#2              0
 PL BOUND     x#4#2#2 
 LO BOUND     x#4#2#3              0
 PL BOUND     x#4#2#3 
 LO BOUND     x#4#2#4              0
 PL BOUND     x#4#2#4 
 LO BOUND     x#5#1#1              0
 PL BOUND     x#5#1#1 
 LO BOUND     x#5#1#2              0
 PL BOUND     x#5#1#2 
 LO BOUND     x#5#1#3              0
 PL BOUND     x#5#1#3 
 LO BOUND     x#5#1#4              0
 PL BOUND     x#5#1#4 
 LO BOUND     x#5#2#1              0
 PL BOUND     x#5#2#1 
 LO BOUND     x#5#2#2              0
 PL BOUND     x#5#2#2 
 LO BOUND     x#5#2#3              0
 PL BOUND     x#5#2#3 
 LO BOUND     x#5#2#4              0
 PL BOUND     x#5#2#4 
 LO BOUND     y#1#1#1              0
 PL BOUND     y#1#1#1 
 LO BOUND     y#1#1#2              0
 PL BOUND     y#1#1#2 
 LO BOUND     y#1#1#3              0
 PL BOUND     y#1#1#3 
 LO BOUND     y#1#1#4              0
 PL BOUND     y#1#1#4 
 LO BOUND     y#1#2#1              0
 PL BOUND     y#1#2#1 
 LO BOUND     y#1#2#2              0
 PL BOUND     y#1#2#2 
 LO BOUND     y#1#2#3              0
 PL BOUND     y#1#2#3 
 LO BOUND     y#1#2#4              0
 PL BOUND     y#1#2#4 
 LO BOUND     y#1#3#1              0
 PL BOUND     y#1#3#1 
 LO BOUND     y#1#3#2              0
 PL BOUND     y#1#3#2 
 LO BOUND     y#1#3#3              0
 PL BOUND     y#1#3#3 
 LO BOUND     y#1#3#4              0
 PL BOUND     y#1#3#4 
 LO BOUND     y#1#4#1              0
 PL BOUND     y#1#4#1 
 LO BOUND     y#1#4#2              0
 PL BOUND     y#1#4#2 
 LO BOUND     y#1#4#3              0
 PL BOUND     y#1#4#3 
 LO BOUND     y#1#4#4              0
 PL BOUND     y#1#4#4 
 LO BOUND     y#1#5#1              0
 PL BOUND     y#1#5#1 
 LO BOUND     y#1#5#2              0
 PL BOUND     y#1#5#2 
 LO BOUND     y#1#5#3              0
 PL BOUND     y#1#5#3 
 LO BOUND     y#1#5#4              0
 PL BOUND     y#1#5#4 
 LO BOUND     y#2#1#1              0
 PL BOUND     y#2#1#1 
 LO BOUND     y#2#1#2              0
 PL BOUND     y#2#1#2 
 LO BOUND     y#2#1#3              0
 PL BOUND     y#2#1#3 
 LO BOUND     y#2#1#4              0
 PL BOUND     y#2#1#4 
 LO BOUND     y#2#2#1              0
 PL BOUND     y#2#2#1 
 LO BOUND     y#2#2#2              0
 PL BOUND     y#2#2#2 
 LO BOUND     y#2#2#3              0
 PL BOUND     y#2#2#3 
 LO BOUND     y#2#2#4              0
 PL BOUND     y#2#2#4 
 LO BOUND     y#2#3#1              0
 PL BOUND     y#2#3#1 
 LO BOUND     y#2#3#2              0
 PL BOUND     y#2#3#2 
 LO BOUND     y#2#3#3              0
 PL BOUND     y#2#3#3 
 LO BOUND     y#2#3#4              0
 PL BOUND     y#2#3#4 
 LO BOUND     y#2#4#1              0
 PL BOUND     y#2#4#1 
 LO BOUND     y#2#4#2              0
 PL BOUND     y#2#4#2 
 LO BOUND     y#2#4#3              0
 PL BOUND     y#2#4#3 
 LO BOUND     y#2#4#4              0
 PL BOUND     y#2#4#4 
 LO BOUND     y#2#5#1              0
 PL BOUND     y#2#5#1 
 LO BOUND     y#2#5#2              0
 PL BOUND     y#2#5#2 
 LO BOUND     y#2#5#3              0
 PL BOUND     y#2#5#3 
 LO BOUND     y#2#5#4              0
 PL BOUND     y#2#5#4 
 LO BOUND     y#3#1#1              0
 PL BOUND     y#3#1#1 
 LO BOUND     y#3#1#2              0
 PL BOUND     y#3#1#2 
 LO BOUND     y#3#1#3              0
 PL BOUND     y#3#1#3 
 LO BOUND     y#3#1#4              0
 PL BOUND     y#3#1#4 
 LO BOUND     y#3#2#1              0
 PL BOUND     y#3#2#1 
 LO BOUND     y#3#2#2              0
 PL BOUND     y#3#2#2 
 LO BOUND     y#3#2#3              0
 PL BOUND     y#3#2#3 
 LO BOUND     y#3#2#4              0
 PL BOUND     y#3#2#4 
 LO BOUND     y#3#3#1              0
 PL BOUND     y#3#3#1 
 LO BOUND     y#3#3#2              0
 PL BOUND     y#3#3#2 
 LO BOUND     y#3#3#3              0
 PL BOUND     y#3#3#3 
 LO BOUND     y#3#3#4              0
 PL BOUND     y#3#3#4 
 LO BOUND     y#3#4#1              0
 PL BOUND     y#3#4#1 
 LO BOUND     y#3#4#2              0
 PL BOUND     y#3#4#2 
 LO BOUND     y#3#4#3              0
 PL BOUND     y#3#4#3 
 LO BOUND     y#3#4#4              0
 PL BOUND     y#3#4#4 
 LO BOUND     y#3#5#1              0
 PL BOUND     y#3#5#1 
 LO BOUND     y#3#5#2              0
 PL BOUND     y#3#5#2 
 LO BOUND     y#3#5#3              0
 PL BOUND     y#3#5#3 
 LO BOUND     y#3#5#4              0
 PL BOUND     y#3#5#4 
 LO BOUND     y#4#1#1              0
 PL BOUND     y#4#1#1 
 LO BOUND     y#4#1#2              0
 PL BOUND     y#4#1#2 
 LO BOUND     y#4#1#3              0
 PL BOUND     y#4#1#3 
 LO BOUND     y#4#1#4              0
 PL BOUND     y#4#1#4 
 LO BOUND     y#4#2#1              0
 PL BOUND     y#4#2#1 
 LO BOUND     y#4#2#2              0
 PL BOUND     y#4#2#2 
 LO BOUND     y#4#2#3              0
 PL BOUND     y#4#2#3 
 LO BOUND     y#4#2#4              0
 PL BOUND     y#4#2#4 
 LO BOUND     y#4#3#1              0
 PL BOUND     y#4#3#1 
 LO BOUND     y#4#3#2              0
 PL BOUND     y#4#3#2 
 LO BOUND     y#4#3#3              0
 PL BOUND     y#4#3#3 
 LO BOUND     y#4#3#4              0
 PL BOUND     y#4#3#4 
 LO BOUND     y#4#4#1              0
 PL BOUND     y#4#4#1 
 LO BOUND     y#4#4#2              0
 PL BOUND     y#4#4#2 
 LO BOUND     y#4#4#3              0
 PL BOUND     y#4#4#3 
 LO BOUND     y#4#4#4              0
 PL BOUND     y#4#4#4 
 LO BOUND     y#4#5#1              0
 PL BOUND     y#4#5#1 
 LO BOUND     y#4#5#2              0
 PL BOUND     y#4#5#2 
 LO BOUND     y#4#5#3              0
 PL BOUND     y#4#5#3 
 LO BOUND     y#4#5#4              0
 PL BOUND     y#4#5#4 
 LO BOUND     y#5#1#1              0
 PL BOUND     y#5#1#1 
 LO BOUND     y#5#1#2              0
 PL BOUND     y#5#1#2 
 LO BOUND     y#5#1#3              0
 PL BOUND     y#5#1#3 
 LO BOUND     y#5#1#4              0
 PL BOUND     y#5#1#4 
 LO BOUND     y#5#2#1              0
 PL BOUND     y#5#2#1 
 LO BOUND     y#5#2#2              0
 PL BOUND     y#5#2#2 
 LO BOUND     y#5#2#3              0
 PL BOUND     y#5#2#3 
 LO BOUND     y#5#2#4              0
 PL BOUND     y#5#2#4 
 LO BOUND     y#5#3#1              0
 PL BOUND     y#5#3#1 
 LO BOUND     y#5#3#2              0
 PL BOUND     y#5#3#2 
 LO BOUND     y#5#3#3              0
 PL BOUND     y#5#3#3 
 LO BOUND     y#5#3#4              0
 PL BOUND     y#5#3#4 
 LO BOUND     y#5#4#1              0
 PL BOUND     y#5#4#1 
 LO BOUND     y#5#4#2              0
 PL BOUND     y#5#4#2 
 LO BOUND     y#5#4#3              0
 PL BOUND     y#5#4#3 
 LO BOUND     y#5#4#4              0
 PL BOUND     y#5#4#4 
 LO BOUND     y#5#5#1              0
 PL BOUND     y#5#5#1 
 LO BOUND     y#5#5#2              0
 PL BOUND     y#5#5#2 
 LO BOUND     y#5#5#3              0
 PL BOUND     y#5#5#3 
 LO BOUND     y#5#5#4              0
 PL BOUND     y#5#5#4 
 LO BOUND     z#1                  0
 UP BOUND     z#1                  1
 LO BOUND     z#2                  0
 UP BOUND     z#2                  1
 LO BOUND     z#3                  0
 UP BOUND     z#3                  1
 LO BOUND     z#4                  0
 UP BOUND     z#4                  1
 LO BOUND     z#5                  0
 UP BOUND     z#5                  1
ENDATA
