* This file was automatically generated by Zimpl
* param Q2 := 1;
* do print file2;
* param nC := read file1 as "1n" use 1;
* param nI := read file1 as "2n" use 1;
* param m  := read file1 as "3n" use 1;
* param nT := read file1 as "4n" use 1;
* param nP := read file2 as "1n" use 1;
* set C := { 1 .. nC };
* set I := { 1 .. nI };
* set T0 := { 0 .. nT };
* set T := { 1 .. nT };
* set P := { 1 .. nP };
* param inveCost[I] := read file1 as "<1n> 2n" skip 1 use nI;
* param backCost[I] := read file1 as "<1n> 2n" skip nI+1 use nI;
* param demand[C*I*T] := read file1 as "<1n,2n,3n> 4n" skip 2*nI+1;
* param q[P*I] := read file2 as "<1n,2n> 3n" skip 1;
* param D[<c,i> in C*I] := ceil( sum <t> in T : demand[c,i,t]/Q2 );
* set Pc[<c> in C] := inter <i> in { <i> in I with ( sum <t> in T : demand[c,i,t] ) > 0 } : { <p> in P with q[p,i] > 0 };
* param M[<c,p> in C*P] := max <i> in I with q[p,i] > 0: ceil( sum <t> in T : demand[c,i,t]/Q2/q[p,i] );
* var r[C*I*T0] >= 0;
* var s[C*I*T0] >= 0;
* var x[C*I*T] integer >= 0;
* var y[C*P*T] integer >= 0;
* var z[P] binary;
* minimize cost: sum <i> in I: ( sum <t> in T: (sum <c> in C : (inveCost[i] * s[c,i,t]  + backCost[i] * r[c,i,t]) ));
* subto select:       sum <p> in P: z[p] <= m;
* subto balance:    forall <c,i,t> in C*I*T with t>=1 do       s[c,i,t-1] - r[c,i,t-1] + Q1*Q2*x[c,i,t] + Q2 * (sum <p> in Pc[c
* ]: q[p,i] * y[c,p,t]) == demand[c,i,t] + s[c,i,t] - r[c,i,t];
* subto valid:    forall <c,i> in C*I do       sum <t> in T: ( min(Q1, D[c,i]) * x[c,i,t] + sum <p> in Pc[c]: ( min(q[p,i], D[c
* ,i] ) * y[c,p,t]) ) >= D[c,i];
* subto BigM:    forall <c,p,t> in C*P*T with t>=1 do       y[c,p,t] <= M[c,p] * z[p];
* subto init1:    forall <c,i> in C*I do       s[c,i,0] == 0;
* subto init2:    forall <c,i> in C*I do       r[c,i,0] == 0;
* subto init3:    forall <c,i> in C*I do       r[c,i,nT] == 0;
NAME          mpdp.zpl
ROWS
 N  OBJECTIV          
 L  select_1          
 E  balanc@1          
 E  balanc@2          
 E  balanc@3          
 E  balanc@4          
 E  balanc@5          
 E  balanc@6          
 E  balanc@7          
 E  balanc@8          
 E  balanc@9          
 E  balanc@a          
 E  balanc@b          
 E  balanc@c          
 E  balanc@d          
 E  balanc@e          
 E  balanc@f          
 E  balan@10          
 E  balan@11          
 E  balan@12          
 E  balan@13          
 E  balan@14          
 E  balan@15          
 E  balan@16          
 E  balan@17          
 E  balan@18          
 E  balan@19          
 E  balan@1a          
 E  balan@1b          
 E  balan@1c          
 E  balan@1d          
 E  balan@1e          
 E  balan@1f          
 E  balan@20          
 E  balan@21          
 E  balan@22          
 E  balan@23          
 E  balan@24          
 E  balan@25          
 E  balan@26          
 E  balan@27          
 E  balan@28          
 E  balan@29          
 E  balan@2a          
 E  balan@2b          
 E  balan@2c          
 E  balan@2d          
 E  balan@2e          
 E  balan@2f          
 E  balan@30          
 E  balan@31          
 E  balan@32          
 E  balan@33          
 E  balan@34          
 E  balan@35          
 E  balan@36          
 G  valid_1           
 G  valid_2           
 G  valid_3           
 G  valid_4           
 G  valid_5           
 G  valid_6           
 G  valid_7           
 G  valid_8           
 G  valid_9           
 G  valid_10          
 G  valid_11          
 G  valid_12          
 G  valid_13          
 G  valid_14          
 L  BigM_1            
 L  BigM_2            
 L  BigM_3            
 L  BigM_4            
 L  BigM_5            
 L  BigM_6            
 L  BigM_7            
 L  BigM_8            
 L  BigM_9            
 L  BigM_10           
 L  BigM_11           
 L  BigM_12           
 L  BigM_13           
 L  BigM_14           
 L  BigM_15           
 L  BigM_16           
 L  BigM_17           
 L  BigM_18           
 L  BigM_19           
 L  BigM_20           
 L  BigM_21           
 L  BigM_22           
 L  BigM_23           
 L  BigM_24           
 L  BigM_25           
 L  BigM_26           
 L  BigM_27           
 L  BigM_28           
 L  BigM_29           
 L  BigM_30           
 L  BigM_31           
 L  BigM_32           
 L  BigM_33           
 L  BigM_34           
 L  BigM_35           
 L  BigM_36           
 L  BigM_37           
 L  BigM_38           
 L  BigM_39           
 L  BigM_40           
 L  BigM_41           
 L  BigM_42           
 L  BigM_43           
 L  BigM_44           
 L  BigM_45           
 L  BigM_46           
 L  BigM_47           
 L  BigM_48           
 L  BigM_49           
 L  BigM_50           
 L  BigM_51           
 L  BigM_52           
 L  BigM_53           
 L  BigM_54           
 L  BigM_55           
 L  BigM_56           
 L  BigM_57           
 L  BigM_58           
 L  BigM_59           
 L  BigM_60           
 L  BigM_61           
 L  BigM_62           
 L  BigM_63           
 L  BigM_64           
 L  BigM_65           
 L  BigM_66           
 L  BigM_67           
 L  BigM_68           
 L  BigM_69           
 L  BigM_70           
 L  BigM_71           
 L  BigM_72           
 L  BigM_73           
 L  BigM_74           
 L  BigM_75           
 L  BigM_76           
 L  BigM_77           
 L  BigM_78           
 L  BigM_79           
 L  BigM_80           
 L  BigM_81           
 L  BigM_82           
 L  BigM_83           
 L  BigM_84           
 L  BigM_85           
 L  BigM_86           
 L  BigM_87           
 L  BigM_88           
 L  BigM_89           
 L  BigM_90           
 L  BigM_91           
 L  BigM_92           
 L  BigM_93           
 L  BigM_94           
 L  BigM_95           
 L  BigM_96           
 L  BigM_97           
 L  BigM_98           
 L  BigM_99           
 L  BigM_100          
 L  BigM_101          
 L  BigM_102          
 L  BigM_103          
 L  BigM_104          
 L  BigM_105          
 L  BigM_106          
 L  BigM_107          
 L  BigM_108          
 L  BigM_109          
 L  BigM_110          
 L  BigM_111          
 L  BigM_112          
 L  BigM_113          
 L  BigM_114          
 L  BigM_115          
 L  BigM_116          
 L  BigM_117          
 L  BigM_118          
 L  BigM_119          
 L  BigM_120          
 L  BigM_121          
 L  BigM_122          
 L  BigM_123          
 L  BigM_124          
 L  BigM_125          
 L  BigM_126          
 E  init1_1           
 E  init1_2           
 E  init1_3           
 E  init1_4           
 E  init1_5           
 E  init1_6           
 E  init1_7           
 E  init1_8           
 E  init1_9           
 E  init1_10          
 E  init1_11          
 E  init1_12          
 E  init1_13          
 E  init1_14          
 E  init1_15          
 E  init1_16          
 E  init1_17          
 E  init1_18          
 E  init2_1           
 E  init2_2           
 E  init2_3           
 E  init2_4           
 E  init2_5           
 E  init2_6           
 E  init2_7           
 E  init2_8           
 E  init2_9           
 E  init2_10          
 E  init2_11          
 E  init2_12          
 E  init2_13          
 E  init2_14          
 E  init2_15          
 E  init2_16          
 E  init2_17          
 E  init2_18          
 E  init3_1           
 E  init3_2           
 E  init3_3           
 E  init3_4           
 E  init3_5           
 E  init3_6           
 E  init3_7           
 E  init3_8           
 E  init3_9           
 E  init3_10          
 E  init3_11          
 E  init3_12          
 E  init3_13          
 E  init3_14          
 E  init3_15          
 E  init3_16          
 E  init3_17          
 E  init3_18          
COLUMNS
    MARK0000  'MARKER'                 'INTORG'
    x#1#1#1   valid_1             72
    x#1#1#1   balanc@1            72
    x#1#1#2   valid_1             72
    x#1#1#2   balanc@2            72
    x#1#1#3   valid_1             72
    x#1#1#3   balanc@3            72
    x#1#2#1   balanc@4            72
    x#1#2#2   balanc@5            72
    x#1#2#3   balanc@6            72
    x#1#3#1   valid_2             72
    x#1#3#1   balanc@7            72
    x#1#3#2   valid_2             72
    x#1#3#2   balanc@8            72
    x#1#3#3   valid_2             72
    x#1#3#3   balanc@9            72
    x#2#1#1   valid_3             72
    x#2#1#1   balanc@a            72
    x#2#1#2   valid_3             72
    x#2#1#2   balanc@b            72
    x#2#1#3   valid_3             72
    x#2#1#3   balanc@c            72
    x#2#2#1   valid_4             72
    x#2#2#1   balanc@d            72
    x#2#2#2   valid_4             72
    x#2#2#2   balanc@e            72
    x#2#2#3   valid_4             72
    x#2#2#3   balanc@f            72
    x#2#3#1   valid_5             72
    x#2#3#1   balan@10            72
    x#2#3#2   valid_5             72
    x#2#3#2   balan@11            72
    x#2#3#3   valid_5             72
    x#2#3#3   balan@12            72
    x#3#1#1   valid_6             72
    x#3#1#1   balan@13            72
    x#3#1#2   valid_6             72
    x#3#1#2   balan@14            72
    x#3#1#3   valid_6             72
    x#3#1#3   balan@15            72
    x#3#2#1   valid_7             72
    x#3#2#1   balan@16            72
    x#3#2#2   valid_7             72
    x#3#2#2   balan@17            72
    x#3#2#3   valid_7             72
    x#3#2#3   balan@18            72
    x#3#3#1   valid_8             72
    x#3#3#1   balan@19            72
    x#3#3#2   valid_8             72
    x#3#3#2   balan@1a            72
    x#3#3#3   valid_8             72
    x#3#3#3   balan@1b            72
    x#4#1#1   balan@1c            72
    x#4#1#2   balan@1d            72
    x#4#1#3   balan@1e            72
    x#4#2#1   valid_9             72
    x#4#2#1   balan@1f            72
    x#4#2#2   valid_9             72
    x#4#2#2   balan@20            72
    x#4#2#3   valid_9             72
    x#4#2#3   balan@21            72
    x#4#3#1   valid_10            72
    x#4#3#1   balan@22            72
    x#4#3#2   valid_10            72
    x#4#3#2   balan@23            72
    x#4#3#3   valid_10            72
    x#4#3#3   balan@24            72
    x#5#1#1   valid_11            72
    x#5#1#1   balan@25            72
    x#5#1#2   valid_11            72
    x#5#1#2   balan@26            72
    x#5#1#3   valid_11            72
    x#5#1#3   balan@27            72
    x#5#2#1   valid_12            72
    x#5#2#1   balan@28            72
    x#5#2#2   valid_12            72
    x#5#2#2   balan@29            72
    x#5#2#3   valid_12            72
    x#5#2#3   balan@2a            72
    x#5#3#1   balan@2b            72
    x#5#3#2   balan@2c            72
    x#5#3#3   balan@2d            72
    x#6#1#1   valid_13            72
    x#6#1#1   balan@2e            72
    x#6#1#2   valid_13            72
    x#6#1#2   balan@2f            72
    x#6#1#3   valid_13            72
    x#6#1#3   balan@30            72
    x#6#2#1   valid_14            72
    x#6#2#1   balan@31            72
    x#6#2#2   valid_14            72
    x#6#2#2   balan@32            72
    x#6#2#3   valid_14            72
    x#6#2#3   balan@33            72
    x#6#3#1   balan@34            72
    x#6#3#2   balan@35            72
    x#6#3#3   balan@36            72
    y#1#1#1   BigM_1               1
    y#1#1#1   valid_2              5
    y#1#1#1   valid_1             51
    y#1#1#1   balanc@7             5
    y#1#1#1   balanc@4            16
    y#1#1#1   balanc@1            51
    y#1#1#2   BigM_2               1
    y#1#1#2   valid_2              5
    y#1#1#2   valid_1             51
    y#1#1#2   balanc@8             5
    y#1#1#2   balanc@5            16
    y#1#1#2   balanc@2            51
    y#1#1#3   BigM_3               1
    y#1#1#3   valid_2              5
    y#1#1#3   valid_1             51
    y#1#1#3   balanc@9             5
    y#1#1#3   balanc@6            16
    y#1#1#3   balanc@3            51
    y#1#2#1   BigM_4               1
    y#1#2#1   valid_2             46
    y#1#2#1   valid_1             19
    y#1#2#1   balanc@7            46
    y#1#2#1   balanc@4             7
    y#1#2#1   balanc@1            19
    y#1#2#2   BigM_5               1
    y#1#2#2   valid_2             46
    y#1#2#2   valid_1             19
    y#1#2#2   balanc@8            46
    y#1#2#2   balanc@5             7
    y#1#2#2   balanc@2            19
    y#1#2#3   BigM_6               1
    y#1#2#3   valid_2             46
    y#1#2#3   valid_1             19
    y#1#2#3   balanc@9            46
    y#1#2#3   balanc@6             7
    y#1#2#3   balanc@3            19
    y#1#3#1   BigM_7               1
    y#1#3#1   valid_2             42
    y#1#3#1   valid_1              6
    y#1#3#1   balanc@7            42
    y#1#3#1   balanc@4            24
    y#1#3#1   balanc@1             6
    y#1#3#2   BigM_8               1
    y#1#3#2   valid_2             42
    y#1#3#2   valid_1              6
    y#1#3#2   balanc@8            42
    y#1#3#2   balanc@5            24
    y#1#3#2   balanc@2             6
    y#1#3#3   BigM_9               1
    y#1#3#3   valid_2             42
    y#1#3#3   valid_1              6
    y#1#3#3   balanc@9            42
    y#1#3#3   balanc@6            24
    y#1#3#3   balanc@3             6
    y#1#4#1   BigM_10              1
    y#1#4#1   valid_2              7
    y#1#4#1   valid_1              1
    y#1#4#1   balanc@7             7
    y#1#4#1   balanc@4            64
    y#1#4#1   balanc@1             1
    y#1#4#2   BigM_11              1
    y#1#4#2   valid_2              7
    y#1#4#2   valid_1              1
    y#1#4#2   balanc@8             7
    y#1#4#2   balanc@5            64
    y#1#4#2   balanc@2             1
    y#1#4#3   BigM_12              1
    y#1#4#3   valid_2              7
    y#1#4#3   valid_1              1
    y#1#4#3   balanc@9             7
    y#1#4#3   balanc@6            64
    y#1#4#3   balanc@3             1
    y#1#5#1   BigM_13              1
    y#1#5#1   valid_2             30
    y#1#5#1   valid_1             20
    y#1#5#1   balanc@7            30
    y#1#5#1   balanc@4            22
    y#1#5#1   balanc@1            20
    y#1#5#2   BigM_14              1
    y#1#5#2   valid_2             30
    y#1#5#2   valid_1             20
    y#1#5#2   balanc@8            30
    y#1#5#2   balanc@5            22
    y#1#5#2   balanc@2            20
    y#1#5#3   BigM_15              1
    y#1#5#3   valid_2             30
    y#1#5#3   valid_1             20
    y#1#5#3   balanc@9            30
    y#1#5#3   balanc@6            22
    y#1#5#3   balanc@3            20
    y#1#6#1   BigM_16              1
    y#1#6#1   valid_2             36
    y#1#6#1   valid_1             18
    y#1#6#1   balanc@7            36
    y#1#6#1   balanc@4            18
    y#1#6#1   balanc@1            18
    y#1#6#2   BigM_17              1
    y#1#6#2   valid_2             36
    y#1#6#2   valid_1             18
    y#1#6#2   balanc@8            36
    y#1#6#2   balanc@5            18
    y#1#6#2   balanc@2            18
    y#1#6#3   BigM_18              1
    y#1#6#3   valid_2             36
    y#1#6#3   valid_1             18
    y#1#6#3   balanc@9            36
    y#1#6#3   balanc@6            18
    y#1#6#3   balanc@3            18
    y#1#7#1   BigM_19              1
    y#1#7#2   BigM_20              1
    y#1#7#3   BigM_21              1
    y#2#1#1   BigM_22              1
    y#2#1#1   valid_5              5
    y#2#1#1   valid_4             16
    y#2#1#1   valid_3             51
    y#2#1#1   balan@10             5
    y#2#1#1   balanc@d            16
    y#2#1#1   balanc@a            51
    y#2#1#2   BigM_23              1
    y#2#1#2   valid_5              5
    y#2#1#2   valid_4             16
    y#2#1#2   valid_3             51
    y#2#1#2   balan@11             5
    y#2#1#2   balanc@e            16
    y#2#1#2   balanc@b            51
    y#2#1#3   BigM_24              1
    y#2#1#3   valid_5              5
    y#2#1#3   valid_4             16
    y#2#1#3   valid_3             51
    y#2#1#3   balan@12             5
    y#2#1#3   balanc@f            16
    y#2#1#3   balanc@c            51
    y#2#2#1   BigM_25              1
    y#2#2#1   valid_5             46
    y#2#2#1   valid_4              7
    y#2#2#1   valid_3             19
    y#2#2#1   balan@10            46
    y#2#2#1   balanc@d             7
    y#2#2#1   balanc@a            19
    y#2#2#2   BigM_26              1
    y#2#2#2   valid_5             46
    y#2#2#2   valid_4              7
    y#2#2#2   valid_3             19
    y#2#2#2   balan@11            46
    y#2#2#2   balanc@e             7
    y#2#2#2   balanc@b            19
    y#2#2#3   BigM_27              1
    y#2#2#3   valid_5             46
    y#2#2#3   valid_4              7
    y#2#2#3   valid_3             19
    y#2#2#3   balan@12            46
    y#2#2#3   balanc@f             7
    y#2#2#3   balanc@c            19
    y#2#3#1   BigM_28              1
    y#2#3#1   valid_5             42
    y#2#3#1   valid_4             24
    y#2#3#1   valid_3              6
    y#2#3#1   balan@10            42
    y#2#3#1   balanc@d            24
    y#2#3#1   balanc@a             6
    y#2#3#2   BigM_29              1
    y#2#3#2   valid_5             42
    y#2#3#2   valid_4             24
    y#2#3#2   valid_3              6
    y#2#3#2   balan@11            42
    y#2#3#2   balanc@e            24
    y#2#3#2   balanc@b             6
    y#2#3#3   BigM_30              1
    y#2#3#3   valid_5             42
    y#2#3#3   valid_4             24
    y#2#3#3   valid_3              6
    y#2#3#3   balan@12            42
    y#2#3#3   balanc@f            24
    y#2#3#3   balanc@c             6
    y#2#4#1   BigM_31              1
    y#2#4#1   valid_5              7
    y#2#4#1   valid_4             64
    y#2#4#1   valid_3              1
    y#2#4#1   balan@10             7
    y#2#4#1   balanc@d            64
    y#2#4#1   balanc@a             1
    y#2#4#2   BigM_32              1
    y#2#4#2   valid_5              7
    y#2#4#2   valid_4             64
    y#2#4#2   valid_3              1
    y#2#4#2   balan@11             7
    y#2#4#2   balanc@e            64
    y#2#4#2   balanc@b             1
    y#2#4#3   BigM_33              1
    y#2#4#3   valid_5              7
    y#2#4#3   valid_4             64
    y#2#4#3   valid_3              1
    y#2#4#3   balan@12             7
    y#2#4#3   balanc@f            64
    y#2#4#3   balanc@c             1
    y#2#5#1   BigM_34              1
    y#2#5#1   valid_5             30
    y#2#5#1   valid_4             22
    y#2#5#1   valid_3             20
    y#2#5#1   balan@10            30
    y#2#5#1   balanc@d            22
    y#2#5#1   balanc@a            20
    y#2#5#2   BigM_35              1
    y#2#5#2   valid_5             30
    y#2#5#2   valid_4             22
    y#2#5#2   valid_3             20
    y#2#5#2   balan@11            30
    y#2#5#2   balanc@e            22
    y#2#5#2   balanc@b            20
    y#2#5#3   BigM_36              1
    y#2#5#3   valid_5             30
    y#2#5#3   valid_4             22
    y#2#5#3   valid_3             20
    y#2#5#3   balan@12            30
    y#2#5#3   balanc@f            22
    y#2#5#3   balanc@c            20
    y#2#6#1   BigM_37              1
    y#2#6#1   valid_5             36
    y#2#6#1   valid_4             18
    y#2#6#1   valid_3             18
    y#2#6#1   balan@10            36
    y#2#6#1   balanc@d            18
    y#2#6#1   balanc@a            18
    y#2#6#2   BigM_38              1
    y#2#6#2   valid_5             36
    y#2#6#2   valid_4             18
    y#2#6#2   valid_3             18
    y#2#6#2   balan@11            36
    y#2#6#2   balanc@e            18
    y#2#6#2   balanc@b            18
    y#2#6#3   BigM_39              1
    y#2#6#3   valid_5             36
    y#2#6#3   valid_4             18
    y#2#6#3   valid_3             18
    y#2#6#3   balan@12            36
    y#2#6#3   balanc@f            18
    y#2#6#3   balanc@c            18
    y#2#7#1   BigM_40              1
    y#2#7#2   BigM_41              1
    y#2#7#3   BigM_42              1
    y#3#1#1   BigM_43              1
    y#3#1#1   valid_8              5
    y#3#1#1   valid_7             16
    y#3#1#1   valid_6             51
    y#3#1#1   balan@19             5
    y#3#1#1   balan@16            16
    y#3#1#1   balan@13            51
    y#3#1#2   BigM_44              1
    y#3#1#2   valid_8              5
    y#3#1#2   valid_7             16
    y#3#1#2   valid_6             51
    y#3#1#2   balan@1a             5
    y#3#1#2   balan@17            16
    y#3#1#2   balan@14            51
    y#3#1#3   BigM_45              1
    y#3#1#3   valid_8              5
    y#3#1#3   valid_7             16
    y#3#1#3   valid_6             51
    y#3#1#3   balan@1b             5
    y#3#1#3   balan@18            16
    y#3#1#3   balan@15            51
    y#3#2#1   BigM_46              1
    y#3#2#1   valid_8             46
    y#3#2#1   valid_7              7
    y#3#2#1   valid_6             19
    y#3#2#1   balan@19            46
    y#3#2#1   balan@16             7
    y#3#2#1   balan@13            19
    y#3#2#2   BigM_47              1
    y#3#2#2   valid_8             46
    y#3#2#2   valid_7              7
    y#3#2#2   valid_6             19
    y#3#2#2   balan@1a            46
    y#3#2#2   balan@17             7
    y#3#2#2   balan@14            19
    y#3#2#3   BigM_48              1
    y#3#2#3   valid_8             46
    y#3#2#3   valid_7              7
    y#3#2#3   valid_6             19
    y#3#2#3   balan@1b            46
    y#3#2#3   balan@18             7
    y#3#2#3   balan@15            19
    y#3#3#1   BigM_49              1
    y#3#3#1   valid_8             42
    y#3#3#1   valid_7             24
    y#3#3#1   valid_6              6
    y#3#3#1   balan@19            42
    y#3#3#1   balan@16            24
    y#3#3#1   balan@13             6
    y#3#3#2   BigM_50              1
    y#3#3#2   valid_8             42
    y#3#3#2   valid_7             24
    y#3#3#2   valid_6              6
    y#3#3#2   balan@1a            42
    y#3#3#2   balan@17            24
    y#3#3#2   balan@14             6
    y#3#3#3   BigM_51              1
    y#3#3#3   valid_8             42
    y#3#3#3   valid_7             24
    y#3#3#3   valid_6              6
    y#3#3#3   balan@1b            42
    y#3#3#3   balan@18            24
    y#3#3#3   balan@15             6
    y#3#4#1   BigM_52              1
    y#3#4#1   valid_8              7
    y#3#4#1   valid_7             64
    y#3#4#1   valid_6              1
    y#3#4#1   balan@19             7
    y#3#4#1   balan@16            64
    y#3#4#1   balan@13             1
    y#3#4#2   BigM_53              1
    y#3#4#2   valid_8              7
    y#3#4#2   valid_7             64
    y#3#4#2   valid_6              1
    y#3#4#2   balan@1a             7
    y#3#4#2   balan@17            64
    y#3#4#2   balan@14             1
    y#3#4#3   BigM_54              1
    y#3#4#3   valid_8              7
    y#3#4#3   valid_7             64
    y#3#4#3   valid_6              1
    y#3#4#3   balan@1b             7
    y#3#4#3   balan@18            64
    y#3#4#3   balan@15             1
    y#3#5#1   BigM_55              1
    y#3#5#1   valid_8             30
    y#3#5#1   valid_7             22
    y#3#5#1   valid_6             20
    y#3#5#1   balan@19            30
    y#3#5#1   balan@16            22
    y#3#5#1   balan@13            20
    y#3#5#2   BigM_56              1
    y#3#5#2   valid_8             30
    y#3#5#2   valid_7             22
    y#3#5#2   valid_6             20
    y#3#5#2   balan@1a            30
    y#3#5#2   balan@17            22
    y#3#5#2   balan@14            20
    y#3#5#3   BigM_57              1
    y#3#5#3   valid_8             30
    y#3#5#3   valid_7             22
    y#3#5#3   valid_6             20
    y#3#5#3   balan@1b            30
    y#3#5#3   balan@18            22
    y#3#5#3   balan@15            20
    y#3#6#1   BigM_58              1
    y#3#6#1   valid_8             36
    y#3#6#1   valid_7             18
    y#3#6#1   valid_6             18
    y#3#6#1   balan@19            36
    y#3#6#1   balan@16            18
    y#3#6#1   balan@13            18
    y#3#6#2   BigM_59              1
    y#3#6#2   valid_8             36
    y#3#6#2   valid_7             18
    y#3#6#2   valid_6             18
    y#3#6#2   balan@1a            36
    y#3#6#2   balan@17            18
    y#3#6#2   balan@14            18
    y#3#6#3   BigM_60              1
    y#3#6#3   valid_8             36
    y#3#6#3   valid_7             18
    y#3#6#3   valid_6             18
    y#3#6#3   balan@1b            36
    y#3#6#3   balan@18            18
    y#3#6#3   balan@15            18
    y#3#7#1   BigM_61              1
    y#3#7#2   BigM_62              1
    y#3#7#3   BigM_63              1
    y#4#1#1   BigM_64              1
    y#4#1#1   valid_10             5
    y#4#1#1   valid_9             16
    y#4#1#1   balan@22             5
    y#4#1#1   balan@1f            16
    y#4#1#1   balan@1c            51
    y#4#1#2   BigM_65              1
    y#4#1#2   valid_10             5
    y#4#1#2   valid_9             16
    y#4#1#2   balan@23             5
    y#4#1#2   balan@20            16
    y#4#1#2   balan@1d            51
    y#4#1#3   BigM_66              1
    y#4#1#3   valid_10             5
    y#4#1#3   valid_9             16
    y#4#1#3   balan@24             5
    y#4#1#3   balan@21            16
    y#4#1#3   balan@1e            51
    y#4#2#1   BigM_67              1
    y#4#2#1   valid_10            46
    y#4#2#1   valid_9              7
    y#4#2#1   balan@22            46
    y#4#2#1   balan@1f             7
    y#4#2#1   balan@1c            19
    y#4#2#2   BigM_68              1
    y#4#2#2   valid_10            46
    y#4#2#2   valid_9              7
    y#4#2#2   balan@23            46
    y#4#2#2   balan@20             7
    y#4#2#2   balan@1d            19
    y#4#2#3   BigM_69              1
    y#4#2#3   valid_10            46
    y#4#2#3   valid_9              7
    y#4#2#3   balan@24            46
    y#4#2#3   balan@21             7
    y#4#2#3   balan@1e            19
    y#4#3#1   BigM_70              1
    y#4#3#1   valid_10            42
    y#4#3#1   valid_9             24
    y#4#3#1   balan@22            42
    y#4#3#1   balan@1f            24
    y#4#3#1   balan@1c             6
    y#4#3#2   BigM_71              1
    y#4#3#2   valid_10            42
    y#4#3#2   valid_9             24
    y#4#3#2   balan@23            42
    y#4#3#2   balan@20            24
    y#4#3#2   balan@1d             6
    y#4#3#3   BigM_72              1
    y#4#3#3   valid_10            42
    y#4#3#3   valid_9             24
    y#4#3#3   balan@24            42
    y#4#3#3   balan@21            24
    y#4#3#3   balan@1e             6
    y#4#4#1   BigM_73              1
    y#4#4#1   valid_10             7
    y#4#4#1   valid_9             64
    y#4#4#1   balan@22             7
    y#4#4#1   balan@1f            64
    y#4#4#1   balan@1c             1
    y#4#4#2   BigM_74              1
    y#4#4#2   valid_10             7
    y#4#4#2   valid_9             64
    y#4#4#2   balan@23             7
    y#4#4#2   balan@20            64
    y#4#4#2   balan@1d             1
    y#4#4#3   BigM_75              1
    y#4#4#3   valid_10             7
    y#4#4#3   valid_9             64
    y#4#4#3   balan@24             7
    y#4#4#3   balan@21            64
    y#4#4#3   balan@1e             1
    y#4#5#1   BigM_76              1
    y#4#5#1   valid_10            30
    y#4#5#1   valid_9             22
    y#4#5#1   balan@22            30
    y#4#5#1   balan@1f            22
    y#4#5#1   balan@1c            20
    y#4#5#2   BigM_77              1
    y#4#5#2   valid_10            30
    y#4#5#2   valid_9             22
    y#4#5#2   balan@23            30
    y#4#5#2   balan@20            22
    y#4#5#2   balan@1d            20
    y#4#5#3   BigM_78              1
    y#4#5#3   valid_10            30
    y#4#5#3   valid_9             22
    y#4#5#3   balan@24            30
    y#4#5#3   balan@21            22
    y#4#5#3   balan@1e            20
    y#4#6#1   BigM_79              1
    y#4#6#1   valid_10            36
    y#4#6#1   valid_9             18
    y#4#6#1   balan@22            36
    y#4#6#1   balan@1f            18
    y#4#6#1   balan@1c            18
    y#4#6#2   BigM_80              1
    y#4#6#2   valid_10            36
    y#4#6#2   valid_9             18
    y#4#6#2   balan@23            36
    y#4#6#2   balan@20            18
    y#4#6#2   balan@1d            18
    y#4#6#3   BigM_81              1
    y#4#6#3   valid_10            36
    y#4#6#3   valid_9             18
    y#4#6#3   balan@24            36
    y#4#6#3   balan@21            18
    y#4#6#3   balan@1e            18
    y#4#7#1   BigM_82              1
    y#4#7#2   BigM_83              1
    y#4#7#3   BigM_84              1
    y#5#1#1   BigM_85              1
    y#5#1#1   valid_12            16
    y#5#1#1   valid_11            51
    y#5#1#1   balan@2b             5
    y#5#1#1   balan@28            16
    y#5#1#1   balan@25            51
    y#5#1#2   BigM_86              1
    y#5#1#2   valid_12            16
    y#5#1#2   valid_11            51
    y#5#1#2   balan@2c             5
    y#5#1#2   balan@29            16
    y#5#1#2   balan@26            51
    y#5#1#3   BigM_87              1
    y#5#1#3   valid_12            16
    y#5#1#3   valid_11            51
    y#5#1#3   balan@2d             5
    y#5#1#3   balan@2a            16
    y#5#1#3   balan@27            51
    y#5#2#1   BigM_88              1
    y#5#2#1   valid_12             7
    y#5#2#1   valid_11            19
    y#5#2#1   balan@2b            46
    y#5#2#1   balan@28             7
    y#5#2#1   balan@25            19
    y#5#2#2   BigM_89              1
    y#5#2#2   valid_12             7
    y#5#2#2   valid_11            19
    y#5#2#2   balan@2c            46
    y#5#2#2   balan@29             7
    y#5#2#2   balan@26            19
    y#5#2#3   BigM_90              1
    y#5#2#3   valid_12             7
    y#5#2#3   valid_11            19
    y#5#2#3   balan@2d            46
    y#5#2#3   balan@2a             7
    y#5#2#3   balan@27            19
    y#5#3#1   BigM_91              1
    y#5#3#1   valid_12            24
    y#5#3#1   valid_11             6
    y#5#3#1   balan@2b            42
    y#5#3#1   balan@28            24
    y#5#3#1   balan@25             6
    y#5#3#2   BigM_92              1
    y#5#3#2   valid_12            24
    y#5#3#2   valid_11             6
    y#5#3#2   balan@2c            42
    y#5#3#2   balan@29            24
    y#5#3#2   balan@26             6
    y#5#3#3   BigM_93              1
    y#5#3#3   valid_12            24
    y#5#3#3   valid_11             6
    y#5#3#3   balan@2d            42
    y#5#3#3   balan@2a            24
    y#5#3#3   balan@27             6
    y#5#4#1   BigM_94              1
    y#5#4#1   valid_12            64
    y#5#4#1   valid_11             1
    y#5#4#1   balan@2b             7
    y#5#4#1   balan@28            64
    y#5#4#1   balan@25             1
    y#5#4#2   BigM_95              1
    y#5#4#2   valid_12            64
    y#5#4#2   valid_11             1
    y#5#4#2   balan@2c             7
    y#5#4#2   balan@29            64
    y#5#4#2   balan@26             1
    y#5#4#3   BigM_96              1
    y#5#4#3   valid_12            64
    y#5#4#3   valid_11             1
    y#5#4#3   balan@2d             7
    y#5#4#3   balan@2a            64
    y#5#4#3   balan@27             1
    y#5#5#1   BigM_97              1
    y#5#5#1   valid_12            22
    y#5#5#1   valid_11            20
    y#5#5#1   balan@2b            30
    y#5#5#1   balan@28            22
    y#5#5#1   balan@25            20
    y#5#5#2   BigM_98              1
    y#5#5#2   valid_12            22
    y#5#5#2   valid_11            20
    y#5#5#2   balan@2c            30
    y#5#5#2   balan@29            22
    y#5#5#2   balan@26            20
    y#5#5#3   BigM_99              1
    y#5#5#3   valid_12            22
    y#5#5#3   valid_11            20
    y#5#5#3   balan@2d            30
    y#5#5#3   balan@2a            22
    y#5#5#3   balan@27            20
    y#5#6#1   BigM_100             1
    y#5#6#1   valid_12            18
    y#5#6#1   valid_11            18
    y#5#6#1   balan@2b            36
    y#5#6#1   balan@28            18
    y#5#6#1   balan@25            18
    y#5#6#2   BigM_101             1
    y#5#6#2   valid_12            18
    y#5#6#2   valid_11            18
    y#5#6#2   balan@2c            36
    y#5#6#2   balan@29            18
    y#5#6#2   balan@26            18
    y#5#6#3   BigM_102             1
    y#5#6#3   valid_12            18
    y#5#6#3   valid_11            18
    y#5#6#3   balan@2d            36
    y#5#6#3   balan@2a            18
    y#5#6#3   balan@27            18
    y#5#7#1   BigM_103             1
    y#5#7#1   valid_12            24
    y#5#7#1   valid_11            48
    y#5#7#1   balan@28            24
    y#5#7#1   balan@25            48
    y#5#7#2   BigM_104             1
    y#5#7#2   valid_12            24
    y#5#7#2   valid_11            48
    y#5#7#2   balan@29            24
    y#5#7#2   balan@26            48
    y#5#7#3   BigM_105             1
    y#5#7#3   valid_12            24
    y#5#7#3   valid_11            48
    y#5#7#3   balan@2a            24
    y#5#7#3   balan@27            48
    y#6#1#1   BigM_106             1
    y#6#1#1   valid_14            16
    y#6#1#1   valid_13            51
    y#6#1#1   balan@34             5
    y#6#1#1   balan@31            16
    y#6#1#1   balan@2e            51
    y#6#1#2   BigM_107             1
    y#6#1#2   valid_14            16
    y#6#1#2   valid_13            51
    y#6#1#2   balan@35             5
    y#6#1#2   balan@32            16
    y#6#1#2   balan@2f            51
    y#6#1#3   BigM_108             1
    y#6#1#3   valid_14            16
    y#6#1#3   valid_13            51
    y#6#1#3   balan@36             5
    y#6#1#3   balan@33            16
    y#6#1#3   balan@30            51
    y#6#2#1   BigM_109             1
    y#6#2#1   valid_14             7
    y#6#2#1   valid_13            19
    y#6#2#1   balan@34            46
    y#6#2#1   balan@31             7
    y#6#2#1   balan@2e            19
    y#6#2#2   BigM_110             1
    y#6#2#2   valid_14             7
    y#6#2#2   valid_13            19
    y#6#2#2   balan@35            46
    y#6#2#2   balan@32             7
    y#6#2#2   balan@2f            19
    y#6#2#3   BigM_111             1
    y#6#2#3   valid_14             7
    y#6#2#3   valid_13            19
    y#6#2#3   balan@36            46
    y#6#2#3   balan@33             7
    y#6#2#3   balan@30            19
    y#6#3#1   BigM_112             1
    y#6#3#1   valid_14            24
    y#6#3#1   valid_13             6
    y#6#3#1   balan@34            42
    y#6#3#1   balan@31            24
    y#6#3#1   balan@2e             6
    y#6#3#2   BigM_113             1
    y#6#3#2   valid_14            24
    y#6#3#2   valid_13             6
    y#6#3#2   balan@35            42
    y#6#3#2   balan@32            24
    y#6#3#2   balan@2f             6
    y#6#3#3   BigM_114             1
    y#6#3#3   valid_14            24
    y#6#3#3   valid_13             6
    y#6#3#3   balan@36            42
    y#6#3#3   balan@33            24
    y#6#3#3   balan@30             6
    y#6#4#1   BigM_115             1
    y#6#4#1   valid_14            64
    y#6#4#1   valid_13             1
    y#6#4#1   balan@34             7
    y#6#4#1   balan@31            64
    y#6#4#1   balan@2e             1
    y#6#4#2   BigM_116             1
    y#6#4#2   valid_14            64
    y#6#4#2   valid_13             1
    y#6#4#2   balan@35             7
    y#6#4#2   balan@32            64
    y#6#4#2   balan@2f             1
    y#6#4#3   BigM_117             1
    y#6#4#3   valid_14            64
    y#6#4#3   valid_13             1
    y#6#4#3   balan@36             7
    y#6#4#3   balan@33            64
    y#6#4#3   balan@30             1
    y#6#5#1   BigM_118             1
    y#6#5#1   valid_14            22
    y#6#5#1   valid_13            20
    y#6#5#1   balan@34            30
    y#6#5#1   balan@31            22
    y#6#5#1   balan@2e            20
    y#6#5#2   BigM_119             1
    y#6#5#2   valid_14            22
    y#6#5#2   valid_13            20
    y#6#5#2   balan@35            30
    y#6#5#2   balan@32            22
    y#6#5#2   balan@2f            20
    y#6#5#3   BigM_120             1
    y#6#5#3   valid_14            22
    y#6#5#3   valid_13            20
    y#6#5#3   balan@36            30
    y#6#5#3   balan@33            22
    y#6#5#3   balan@30            20
    y#6#6#1   BigM_121             1
    y#6#6#1   valid_14            18
    y#6#6#1   valid_13            18
    y#6#6#1   balan@34            36
    y#6#6#1   balan@31            18
    y#6#6#1   balan@2e            18
    y#6#6#2   BigM_122             1
    y#6#6#2   valid_14            18
    y#6#6#2   valid_13            18
    y#6#6#2   balan@35            36
    y#6#6#2   balan@32            18
    y#6#6#2   balan@2f            18
    y#6#6#3   BigM_123             1
    y#6#6#3   valid_14            18
    y#6#6#3   valid_13            18
    y#6#6#3   balan@36            36
    y#6#6#3   balan@33            18
    y#6#6#3   balan@30            18
    y#6#7#1   BigM_124             1
    y#6#7#1   valid_14            24
    y#6#7#1   valid_13            48
    y#6#7#1   balan@31            24
    y#6#7#1   balan@2e            48
    y#6#7#2   BigM_125             1
    y#6#7#2   valid_14            24
    y#6#7#2   valid_13            48
    y#6#7#2   balan@32            24
    y#6#7#2   balan@2f            48
    y#6#7#3   BigM_126             1
    y#6#7#3   valid_14            24
    y#6#7#3   valid_13            48
    y#6#7#3   balan@33            24
    y#6#7#3   balan@30            48
    z#1       BigM_108          -120
    z#1       BigM_107          -120
    z#1       BigM_106          -120
    z#1       BigM_87            -55
    z#1       BigM_86            -55
    z#1       BigM_85            -55
    z#1       BigM_66           -335
    z#1       BigM_65           -335
    z#1       BigM_64           -335
    z#1       BigM_45           -306
    z#1       BigM_44           -306
    z#1       BigM_43           -306
    z#1       BigM_24           -339
    z#1       BigM_23           -339
    z#1       BigM_22           -339
    z#1       BigM_3            -220
    z#1       BigM_2            -220
    z#1       BigM_1            -220
    z#1       select_1             1
    z#2       BigM_111          -273
    z#2       BigM_110          -273
    z#2       BigM_109          -273
    z#2       BigM_90           -146
    z#2       BigM_89           -146
    z#2       BigM_88           -146
    z#2       BigM_69           -339
    z#2       BigM_68           -339
    z#2       BigM_67           -339
    z#2       BigM_48           -139
    z#2       BigM_47           -139
    z#2       BigM_46           -139
    z#2       BigM_27           -127
    z#2       BigM_26           -127
    z#2       BigM_25           -127
    z#2       BigM_6             -70
    z#2       BigM_5             -70
    z#2       BigM_4             -70
    z#2       select_1             1
    z#3       BigM_114          -433
    z#3       BigM_113          -433
    z#3       BigM_112          -433
    z#3       BigM_93           -461
    z#3       BigM_92           -461
    z#3       BigM_91           -461
    z#3       BigM_72            -99
    z#3       BigM_71            -99
    z#3       BigM_70            -99
    z#3       BigM_51           -159
    z#3       BigM_50           -159
    z#3       BigM_49           -159
    z#3       BigM_30           -263
    z#3       BigM_29           -263
    z#3       BigM_28           -263
    z#3       BigM_9            -221
    z#3       BigM_8            -221
    z#3       BigM_7            -221
    z#3       select_1             1
    z#4       BigM_117         -2594
    z#4       BigM_116         -2594
    z#4       BigM_115         -2594
    z#4       BigM_96          -2762
    z#4       BigM_95          -2762
    z#4       BigM_94          -2762
    z#4       BigM_75           -239
    z#4       BigM_74           -239
    z#4       BigM_73           -239
    z#4       BigM_54           -949
    z#4       BigM_53           -949
    z#4       BigM_52           -949
    z#4       BigM_33          -1575
    z#4       BigM_32          -1575
    z#4       BigM_31          -1575
    z#4       BigM_12          -1322
    z#4       BigM_11          -1322
    z#4       BigM_10          -1322
    z#4       select_1             1
    z#5       BigM_120          -130
    z#5       BigM_119          -130
    z#5       BigM_118          -130
    z#5       BigM_99           -139
    z#5       BigM_98           -139
    z#5       BigM_97           -139
    z#5       BigM_78           -108
    z#5       BigM_77           -108
    z#5       BigM_76           -108
    z#5       BigM_57            -51
    z#5       BigM_56            -51
    z#5       BigM_55            -51
    z#5       BigM_36            -79
    z#5       BigM_35            -79
    z#5       BigM_34            -79
    z#5       BigM_15            -67
    z#5       BigM_14            -67
    z#5       BigM_13            -67
    z#5       select_1             1
    z#6       BigM_123          -145
    z#6       BigM_122          -145
    z#6       BigM_121          -145
    z#6       BigM_102          -154
    z#6       BigM_101          -154
    z#6       BigM_100          -154
    z#6       BigM_81           -132
    z#6       BigM_80           -132
    z#6       BigM_79           -132
    z#6       BigM_60            -54
    z#6       BigM_59            -54
    z#6       BigM_58            -54
    z#6       BigM_39            -88
    z#6       BigM_38            -88
    z#6       BigM_37            -88
    z#6       BigM_18            -74
    z#6       BigM_17            -74
    z#6       BigM_16            -74
    z#6       select_1             1
    z#7       BigM_126           -80
    z#7       BigM_125           -80
    z#7       BigM_124           -80
    z#7       BigM_105           -58
    z#7       BigM_104           -58
    z#7       BigM_103           -58
    z#7       BigM_84            -99
    z#7       BigM_83            -99
    z#7       BigM_82            -99
    z#7       BigM_63            -41
    z#7       BigM_62            -41
    z#7       BigM_61            -41
    z#7       BigM_42            -37
    z#7       BigM_41            -37
    z#7       BigM_40            -37
    z#7       BigM_21            -28
    z#7       BigM_20            -28
    z#7       BigM_19            -28
    z#7       select_1             1
    MARK0001  'MARKER'                 'INTEND'
    r#1#1#0   init2_1              1
    r#1#1#0   balanc@1            -1
    r#1#1#1   OBJECTIV             5
    r#1#1#1   balanc@2            -1
    r#1#1#1   balanc@1             1
    r#1#1#2   OBJECTIV             5
    r#1#1#2   balanc@3            -1
    r#1#1#2   balanc@2             1
    r#1#1#3   OBJECTIV             5
    r#1#1#3   init3_1              1
    r#1#1#3   balanc@3             1
    r#1#2#0   init2_2              1
    r#1#2#0   balanc@4            -1
    r#1#2#1   OBJECTIV           5.5
    r#1#2#1   balanc@5            -1
    r#1#2#1   balanc@4             1
    r#1#2#2   OBJECTIV           5.5
    r#1#2#2   balanc@6            -1
    r#1#2#2   balanc@5             1
    r#1#2#3   OBJECTIV           5.5
    r#1#2#3   init3_2              1
    r#1#2#3   balanc@6             1
    r#1#3#0   init2_3              1
    r#1#3#0   balanc@7            -1
    r#1#3#1   OBJECTIV           5.5
    r#1#3#1   balanc@8            -1
    r#1#3#1   balanc@7             1
    r#1#3#2   OBJECTIV           5.5
    r#1#3#2   balanc@9            -1
    r#1#3#2   balanc@8             1
    r#1#3#3   OBJECTIV           5.5
    r#1#3#3   init3_3              1
    r#1#3#3   balanc@9             1
    r#2#1#0   init2_4              1
    r#2#1#0   balanc@a            -1
    r#2#1#1   OBJECTIV             5
    r#2#1#1   balanc@b            -1
    r#2#1#1   balanc@a             1
    r#2#1#2   OBJECTIV             5
    r#2#1#2   balanc@c            -1
    r#2#1#2   balanc@b             1
    r#2#1#3   OBJECTIV             5
    r#2#1#3   init3_4              1
    r#2#1#3   balanc@c             1
    r#2#2#0   init2_5              1
    r#2#2#0   balanc@d            -1
    r#2#2#1   OBJECTIV           5.5
    r#2#2#1   balanc@e            -1
    r#2#2#1   balanc@d             1
    r#2#2#2   OBJECTIV           5.5
    r#2#2#2   balanc@f            -1
    r#2#2#2   balanc@e             1
    r#2#2#3   OBJECTIV           5.5
    r#2#2#3   init3_5              1
    r#2#2#3   balanc@f             1
    r#2#3#0   init2_6              1
    r#2#3#0   balan@10            -1
    r#2#3#1   OBJECTIV           5.5
    r#2#3#1   balan@11            -1
    r#2#3#1   balan@10             1
    r#2#3#2   OBJECTIV           5.5
    r#2#3#2   balan@12            -1
    r#2#3#2   balan@11             1
    r#2#3#3   OBJECTIV           5.5
    r#2#3#3   init3_6              1
    r#2#3#3   balan@12             1
    r#3#1#0   init2_7              1
    r#3#1#0   balan@13            -1
    r#3#1#1   OBJECTIV             5
    r#3#1#1   balan@14            -1
    r#3#1#1   balan@13             1
    r#3#1#2   OBJECTIV             5
    r#3#1#2   balan@15            -1
    r#3#1#2   balan@14             1
    r#3#1#3   OBJECTIV             5
    r#3#1#3   init3_7              1
    r#3#1#3   balan@15             1
    r#3#2#0   init2_8              1
    r#3#2#0   balan@16            -1
    r#3#2#1   OBJECTIV           5.5
    r#3#2#1   balan@17            -1
    r#3#2#1   balan@16             1
    r#3#2#2   OBJECTIV           5.5
    r#3#2#2   balan@18            -1
    r#3#2#2   balan@17             1
    r#3#2#3   OBJECTIV           5.5
    r#3#2#3   init3_8              1
    r#3#2#3   balan@18             1
    r#3#3#0   init2_9              1
    r#3#3#0   balan@19            -1
    r#3#3#1   OBJECTIV           5.5
    r#3#3#1   balan@1a            -1
    r#3#3#1   balan@19             1
    r#3#3#2   OBJECTIV           5.5
    r#3#3#2   balan@1b            -1
    r#3#3#2   balan@1a             1
    r#3#3#3   OBJECTIV           5.5
    r#3#3#3   init3_9              1
    r#3#3#3   balan@1b             1
    r#4#1#0   init2_10             1
    r#4#1#0   balan@1c            -1
    r#4#1#1   OBJECTIV             5
    r#4#1#1   balan@1d            -1
    r#4#1#1   balan@1c             1
    r#4#1#2   OBJECTIV             5
    r#4#1#2   balan@1e            -1
    r#4#1#2   balan@1d             1
    r#4#1#3   OBJECTIV             5
    r#4#1#3   init3_10             1
    r#4#1#3   balan@1e             1
    r#4#2#0   init2_11             1
    r#4#2#0   balan@1f            -1
    r#4#2#1   OBJECTIV           5.5
    r#4#2#1   balan@20            -1
    r#4#2#1   balan@1f             1
    r#4#2#2   OBJECTIV           5.5
    r#4#2#2   balan@21            -1
    r#4#2#2   balan@20             1
    r#4#2#3   OBJECTIV           5.5
    r#4#2#3   init3_11             1
    r#4#2#3   balan@21             1
    r#4#3#0   init2_12             1
    r#4#3#0   balan@22            -1
    r#4#3#1   OBJECTIV           5.5
    r#4#3#1   balan@23            -1
    r#4#3#1   balan@22             1
    r#4#3#2   OBJECTIV           5.5
    r#4#3#2   balan@24            -1
    r#4#3#2   balan@23             1
    r#4#3#3   OBJECTIV           5.5
    r#4#3#3   init3_12             1
    r#4#3#3   balan@24             1
    r#5#1#0   init2_13             1
    r#5#1#0   balan@25            -1
    r#5#1#1   OBJECTIV             5
    r#5#1#1   balan@26            -1
    r#5#1#1   balan@25             1
    r#5#1#2   OBJECTIV             5
    r#5#1#2   balan@27            -1
    r#5#1#2   balan@26             1
    r#5#1#3   OBJECTIV             5
    r#5#1#3   init3_13             1
    r#5#1#3   balan@27             1
    r#5#2#0   init2_14             1
    r#5#2#0   balan@28            -1
    r#5#2#1   OBJECTIV           5.5
    r#5#2#1   balan@29            -1
    r#5#2#1   balan@28             1
    r#5#2#2   OBJECTIV           5.5
    r#5#2#2   balan@2a            -1
    r#5#2#2   balan@29             1
    r#5#2#3   OBJECTIV           5.5
    r#5#2#3   init3_14             1
    r#5#2#3   balan@2a             1
    r#5#3#0   init2_15             1
    r#5#3#0   balan@2b            -1
    r#5#3#1   OBJECTIV           5.5
    r#5#3#1   balan@2c            -1
    r#5#3#1   balan@2b             1
    r#5#3#2   OBJECTIV           5.5
    r#5#3#2   balan@2d            -1
    r#5#3#2   balan@2c             1
    r#5#3#3   OBJECTIV           5.5
    r#5#3#3   init3_15             1
    r#5#3#3   balan@2d             1
    r#6#1#0   init2_16             1
    r#6#1#0   balan@2e            -1
    r#6#1#1   OBJECTIV             5
    r#6#1#1   balan@2f            -1
    r#6#1#1   balan@2e             1
    r#6#1#2   OBJECTIV             5
    r#6#1#2   balan@30            -1
    r#6#1#2   balan@2f             1
    r#6#1#3   OBJECTIV             5
    r#6#1#3   init3_16             1
    r#6#1#3   balan@30             1
    r#6#2#0   init2_17             1
    r#6#2#0   balan@31            -1
    r#6#2#1   OBJECTIV           5.5
    r#6#2#1   balan@32            -1
    r#6#2#1   balan@31             1
    r#6#2#2   OBJECTIV           5.5
    r#6#2#2   balan@33            -1
    r#6#2#2   balan@32             1
    r#6#2#3   OBJECTIV           5.5
    r#6#2#3   init3_17             1
    r#6#2#3   balan@33             1
    r#6#3#0   init2_18             1
    r#6#3#0   balan@34            -1
    r#6#3#1   OBJECTIV           5.5
    r#6#3#1   balan@35            -1
    r#6#3#1   balan@34             1
    r#6#3#2   OBJECTIV           5.5
    r#6#3#2   balan@36            -1
    r#6#3#2   balan@35             1
    r#6#3#3   OBJECTIV           5.5
    r#6#3#3   init3_18             1
    r#6#3#3   balan@36             1
    s#1#1#0   init1_1              1
    s#1#1#0   balanc@1             1
    s#1#1#1   OBJECTIV             1
    s#1#1#1   balanc@2             1
    s#1#1#1   balanc@1            -1
    s#1#1#2   OBJECTIV             1
    s#1#1#2   balanc@3             1
    s#1#1#2   balanc@2            -1
    s#1#1#3   OBJECTIV             1
    s#1#1#3   balanc@3            -1
    s#1#2#0   init1_2              1
    s#1#2#0   balanc@4             1
    s#1#2#1   OBJECTIV           1.1
    s#1#2#1   balanc@5             1
    s#1#2#1   balanc@4            -1
    s#1#2#2   OBJECTIV           1.1
    s#1#2#2   balanc@6             1
    s#1#2#2   balanc@5            -1
    s#1#2#3   OBJECTIV           1.1
    s#1#2#3   balanc@6            -1
    s#1#3#0   init1_3              1
    s#1#3#0   balanc@7             1
    s#1#3#1   OBJECTIV           1.1
    s#1#3#1   balanc@8             1
    s#1#3#1   balanc@7            -1
    s#1#3#2   OBJECTIV           1.1
    s#1#3#2   balanc@9             1
    s#1#3#2   balanc@8            -1
    s#1#3#3   OBJECTIV           1.1
    s#1#3#3   balanc@9            -1
    s#2#1#0   init1_4              1
    s#2#1#0   balanc@a             1
    s#2#1#1   OBJECTIV             1
    s#2#1#1   balanc@b             1
    s#2#1#1   balanc@a            -1
    s#2#1#2   OBJECTIV             1
    s#2#1#2   balanc@c             1
    s#2#1#2   balanc@b            -1
    s#2#1#3   OBJECTIV             1
    s#2#1#3   balanc@c            -1
    s#2#2#0   init1_5              1
    s#2#2#0   balanc@d             1
    s#2#2#1   OBJECTIV           1.1
    s#2#2#1   balanc@e             1
    s#2#2#1   balanc@d            -1
    s#2#2#2   OBJECTIV           1.1
    s#2#2#2   balanc@f             1
    s#2#2#2   balanc@e            -1
    s#2#2#3   OBJECTIV           1.1
    s#2#2#3   balanc@f            -1
    s#2#3#0   init1_6              1
    s#2#3#0   balan@10             1
    s#2#3#1   OBJECTIV           1.1
    s#2#3#1   balan@11             1
    s#2#3#1   balan@10            -1
    s#2#3#2   OBJECTIV           1.1
    s#2#3#2   balan@12             1
    s#2#3#2   balan@11            -1
    s#2#3#3   OBJECTIV           1.1
    s#2#3#3   balan@12            -1
    s#3#1#0   init1_7              1
    s#3#1#0   balan@13             1
    s#3#1#1   OBJECTIV             1
    s#3#1#1   balan@14             1
    s#3#1#1   balan@13            -1
    s#3#1#2   OBJECTIV             1
    s#3#1#2   balan@15             1
    s#3#1#2   balan@14            -1
    s#3#1#3   OBJECTIV             1
    s#3#1#3   balan@15            -1
    s#3#2#0   init1_8              1
    s#3#2#0   balan@16             1
    s#3#2#1   OBJECTIV           1.1
    s#3#2#1   balan@17             1
    s#3#2#1   balan@16            -1
    s#3#2#2   OBJECTIV           1.1
    s#3#2#2   balan@18             1
    s#3#2#2   balan@17            -1
    s#3#2#3   OBJECTIV           1.1
    s#3#2#3   balan@18            -1
    s#3#3#0   init1_9              1
    s#3#3#0   balan@19             1
    s#3#3#1   OBJECTIV           1.1
    s#3#3#1   balan@1a             1
    s#3#3#1   balan@19            -1
    s#3#3#2   OBJECTIV           1.1
    s#3#3#2   balan@1b             1
    s#3#3#2   balan@1a            -1
    s#3#3#3   OBJECTIV           1.1
    s#3#3#3   balan@1b            -1
    s#4#1#0   init1_10             1
    s#4#1#0   balan@1c             1
    s#4#1#1   OBJECTIV             1
    s#4#1#1   balan@1d             1
    s#4#1#1   balan@1c            -1
    s#4#1#2   OBJECTIV             1
    s#4#1#2   balan@1e             1
    s#4#1#2   balan@1d            -1
    s#4#1#3   OBJECTIV             1
    s#4#1#3   balan@1e            -1
    s#4#2#0   init1_11             1
    s#4#2#0   balan@1f             1
    s#4#2#1   OBJECTIV           1.1
    s#4#2#1   balan@20             1
    s#4#2#1   balan@1f            -1
    s#4#2#2   OBJECTIV           1.1
    s#4#2#2   balan@21             1
    s#4#2#2   balan@20            -1
    s#4#2#3   OBJECTIV           1.1
    s#4#2#3   balan@21            -1
    s#4#3#0   init1_12             1
    s#4#3#0   balan@22             1
    s#4#3#1   OBJECTIV           1.1
    s#4#3#1   balan@23             1
    s#4#3#1   balan@22            -1
    s#4#3#2   OBJECTIV           1.1
    s#4#3#2   balan@24             1
    s#4#3#2   balan@23            -1
    s#4#3#3   OBJECTIV           1.1
    s#4#3#3   balan@24            -1
    s#5#1#0   init1_13             1
    s#5#1#0   balan@25             1
    s#5#1#1   OBJECTIV             1
    s#5#1#1   balan@26             1
    s#5#1#1   balan@25            -1
    s#5#1#2   OBJECTIV             1
    s#5#1#2   balan@27             1
    s#5#1#2   balan@26            -1
    s#5#1#3   OBJECTIV             1
    s#5#1#3   balan@27            -1
    s#5#2#0   init1_14             1
    s#5#2#0   balan@28             1
    s#5#2#1   OBJECTIV           1.1
    s#5#2#1   balan@29             1
    s#5#2#1   balan@28            -1
    s#5#2#2   OBJECTIV           1.1
    s#5#2#2   balan@2a             1
    s#5#2#2   balan@29            -1
    s#5#2#3   OBJECTIV           1.1
    s#5#2#3   balan@2a            -1
    s#5#3#0   init1_15             1
    s#5#3#0   balan@2b             1
    s#5#3#1   OBJECTIV           1.1
    s#5#3#1   balan@2c             1
    s#5#3#1   balan@2b            -1
    s#5#3#2   OBJECTIV           1.1
    s#5#3#2   balan@2d             1
    s#5#3#2   balan@2c            -1
    s#5#3#3   OBJECTIV           1.1
    s#5#3#3   balan@2d            -1
    s#6#1#0   init1_16             1
    s#6#1#0   balan@2e             1
    s#6#1#1   OBJECTIV             1
    s#6#1#1   balan@2f             1
    s#6#1#1   balan@2e            -1
    s#6#1#2   OBJECTIV             1
    s#6#1#2   balan@30             1
    s#6#1#2   balan@2f            -1
    s#6#1#3   OBJECTIV             1
    s#6#1#3   balan@30            -1
    s#6#2#0   init1_17             1
    s#6#2#0   balan@31             1
    s#6#2#1   OBJECTIV           1.1
    s#6#2#1   balan@32             1
    s#6#2#1   balan@31            -1
    s#6#2#2   OBJECTIV           1.1
    s#6#2#2   balan@33             1
    s#6#2#2   balan@32            -1
    s#6#2#3   OBJECTIV           1.1
    s#6#2#3   balan@33            -1
    s#6#3#0   init1_18             1
    s#6#3#0   balan@34             1
    s#6#3#1   OBJECTIV           1.1
    s#6#3#1   balan@35             1
    s#6#3#1   balan@34            -1
    s#6#3#2   OBJECTIV           1.1
    s#6#3#2   balan@36             1
    s#6#3#2   balan@35            -1
    s#6#3#3   OBJECTIV           1.1
    s#6#3#3   balan@36            -1
RHS
    RHS       select_1             2
    RHS       balanc@1           964
    RHS       balanc@2            21
    RHS       balanc@3           337
    RHS       balanc@7           371
    RHS       balanc@8           573
    RHS       balanc@9           153
    RHS       balanc@a           333
    RHS       balanc@b           776
    RHS       balanc@c           466
    RHS       balanc@d           239
    RHS       balanc@e           425
    RHS       balanc@f           220
    RHS       balan@10           852
    RHS       balan@11            50
    RHS       balan@12           791
    RHS       balan@13           136
    RHS       balan@14           621
    RHS       balan@15           192
    RHS       balan@16             7
    RHS       balan@17            27
    RHS       balan@18           934
    RHS       balan@19          1000
    RHS       balan@1a           237
    RHS       balan@1b           292
    RHS       balan@1f           914
    RHS       balan@20           988
    RHS       balan@21           465
    RHS       balan@22           734
    RHS       balan@23           911
    RHS       balan@24            27
    RHS       balan@25           936
    RHS       balan@26           931
    RHS       balan@27           895
    RHS       balan@28           249
    RHS       balan@29           352
    RHS       balan@2a           188
    RHS       balan@2e           892
    RHS       balan@2f           869
    RHS       balan@30           833
    RHS       balan@31           956
    RHS       balan@32           226
    RHS       balan@33           725
    RHS       valid_1           1322
    RHS       valid_2           1097
    RHS       valid_3           1575
    RHS       valid_4            884
    RHS       valid_5           1693
    RHS       valid_6            949
    RHS       valid_7            968
    RHS       valid_8           1529
    RHS       valid_9           2367
    RHS       valid_10          1672
    RHS       valid_11          2762
    RHS       valid_12           789
    RHS       valid_13          2594
    RHS       valid_14          1907
BOUNDS
 LO BOUND     r#1#1#0              0
 PL BOUND     r#1#1#0 
 LO BOUND     r#1#1#1              0
 PL BOUND     r#1#1#1 
 LO BOUND     r#1#1#2              0
 PL BOUND     r#1#1#2 
 LO BOUND     r#1#1#3              0
 PL BOUND     r#1#1#3 
 LO BOUND     r#1#2#0              0
 PL BOUND     r#1#2#0 
 LO BOUND     r#1#2#1              0
 PL BOUND     r#1#2#1 
 LO BOUND     r#1#2#2              0
 PL BOUND     r#1#2#2 
 LO BOUND     r#1#2#3              0
 PL BOUND     r#1#2#3 
 LO BOUND     r#1#3#0              0
 PL BOUND     r#1#3#0 
 LO BOUND     r#1#3#1              0
 PL BOUND     r#1#3#1 
 LO BOUND     r#1#3#2              0
 PL BOUND     r#1#3#2 
 LO BOUND     r#1#3#3              0
 PL BOUND     r#1#3#3 
 LO BOUND     r#2#1#0              0
 PL BOUND     r#2#1#0 
 LO BOUND     r#2#1#1              0
 PL BOUND     r#2#1#1 
 LO BOUND     r#2#1#2              0
 PL BOUND     r#2#1#2 
 LO BOUND     r#2#1#3              0
 PL BOUND     r#2#1#3 
 LO BOUND     r#2#2#0              0
 PL BOUND     r#2#2#0 
 LO BOUND     r#2#2#1              0
 PL BOUND     r#2#2#1 
 LO BOUND     r#2#2#2              0
 PL BOUND     r#2#2#2 
 LO BOUND     r#2#2#3              0
 PL BOUND     r#2#2#3 
 LO BOUND     r#2#3#0              0
 PL BOUND     r#2#3#0 
 LO BOUND     r#2#3#1              0
 PL BOUND     r#2#3#1 
 LO BOUND     r#2#3#2              0
 PL BOUND     r#2#3#2 
 LO BOUND     r#2#3#3              0
 PL BOUND     r#2#3#3 
 LO BOUND     r#3#1#0              0
 PL BOUND     r#3#1#0 
 LO BOUND     r#3#1#1              0
 PL BOUND     r#3#1#1 
 LO BOUND     r#3#1#2              0
 PL BOUND     r#3#1#2 
 LO BOUND     r#3#1#3              0
 PL BOUND     r#3#1#3 
 LO BOUND     r#3#2#0              0
 PL BOUND     r#3#2#0 
 LO BOUND     r#3#2#1              0
 PL BOUND     r#3#2#1 
 LO BOUND     r#3#2#2              0
 PL BOUND     r#3#2#2 
 LO BOUND     r#3#2#3              0
 PL BOUND     r#3#2#3 
 LO BOUND     r#3#3#0              0
 PL BOUND     r#3#3#0 
 LO BOUND     r#3#3#1              0
 PL BOUND     r#3#3#1 
 LO BOUND     r#3#3#2              0
 PL BOUND     r#3#3#2 
 LO BOUND     r#3#3#3              0
 PL BOUND     r#3#3#3 
 LO BOUND     r#4#1#0              0
 PL BOUND     r#4#1#0 
 LO BOUND     r#4#1#1              0
 PL BOUND     r#4#1#1 
 LO BOUND     r#4#1#2              0
 PL BOUND     r#4#1#2 
 LO BOUND     r#4#1#3              0
 PL BOUND     r#4#1#3 
 LO BOUND     r#4#2#0              0
 PL BOUND     r#4#2#0 
 LO BOUND     r#4#2#1              0
 PL BOUND     r#4#2#1 
 LO BOUND     r#4#2#2              0
 PL BOUND     r#4#2#2 
 LO BOUND     r#4#2#3              0
 PL BOUND     r#4#2#3 
 LO BOUND     r#4#3#0              0
 PL BOUND     r#4#3#0 
 LO BOUND     r#4#3#1              0
 PL BOUND     r#4#3#1 
 LO BOUND     r#4#3#2              0
 PL BOUND     r#4#3#2 
 LO BOUND     r#4#3#3              0
 PL BOUND     r#4#3#3 
 LO BOUND     r#5#1#0              0
 PL BOUND     r#5#1#0 
 LO BOUND     r#5#1#1              0
 PL BOUND     r#5#1#1 
 LO BOUND     r#5#1#2              0
 PL BOUND     r#5#1#2 
 LO BOUND     r#5#1#3              0
 PL BOUND     r#5#1#3 
 LO BOUND     r#5#2#0              0
 PL BOUND     r#5#2#0 
 LO BOUND     r#5#2#1              0
 PL BOUND     r#5#2#1 
 LO BOUND     r#5#2#2              0
 PL BOUND     r#5#2#2 
 LO BOUND     r#5#2#3              0
 PL BOUND     r#5#2#3 
 LO BOUND     r#5#3#0              0
 PL BOUND     r#5#3#0 
 LO BOUND     r#5#3#1              0
 PL BOUND     r#5#3#1 
 LO BOUND     r#5#3#2              0
 PL BOUND     r#5#3#2 
 LO BOUND     r#5#3#3              0
 PL BOUND     r#5#3#3 
 LO BOUND     r#6#1#0              0
 PL BOUND     r#6#1#0 
 LO BOUND     r#6#1#1              0
 PL BOUND     r#6#1#1 
 LO BOUND     r#6#1#2              0
 PL BOUND     r#6#1#2 
 LO BOUND     r#6#1#3              0
 PL BOUND     r#6#1#3 
 LO BOUND     r#6#2#0              0
 PL BOUND     r#6#2#0 
 LO BOUND     r#6#2#1              0
 PL BOUND     r#6#2#1 
 LO BOUND     r#6#2#2              0
 PL BOUND     r#6#2#2 
 LO BOUND     r#6#2#3              0
 PL BOUND     r#6#2#3 
 LO BOUND     r#6#3#0              0
 PL BOUND     r#6#3#0 
 LO BOUND     r#6#3#1              0
 PL BOUND     r#6#3#1 
 LO BOUND     r#6#3#2              0
 PL BOUND     r#6#3#2 
 LO BOUND     r#6#3#3              0
 PL BOUND     r#6#3#3 
 LO BOUND     s#1#1#0              0
 PL BOUND     s#1#1#0 
 LO BOUND     s#1#1#1              0
 PL BOUND     s#1#1#1 
 LO BOUND     s#1#1#2              0
 PL BOUND     s#1#1#2 
 LO BOUND     s#1#1#3              0
 PL BOUND     s#1#1#3 
 LO BOUND     s#1#2#0              0
 PL BOUND     s#1#2#0 
 LO BOUND     s#1#2#1              0
 PL BOUND     s#1#2#1 
 LO BOUND     s#1#2#2              0
 PL BOUND     s#1#2#2 
 LO BOUND     s#1#2#3              0
 PL BOUND     s#1#2#3 
 LO BOUND     s#1#3#0              0
 PL BOUND     s#1#3#0 
 LO BOUND     s#1#3#1              0
 PL BOUND     s#1#3#1 
 LO BOUND     s#1#3#2              0
 PL BOUND     s#1#3#2 
 LO BOUND     s#1#3#3              0
 PL BOUND     s#1#3#3 
 LO BOUND     s#2#1#0              0
 PL BOUND     s#2#1#0 
 LO BOUND     s#2#1#1              0
 PL BOUND     s#2#1#1 
 LO BOUND     s#2#1#2              0
 PL BOUND     s#2#1#2 
 LO BOUND     s#2#1#3              0
 PL BOUND     s#2#1#3 
 LO BOUND     s#2#2#0              0
 PL BOUND     s#2#2#0 
 LO BOUND     s#2#2#1              0
 PL BOUND     s#2#2#1 
 LO BOUND     s#2#2#2              0
 PL BOUND     s#2#2#2 
 LO BOUND     s#2#2#3              0
 PL BOUND     s#2#2#3 
 LO BOUND     s#2#3#0              0
 PL BOUND     s#2#3#0 
 LO BOUND     s#2#3#1              0
 PL BOUND     s#2#3#1 
 LO BOUND     s#2#3#2              0
 PL BOUND     s#2#3#2 
 LO BOUND     s#2#3#3              0
 PL BOUND     s#2#3#3 
 LO BOUND     s#3#1#0              0
 PL BOUND     s#3#1#0 
 LO BOUND     s#3#1#1              0
 PL BOUND     s#3#1#1 
 LO BOUND     s#3#1#2              0
 PL BOUND     s#3#1#2 
 LO BOUND     s#3#1#3              0
 PL BOUND     s#3#1#3 
 LO BOUND     s#3#2#0              0
 PL BOUND     s#3#2#0 
 LO BOUND     s#3#2#1              0
 PL BOUND     s#3#2#1 
 LO BOUND     s#3#2#2              0
 PL BOUND     s#3#2#2 
 LO BOUND     s#3#2#3              0
 PL BOUND     s#3#2#3 
 LO BOUND     s#3#3#0              0
 PL BOUND     s#3#3#0 
 LO BOUND     s#3#3#1              0
 PL BOUND     s#3#3#1 
 LO BOUND     s#3#3#2              0
 PL BOUND     s#3#3#2 
 LO BOUND     s#3#3#3              0
 PL BOUND     s#3#3#3 
 LO BOUND     s#4#1#0              0
 PL BOUND     s#4#1#0 
 LO BOUND     s#4#1#1              0
 PL BOUND     s#4#1#1 
 LO BOUND     s#4#1#2              0
 PL BOUND     s#4#1#2 
 LO BOUND     s#4#1#3              0
 PL BOUND     s#4#1#3 
 LO BOUND     s#4#2#0              0
 PL BOUND     s#4#2#0 
 LO BOUND     s#4#2#1              0
 PL BOUND     s#4#2#1 
 LO BOUND     s#4#2#2              0
 PL BOUND     s#4#2#2 
 LO BOUND     s#4#2#3              0
 PL BOUND     s#4#2#3 
 LO BOUND     s#4#3#0              0
 PL BOUND     s#4#3#0 
 LO BOUND     s#4#3#1              0
 PL BOUND     s#4#3#1 
 LO BOUND     s#4#3#2              0
 PL BOUND     s#4#3#2 
 LO BOUND     s#4#3#3              0
 PL BOUND     s#4#3#3 
 LO BOUND     s#5#1#0              0
 PL BOUND     s#5#1#0 
 LO BOUND     s#5#1#1              0
 PL BOUND     s#5#1#1 
 LO BOUND     s#5#1#2              0
 PL BOUND     s#5#1#2 
 LO BOUND     s#5#1#3              0
 PL BOUND     s#5#1#3 
 LO BOUND     s#5#2#0              0
 PL BOUND     s#5#2#0 
 LO BOUND     s#5#2#1              0
 PL BOUND     s#5#2#1 
 LO BOUND     s#5#2#2              0
 PL BOUND     s#5#2#2 
 LO BOUND     s#5#2#3              0
 PL BOUND     s#5#2#3 
 LO BOUND     s#5#3#0              0
 PL BOUND     s#5#3#0 
 LO BOUND     s#5#3#1              0
 PL BOUND     s#5#3#1 
 LO BOUND     s#5#3#2              0
 PL BOUND     s#5#3#2 
 LO BOUND     s#5#3#3              0
 PL BOUND     s#5#3#3 
 LO BOUND     s#6#1#0              0
 PL BOUND     s#6#1#0 
 LO BOUND     s#6#1#1              0
 PL BOUND     s#6#1#1 
 LO BOUND     s#6#1#2              0
 PL BOUND     s#6#1#2 
 LO BOUND     s#6#1#3              0
 PL BOUND     s#6#1#3 
 LO BOUND     s#6#2#0              0
 PL BOUND     s#6#2#0 
 LO BOUND     s#6#2#1              0
 PL BOUND     s#6#2#1 
 LO BOUND     s#6#2#2              0
 PL BOUND     s#6#2#2 
 LO BOUND     s#6#2#3              0
 PL BOUND     s#6#2#3 
 LO BOUND     s#6#3#0              0
 PL BOUND     s#6#3#0 
 LO BOUND     s#6#3#1              0
 PL BOUND     s#6#3#1 
 LO BOUND     s#6#3#2              0
 PL BOUND     s#6#3#2 
 LO BOUND     s#6#3#3              0
 PL BOUND     s#6#3#3 
 LO BOUND     x#1#1#1              0
 PL BOUND     x#1#1#1 
 LO BOUND     x#1#1#2              0
 PL BOUND     x#1#1#2 
 LO BOUND     x#1#1#3              0
 PL BOUND     x#1#1#3 
 LO BOUND     x#1#2#1              0
 PL BOUND     x#1#2#1 
 LO BOUND     x#1#2#2              0
 PL BOUND     x#1#2#2 
 LO BOUND     x#1#2#3              0
 PL BOUND     x#1#2#3 
 LO BOUND     x#1#3#1              0
 PL BOUND     x#1#3#1 
 LO BOUND     x#1#3#2              0
 PL BOUND     x#1#3#2 
 LO BOUND     x#1#3#3              0
 PL BOUND     x#1#3#3 
 LO BOUND     x#2#1#1              0
 PL BOUND     x#2#1#1 
 LO BOUND     x#2#1#2              0
 PL BOUND     x#2#1#2 
 LO BOUND     x#2#1#3              0
 PL BOUND     x#2#1#3 
 LO BOUND     x#2#2#1              0
 PL BOUND     x#2#2#1 
 LO BOUND     x#2#2#2              0
 PL BOUND     x#2#2#2 
 LO BOUND     x#2#2#3              0
 PL BOUND     x#2#2#3 
 LO BOUND     x#2#3#1              0
 PL BOUND     x#2#3#1 
 LO BOUND     x#2#3#2              0
 PL BOUND     x#2#3#2 
 LO BOUND     x#2#3#3              0
 PL BOUND     x#2#3#3 
 LO BOUND     x#3#1#1              0
 PL BOUND     x#3#1#1 
 LO BOUND     x#3#1#2              0
 PL BOUND     x#3#1#2 
 LO BOUND     x#3#1#3              0
 PL BOUND     x#3#1#3 
 LO BOUND     x#3#2#1              0
 PL BOUND     x#3#2#1 
 LO BOUND     x#3#2#2              0
 PL BOUND     x#3#2#2 
 LO BOUND     x#3#2#3              0
 PL BOUND     x#3#2#3 
 LO BOUND     x#3#3#1              0
 PL BOUND     x#3#3#1 
 LO BOUND     x#3#3#2              0
 PL BOUND     x#3#3#2 
 LO BOUND     x#3#3#3              0
 PL BOUND     x#3#3#3 
 LO BOUND     x#4#1#1              0
 PL BOUND     x#4#1#1 
 LO BOUND     x#4#1#2              0
 PL BOUND     x#4#1#2 
 LO BOUND     x#4#1#3              0
 PL BOUND     x#4#1#3 
 LO BOUND     x#4#2#1              0
 PL BOUND     x#4#2#1 
 LO BOUND     x#4#2#2              0
 PL BOUND     x#4#2#2 
 LO BOUND     x#4#2#3              0
 PL BOUND     x#4#2#3 
 LO BOUND     x#4#3#1              0
 PL BOUND     x#4#3#1 
 LO BOUND     x#4#3#2              0
 PL BOUND     x#4#3#2 
 LO BOUND     x#4#3#3              0
 PL BOUND     x#4#3#3 
 LO BOUND     x#5#1#1              0
 PL BOUND     x#5#1#1 
 LO BOUND     x#5#1#2              0
 PL BOUND     x#5#1#2 
 LO BOUND     x#5#1#3              0
 PL BOUND     x#5#1#3 
 LO BOUND     x#5#2#1              0
 PL BOUND     x#5#2#1 
 LO BOUND     x#5#2#2              0
 PL BOUND     x#5#2#2 
 LO BOUND     x#5#2#3              0
 PL BOUND     x#5#2#3 
 LO BOUND     x#5#3#1              0
 PL BOUND     x#5#3#1 
 LO BOUND     x#5#3#2              0
 PL BOUND     x#5#3#2 
 LO BOUND     x#5#3#3              0
 PL BOUND     x#5#3#3 
 LO BOUND     x#6#1#1              0
 PL BOUND     x#6#1#1 
 LO BOUND     x#6#1#2              0
 PL BOUND     x#6#1#2 
 LO BOUND     x#6#1#3              0
 PL BOUND     x#6#1#3 
 LO BOUND     x#6#2#1              0
 PL BOUND     x#6#2#1 
 LO BOUND     x#6#2#2              0
 PL BOUND     x#6#2#2 
 LO BOUND     x#6#2#3              0
 PL BOUND     x#6#2#3 
 LO BOUND     x#6#3#1              0
 PL BOUND     x#6#3#1 
 LO BOUND     x#6#3#2              0
 PL BOUND     x#6#3#2 
 LO BOUND     x#6#3#3              0
 PL BOUND     x#6#3#3 
 LO BOUND     y#1#1#1              0
 PL BOUND     y#1#1#1 
 LO BOUND     y#1#1#2              0
 PL BOUND     y#1#1#2 
 LO BOUND     y#1#1#3              0
 PL BOUND     y#1#1#3 
 LO BOUND     y#1#2#1              0
 PL BOUND     y#1#2#1 
 LO BOUND     y#1#2#2              0
 PL BOUND     y#1#2#2 
 LO BOUND     y#1#2#3              0
 PL BOUND     y#1#2#3 
 LO BOUND     y#1#3#1              0
 PL BOUND     y#1#3#1 
 LO BOUND     y#1#3#2              0
 PL BOUND     y#1#3#2 
 LO BOUND     y#1#3#3              0
 PL BOUND     y#1#3#3 
 LO BOUND     y#1#4#1              0
 PL BOUND     y#1#4#1 
 LO BOUND     y#1#4#2              0
 PL BOUND     y#1#4#2 
 LO BOUND     y#1#4#3              0
 PL BOUND     y#1#4#3 
 LO BOUND     y#1#5#1              0
 PL BOUND     y#1#5#1 
 LO BOUND     y#1#5#2              0
 PL BOUND     y#1#5#2 
 LO BOUND     y#1#5#3              0
 PL BOUND     y#1#5#3 
 LO BOUND     y#1#6#1              0
 PL BOUND     y#1#6#1 
 LO BOUND     y#1#6#2              0
 PL BOUND     y#1#6#2 
 LO BOUND     y#1#6#3              0
 PL BOUND     y#1#6#3 
 LO BOUND     y#1#7#1              0
 PL BOUND     y#1#7#1 
 LO BOUND     y#1#7#2              0
 PL BOUND     y#1#7#2 
 LO BOUND     y#1#7#3              0
 PL BOUND     y#1#7#3 
 LO BOUND     y#2#1#1              0
 PL BOUND     y#2#1#1 
 LO BOUND     y#2#1#2              0
 PL BOUND     y#2#1#2 
 LO BOUND     y#2#1#3              0
 PL BOUND     y#2#1#3 
 LO BOUND     y#2#2#1              0
 PL BOUND     y#2#2#1 
 LO BOUND     y#2#2#2              0
 PL BOUND     y#2#2#2 
 LO BOUND     y#2#2#3              0
 PL BOUND     y#2#2#3 
 LO BOUND     y#2#3#1              0
 PL BOUND     y#2#3#1 
 LO BOUND     y#2#3#2              0
 PL BOUND     y#2#3#2 
 LO BOUND     y#2#3#3              0
 PL BOUND     y#2#3#3 
 LO BOUND     y#2#4#1              0
 PL BOUND     y#2#4#1 
 LO BOUND     y#2#4#2              0
 PL BOUND     y#2#4#2 
 LO BOUND     y#2#4#3              0
 PL BOUND     y#2#4#3 
 LO BOUND     y#2#5#1              0
 PL BOUND     y#2#5#1 
 LO BOUND     y#2#5#2              0
 PL BOUND     y#2#5#2 
 LO BOUND     y#2#5#3              0
 PL BOUND     y#2#5#3 
 LO BOUND     y#2#6#1              0
 PL BOUND     y#2#6#1 
 LO BOUND     y#2#6#2              0
 PL BOUND     y#2#6#2 
 LO BOUND     y#2#6#3              0
 PL BOUND     y#2#6#3 
 LO BOUND     y#2#7#1              0
 PL BOUND     y#2#7#1 
 LO BOUND     y#2#7#2              0
 PL BOUND     y#2#7#2 
 LO BOUND     y#2#7#3              0
 PL BOUND     y#2#7#3 
 LO BOUND     y#3#1#1              0
 PL BOUND     y#3#1#1 
 LO BOUND     y#3#1#2              0
 PL BOUND     y#3#1#2 
 LO BOUND     y#3#1#3              0
 PL BOUND     y#3#1#3 
 LO BOUND     y#3#2#1              0
 PL BOUND     y#3#2#1 
 LO BOUND     y#3#2#2              0
 PL BOUND     y#3#2#2 
 LO BOUND     y#3#2#3              0
 PL BOUND     y#3#2#3 
 LO BOUND     y#3#3#1              0
 PL BOUND     y#3#3#1 
 LO BOUND     y#3#3#2              0
 PL BOUND     y#3#3#2 
 LO BOUND     y#3#3#3              0
 PL BOUND     y#3#3#3 
 LO BOUND     y#3#4#1              0
 PL BOUND     y#3#4#1 
 LO BOUND     y#3#4#2              0
 PL BOUND     y#3#4#2 
 LO BOUND     y#3#4#3              0
 PL BOUND     y#3#4#3 
 LO BOUND     y#3#5#1              0
 PL BOUND     y#3#5#1 
 LO BOUND     y#3#5#2              0
 PL BOUND     y#3#5#2 
 LO BOUND     y#3#5#3              0
 PL BOUND     y#3#5#3 
 LO BOUND     y#3#6#1              0
 PL BOUND     y#3#6#1 
 LO BOUND     y#3#6#2              0
 PL BOUND     y#3#6#2 
 LO BOUND     y#3#6#3              0
 PL BOUND     y#3#6#3 
 LO BOUND     y#3#7#1              0
 PL BOUND     y#3#7#1 
 LO BOUND     y#3#7#2              0
 PL BOUND     y#3#7#2 
 LO BOUND     y#3#7#3              0
 PL BOUND     y#3#7#3 
 LO BOUND     y#4#1#1              0
 PL BOUND     y#4#1#1 
 LO BOUND     y#4#1#2              0
 PL BOUND     y#4#1#2 
 LO BOUND     y#4#1#3              0
 PL BOUND     y#4#1#3 
 LO BOUND     y#4#2#1              0
 PL BOUND     y#4#2#1 
 LO BOUND     y#4#2#2              0
 PL BOUND     y#4#2#2 
 LO BOUND     y#4#2#3              0
 PL BOUND     y#4#2#3 
 LO BOUND     y#4#3#1              0
 PL BOUND     y#4#3#1 
 LO BOUND     y#4#3#2              0
 PL BOUND     y#4#3#2 
 LO BOUND     y#4#3#3              0
 PL BOUND     y#4#3#3 
 LO BOUND     y#4#4#1              0
 PL BOUND     y#4#4#1 
 LO BOUND     y#4#4#2              0
 PL BOUND     y#4#4#2 
 LO BOUND     y#4#4#3              0
 PL BOUND     y#4#4#3 
 LO BOUND     y#4#5#1              0
 PL BOUND     y#4#5#1 
 LO BOUND     y#4#5#2              0
 PL BOUND     y#4#5#2 
 LO BOUND     y#4#5#3              0
 PL BOUND     y#4#5#3 
 LO BOUND     y#4#6#1              0
 PL BOUND     y#4#6#1 
 LO BOUND     y#4#6#2              0
 PL BOUND     y#4#6#2 
 LO BOUND     y#4#6#3              0
 PL BOUND     y#4#6#3 
 LO BOUND     y#4#7#1              0
 PL BOUND     y#4#7#1 
 LO BOUND     y#4#7#2              0
 PL BOUND     y#4#7#2 
 LO BOUND     y#4#7#3              0
 PL BOUND     y#4#7#3 
 LO BOUND     y#5#1#1              0
 PL BOUND     y#5#1#1 
 LO BOUND     y#5#1#2              0
 PL BOUND     y#5#1#2 
 LO BOUND     y#5#1#3              0
 PL BOUND     y#5#1#3 
 LO BOUND     y#5#2#1              0
 PL BOUND     y#5#2#1 
 LO BOUND     y#5#2#2              0
 PL BOUND     y#5#2#2 
 LO BOUND     y#5#2#3              0
 PL BOUND     y#5#2#3 
 LO BOUND     y#5#3#1              0
 PL BOUND     y#5#3#1 
 LO BOUND     y#5#3#2              0
 PL BOUND     y#5#3#2 
 LO BOUND     y#5#3#3              0
 PL BOUND     y#5#3#3 
 LO BOUND     y#5#4#1              0
 PL BOUND     y#5#4#1 
 LO BOUND     y#5#4#2              0
 PL BOUND     y#5#4#2 
 LO BOUND     y#5#4#3              0
 PL BOUND     y#5#4#3 
 LO BOUND     y#5#5#1              0
 PL BOUND     y#5#5#1 
 LO BOUND     y#5#5#2              0
 PL BOUND     y#5#5#2 
 LO BOUND     y#5#5#3              0
 PL BOUND     y#5#5#3 
 LO BOUND     y#5#6#1              0
 PL BOUND     y#5#6#1 
 LO BOUND     y#5#6#2              0
 PL BOUND     y#5#6#2 
 LO BOUND     y#5#6#3              0
 PL BOUND     y#5#6#3 
 LO BOUND     y#5#7#1              0
 PL BOUND     y#5#7#1 
 LO BOUND     y#5#7#2              0
 PL BOUND     y#5#7#2 
 LO BOUND     y#5#7#3              0
 PL BOUND     y#5#7#3 
 LO BOUND     y#6#1#1              0
 PL BOUND     y#6#1#1 
 LO BOUND     y#6#1#2              0
 PL BOUND     y#6#1#2 
 LO BOUND     y#6#1#3              0
 PL BOUND     y#6#1#3 
 LO BOUND     y#6#2#1              0
 PL BOUND     y#6#2#1 
 LO BOUND     y#6#2#2              0
 PL BOUND     y#6#2#2 
 LO BOUND     y#6#2#3              0
 PL BOUND     y#6#2#3 
 LO BOUND     y#6#3#1              0
 PL BOUND     y#6#3#1 
 LO BOUND     y#6#3#2              0
 PL BOUND     y#6#3#2 
 LO BOUND     y#6#3#3              0
 PL BOUND     y#6#3#3 
 LO BOUND     y#6#4#1              0
 PL BOUND     y#6#4#1 
 LO BOUND     y#6#4#2              0
 PL BOUND     y#6#4#2 
 LO BOUND     y#6#4#3              0
 PL BOUND     y#6#4#3 
 LO BOUND     y#6#5#1              0
 PL BOUND     y#6#5#1 
 LO BOUND     y#6#5#2              0
 PL BOUND     y#6#5#2 
 LO BOUND     y#6#5#3              0
 PL BOUND     y#6#5#3 
 LO BOUND     y#6#6#1              0
 PL BOUND     y#6#6#1 
 LO BOUND     y#6#6#2              0
 PL BOUND     y#6#6#2 
 LO BOUND     y#6#6#3              0
 PL BOUND     y#6#6#3 
 LO BOUND     y#6#7#1              0
 PL BOUND     y#6#7#1 
 LO BOUND     y#6#7#2              0
 PL BOUND     y#6#7#2 
 LO BOUND     y#6#7#3              0
 PL BOUND     y#6#7#3 
 LO BOUND     z#1                  0
 UP BOUND     z#1                  1
 LO BOUND     z#2                  0
 UP BOUND     z#2                  1
 LO BOUND     z#3                  0
 UP BOUND     z#3                  1
 LO BOUND     z#4                  0
 UP BOUND     z#4                  1
 LO BOUND     z#5                  0
 UP BOUND     z#5                  1
 LO BOUND     z#6                  0
 UP BOUND     z#6                  1
 LO BOUND     z#7                  0
 UP BOUND     z#7                  1
ENDATA
