* This file was automatically generated by Zimpl
* param Q2 := 1;
* do print file2;
* param nC := read file1 as "1n" use 1;
* param nI := read file1 as "2n" use 1;
* param m  := read file1 as "3n" use 1;
* param nT := read file1 as "4n" use 1;
* param nP := read file2 as "1n" use 1;
* set C := { 1 .. nC };
* set I := { 1 .. nI };
* set T0 := { 0 .. nT };
* set T := { 1 .. nT };
* set P := { 1 .. nP };
* param inveCost[I] := read file1 as "<1n> 2n" skip 1 use nI;
* param backCost[I] := read file1 as "<1n> 2n" skip nI+1 use nI;
* param demand[C*I*T] := read file1 as "<1n,2n,3n> 4n" skip 2*nI+1;
* param q[P*I] := read file2 as "<1n,2n> 3n" skip 1;
* param D[<c,i> in C*I] := ceil( sum <t> in T : demand[c,i,t]/Q2 );
* set Pc[<c> in C] := inter <i> in { <i> in I with ( sum <t> in T : demand[c,i,t] ) > 0 } : { <p> in P with q[p,i] > 0 };
* param M[<c,p> in C*P] := max <i> in I with q[p,i] > 0: ceil( sum <t> in T : demand[c,i,t]/Q2/q[p,i] );
* var r[C*I*T0] >= 0;
* var s[C*I*T0] >= 0;
* var x[C*I*T] integer >= 0;
* var y[C*P*T] integer >= 0;
* var z[P] binary;
* minimize cost: sum <i> in I: ( sum <t> in T: (sum <c> in C : (inveCost[i] * s[c,i,t]  + backCost[i] * r[c,i,t]) ));
* subto select:       sum <p> in P: z[p] <= m;
* subto balance:    forall <c,i,t> in C*I*T with t>=1 do       s[c,i,t-1] - r[c,i,t-1] + Q1*Q2*x[c,i,t] + Q2 * (sum <p> in Pc[c
* ]: q[p,i] * y[c,p,t]) == demand[c,i,t] + s[c,i,t] - r[c,i,t];
* subto valid:    forall <c,i> in C*I do       sum <t> in T: ( min(Q1, D[c,i]) * x[c,i,t] + sum <p> in Pc[c]: ( min(q[p,i], D[c
* ,i] ) * y[c,p,t]) ) >= D[c,i];
* subto BigM:    forall <c,p,t> in C*P*T with t>=1 do       y[c,p,t] <= M[c,p] * z[p];
* subto init1:    forall <c,i> in C*I do       s[c,i,0] == 0;
* subto init2:    forall <c,i> in C*I do       r[c,i,0] == 0;
* subto init3:    forall <c,i> in C*I do       r[c,i,nT] == 0;
NAME          mpdp.zpl
ROWS
 N  OBJECTIV          
 L  select_1          
 E  balanc@1          
 E  balanc@2          
 E  balanc@3          
 E  balanc@4          
 E  balanc@5          
 E  balanc@6          
 E  balanc@7          
 E  balanc@8          
 E  balanc@9          
 E  balanc@a          
 E  balanc@b          
 E  balanc@c          
 E  balanc@d          
 E  balanc@e          
 E  balanc@f          
 E  balan@10          
 E  balan@11          
 E  balan@12          
 E  balan@13          
 E  balan@14          
 E  balan@15          
 E  balan@16          
 E  balan@17          
 E  balan@18          
 E  balan@19          
 E  balan@1a          
 E  balan@1b          
 E  balan@1c          
 E  balan@1d          
 E  balan@1e          
 E  balan@1f          
 E  balan@20          
 E  balan@21          
 E  balan@22          
 E  balan@23          
 E  balan@24          
 E  balan@25          
 E  balan@26          
 E  balan@27          
 E  balan@28          
 E  balan@29          
 E  balan@2a          
 E  balan@2b          
 E  balan@2c          
 E  balan@2d          
 E  balan@2e          
 E  balan@2f          
 E  balan@30          
 G  valid_1           
 G  valid_2           
 G  valid_3           
 G  valid_4           
 G  valid_5           
 G  valid_6           
 G  valid_7           
 G  valid_8           
 G  valid_9           
 G  valid_10          
 G  valid_11          
 G  valid_12          
 G  valid_13          
 L  BigM_1            
 L  BigM_2            
 L  BigM_3            
 L  BigM_4            
 L  BigM_5            
 L  BigM_6            
 L  BigM_7            
 L  BigM_8            
 L  BigM_9            
 L  BigM_10           
 L  BigM_11           
 L  BigM_12           
 L  BigM_13           
 L  BigM_14           
 L  BigM_15           
 L  BigM_16           
 L  BigM_17           
 L  BigM_18           
 L  BigM_19           
 L  BigM_20           
 L  BigM_21           
 L  BigM_22           
 L  BigM_23           
 L  BigM_24           
 L  BigM_25           
 L  BigM_26           
 L  BigM_27           
 L  BigM_28           
 L  BigM_29           
 L  BigM_30           
 L  BigM_31           
 L  BigM_32           
 L  BigM_33           
 L  BigM_34           
 L  BigM_35           
 L  BigM_36           
 L  BigM_37           
 L  BigM_38           
 L  BigM_39           
 L  BigM_40           
 L  BigM_41           
 L  BigM_42           
 L  BigM_43           
 L  BigM_44           
 L  BigM_45           
 L  BigM_46           
 L  BigM_47           
 L  BigM_48           
 L  BigM_49           
 L  BigM_50           
 L  BigM_51           
 L  BigM_52           
 L  BigM_53           
 L  BigM_54           
 L  BigM_55           
 L  BigM_56           
 L  BigM_57           
 L  BigM_58           
 L  BigM_59           
 L  BigM_60           
 L  BigM_61           
 L  BigM_62           
 L  BigM_63           
 L  BigM_64           
 L  BigM_65           
 L  BigM_66           
 L  BigM_67           
 L  BigM_68           
 L  BigM_69           
 L  BigM_70           
 L  BigM_71           
 L  BigM_72           
 L  BigM_73           
 L  BigM_74           
 L  BigM_75           
 L  BigM_76           
 L  BigM_77           
 L  BigM_78           
 L  BigM_79           
 L  BigM_80           
 L  BigM_81           
 L  BigM_82           
 L  BigM_83           
 L  BigM_84           
 L  BigM_85           
 L  BigM_86           
 L  BigM_87           
 L  BigM_88           
 L  BigM_89           
 L  BigM_90           
 L  BigM_91           
 L  BigM_92           
 L  BigM_93           
 L  BigM_94           
 L  BigM_95           
 L  BigM_96           
 L  BigM_97           
 L  BigM_98           
 L  BigM_99           
 L  BigM_100          
 L  BigM_101          
 L  BigM_102          
 L  BigM_103          
 L  BigM_104          
 L  BigM_105          
 L  BigM_106          
 L  BigM_107          
 L  BigM_108          
 L  BigM_109          
 L  BigM_110          
 L  BigM_111          
 L  BigM_112          
 L  BigM_113          
 L  BigM_114          
 L  BigM_115          
 L  BigM_116          
 L  BigM_117          
 L  BigM_118          
 L  BigM_119          
 L  BigM_120          
 L  BigM_121          
 L  BigM_122          
 L  BigM_123          
 L  BigM_124          
 L  BigM_125          
 L  BigM_126          
 L  BigM_127          
 L  BigM_128          
 L  BigM_129          
 L  BigM_130          
 L  BigM_131          
 L  BigM_132          
 L  BigM_133          
 L  BigM_134          
 L  BigM_135          
 L  BigM_136          
 L  BigM_137          
 L  BigM_138          
 L  BigM_139          
 L  BigM_140          
 L  BigM_141          
 L  BigM_142          
 L  BigM_143          
 L  BigM_144          
 L  BigM_145          
 L  BigM_146          
 L  BigM_147          
 L  BigM_148          
 L  BigM_149          
 L  BigM_150          
 L  BigM_151          
 L  BigM_152          
 L  BigM_153          
 L  BigM_154          
 L  BigM_155          
 L  BigM_156          
 L  BigM_157          
 L  BigM_158          
 L  BigM_159          
 L  BigM_160          
 L  BigM_161          
 L  BigM_162          
 L  BigM_163          
 L  BigM_164          
 L  BigM_165          
 L  BigM_166          
 L  BigM_167          
 L  BigM_168          
 L  BigM_169          
 L  BigM_170          
 L  BigM_171          
 L  BigM_172          
 L  BigM_173          
 L  BigM_174          
 L  BigM_175          
 L  BigM_176          
 L  BigM_177          
 L  BigM_178          
 L  BigM_179          
 L  BigM_180          
 L  BigM_181          
 L  BigM_182          
 L  BigM_183          
 L  BigM_184          
 L  BigM_185          
 L  BigM_186          
 L  BigM_187          
 L  BigM_188          
 L  BigM_189          
 L  BigM_190          
 L  BigM_191          
 L  BigM_192          
 L  BigM_193          
 L  BigM_194          
 L  BigM_195          
 L  BigM_196          
 L  BigM_197          
 L  BigM_198          
 L  BigM_199          
 L  BigM_200          
 L  BigM_201          
 L  BigM_202          
 L  BigM_203          
 L  BigM_204          
 L  BigM_205          
 L  BigM_206          
 L  BigM_207          
 L  BigM_208          
 L  BigM_209          
 L  BigM_210          
 L  BigM_211          
 L  BigM_212          
 L  BigM_213          
 L  BigM_214          
 L  BigM_215          
 L  BigM_216          
 E  init1_1           
 E  init1_2           
 E  init1_3           
 E  init1_4           
 E  init1_5           
 E  init1_6           
 E  init1_7           
 E  init1_8           
 E  init1_9           
 E  init1_10          
 E  init1_11          
 E  init1_12          
 E  init1_13          
 E  init1_14          
 E  init1_15          
 E  init1_16          
 E  init2_1           
 E  init2_2           
 E  init2_3           
 E  init2_4           
 E  init2_5           
 E  init2_6           
 E  init2_7           
 E  init2_8           
 E  init2_9           
 E  init2_10          
 E  init2_11          
 E  init2_12          
 E  init2_13          
 E  init2_14          
 E  init2_15          
 E  init2_16          
 E  init3_1           
 E  init3_2           
 E  init3_3           
 E  init3_4           
 E  init3_5           
 E  init3_6           
 E  init3_7           
 E  init3_8           
 E  init3_9           
 E  init3_10          
 E  init3_11          
 E  init3_12          
 E  init3_13          
 E  init3_14          
 E  init3_15          
 E  init3_16          
COLUMNS
    MARK0000  'MARKER'                 'INTORG'
    x#1#1#1   valid_1             72
    x#1#1#1   balanc@1            72
    x#1#1#2   valid_1             72
    x#1#1#2   balanc@2            72
    x#1#1#3   valid_1             72
    x#1#1#3   balanc@3            72
    x#1#2#1   balanc@4            72
    x#1#2#2   balanc@5            72
    x#1#2#3   balanc@6            72
    x#2#1#1   valid_2             72
    x#2#1#1   balanc@7            72
    x#2#1#2   valid_2             72
    x#2#1#2   balanc@8            72
    x#2#1#3   valid_2             72
    x#2#1#3   balanc@9            72
    x#2#2#1   valid_3             72
    x#2#2#1   balanc@a            72
    x#2#2#2   valid_3             72
    x#2#2#2   balanc@b            72
    x#2#2#3   valid_3             72
    x#2#2#3   balanc@c            72
    x#3#1#1   valid_4             72
    x#3#1#1   balanc@d            72
    x#3#1#2   valid_4             72
    x#3#1#2   balanc@e            72
    x#3#1#3   valid_4             72
    x#3#1#3   balanc@f            72
    x#3#2#1   valid_5             72
    x#3#2#1   balan@10            72
    x#3#2#2   valid_5             72
    x#3#2#2   balan@11            72
    x#3#2#3   valid_5             72
    x#3#2#3   balan@12            72
    x#4#1#1   balan@13            72
    x#4#1#2   balan@14            72
    x#4#1#3   balan@15            72
    x#4#2#1   valid_6             72
    x#4#2#1   balan@16            72
    x#4#2#2   valid_6             72
    x#4#2#2   balan@17            72
    x#4#2#3   valid_6             72
    x#4#2#3   balan@18            72
    x#5#1#1   valid_7             72
    x#5#1#1   balan@19            72
    x#5#1#2   valid_7             72
    x#5#1#2   balan@1a            72
    x#5#1#3   valid_7             72
    x#5#1#3   balan@1b            72
    x#5#2#1   valid_8             72
    x#5#2#1   balan@1c            72
    x#5#2#2   valid_8             72
    x#5#2#2   balan@1d            72
    x#5#2#3   valid_8             72
    x#5#2#3   balan@1e            72
    x#6#1#1   valid_9             72
    x#6#1#1   balan@1f            72
    x#6#1#2   valid_9             72
    x#6#1#2   balan@20            72
    x#6#1#3   valid_9             72
    x#6#1#3   balan@21            72
    x#6#2#1   valid_10            72
    x#6#2#1   balan@22            72
    x#6#2#2   valid_10            72
    x#6#2#2   balan@23            72
    x#6#2#3   valid_10            72
    x#6#2#3   balan@24            72
    x#7#1#1   valid_11            72
    x#7#1#1   balan@25            72
    x#7#1#2   valid_11            72
    x#7#1#2   balan@26            72
    x#7#1#3   valid_11            72
    x#7#1#3   balan@27            72
    x#7#2#1   valid_12            72
    x#7#2#1   balan@28            72
    x#7#2#2   valid_12            72
    x#7#2#2   balan@29            72
    x#7#2#3   valid_12            72
    x#7#2#3   balan@2a            72
    x#8#1#1   balan@2b            72
    x#8#1#2   balan@2c            72
    x#8#1#3   balan@2d            72
    x#8#2#1   valid_13            72
    x#8#2#1   balan@2e            72
    x#8#2#2   valid_13            72
    x#8#2#2   balan@2f            72
    x#8#2#3   valid_13            72
    x#8#2#3   balan@30            72
    y#1#1#1   BigM_1               1
    y#1#1#1   valid_1             29
    y#1#1#1   balanc@4            43
    y#1#1#1   balanc@1            29
    y#1#1#2   BigM_2               1
    y#1#1#2   valid_1             29
    y#1#1#2   balanc@5            43
    y#1#1#2   balanc@2            29
    y#1#1#3   BigM_3               1
    y#1#1#3   valid_1             29
    y#1#1#3   balanc@6            43
    y#1#1#3   balanc@3            29
    y#1#2#1   BigM_4               1
    y#1#2#1   valid_1             15
    y#1#2#1   balanc@4            57
    y#1#2#1   balanc@1            15
    y#1#2#2   BigM_5               1
    y#1#2#2   valid_1             15
    y#1#2#2   balanc@5            57
    y#1#2#2   balanc@2            15
    y#1#2#3   BigM_6               1
    y#1#2#3   valid_1             15
    y#1#2#3   balanc@6            57
    y#1#2#3   balanc@3            15
    y#1#3#1   BigM_7               1
    y#1#3#1   valid_1             57
    y#1#3#1   balanc@4            15
    y#1#3#1   balanc@1            57
    y#1#3#2   BigM_8               1
    y#1#3#2   valid_1             57
    y#1#3#2   balanc@5            15
    y#1#3#2   balanc@2            57
    y#1#3#3   BigM_9               1
    y#1#3#3   valid_1             57
    y#1#3#3   balanc@6            15
    y#1#3#3   balanc@3            57
    y#1#4#1   BigM_10              1
    y#1#4#1   valid_1             63
    y#1#4#1   balanc@4             9
    y#1#4#1   balanc@1            63
    y#1#4#2   BigM_11              1
    y#1#4#2   valid_1             63
    y#1#4#2   balanc@5             9
    y#1#4#2   balanc@2            63
    y#1#4#3   BigM_12              1
    y#1#4#3   valid_1             63
    y#1#4#3   balanc@6             9
    y#1#4#3   balanc@3            63
    y#1#5#1   BigM_13              1
    y#1#5#1   valid_1             50
    y#1#5#1   balanc@4            22
    y#1#5#1   balanc@1            50
    y#1#5#2   BigM_14              1
    y#1#5#2   valid_1             50
    y#1#5#2   balanc@5            22
    y#1#5#2   balanc@2            50
    y#1#5#3   BigM_15              1
    y#1#5#3   valid_1             50
    y#1#5#3   balanc@6            22
    y#1#5#3   balanc@3            50
    y#1#6#1   BigM_16              1
    y#1#6#1   valid_1             40
    y#1#6#1   balanc@4            32
    y#1#6#1   balanc@1            40
    y#1#6#2   BigM_17              1
    y#1#6#2   valid_1             40
    y#1#6#2   balanc@5            32
    y#1#6#2   balanc@2            40
    y#1#6#3   BigM_18              1
    y#1#6#3   valid_1             40
    y#1#6#3   balanc@6            32
    y#1#6#3   balanc@3            40
    y#1#7#1   BigM_19              1
    y#1#7#1   valid_1             21
    y#1#7#1   balanc@4            51
    y#1#7#1   balanc@1            21
    y#1#7#2   BigM_20              1
    y#1#7#2   valid_1             21
    y#1#7#2   balanc@5            51
    y#1#7#2   balanc@2            21
    y#1#7#3   BigM_21              1
    y#1#7#3   valid_1             21
    y#1#7#3   balanc@6            51
    y#1#7#3   balanc@3            21
    y#1#8#1   BigM_22              1
    y#1#8#1   valid_1              3
    y#1#8#1   balanc@4            69
    y#1#8#1   balanc@1             3
    y#1#8#2   BigM_23              1
    y#1#8#2   valid_1              3
    y#1#8#2   balanc@5            69
    y#1#8#2   balanc@2             3
    y#1#8#3   BigM_24              1
    y#1#8#3   valid_1              3
    y#1#8#3   balanc@6            69
    y#1#8#3   balanc@3             3
    y#1#9#1   BigM_25              1
    y#1#9#1   valid_1              4
    y#1#9#1   balanc@4            68
    y#1#9#1   balanc@1             4
    y#1#9#2   BigM_26              1
    y#1#9#2   valid_1              4
    y#1#9#2   balanc@5            68
    y#1#9#2   balanc@2             4
    y#1#9#3   BigM_27              1
    y#1#9#3   valid_1              4
    y#1#9#3   balanc@6            68
    y#1#9#3   balanc@3             4
    y#2#1#1   BigM_28              1
    y#2#1#1   valid_3             43
    y#2#1#1   valid_2             29
    y#2#1#1   balanc@a            43
    y#2#1#1   balanc@7            29
    y#2#1#2   BigM_29              1
    y#2#1#2   valid_3             43
    y#2#1#2   valid_2             29
    y#2#1#2   balanc@b            43
    y#2#1#2   balanc@8            29
    y#2#1#3   BigM_30              1
    y#2#1#3   valid_3             43
    y#2#1#3   valid_2             29
    y#2#1#3   balanc@c            43
    y#2#1#3   balanc@9            29
    y#2#2#1   BigM_31              1
    y#2#2#1   valid_3             57
    y#2#2#1   valid_2             15
    y#2#2#1   balanc@a            57
    y#2#2#1   balanc@7            15
    y#2#2#2   BigM_32              1
    y#2#2#2   valid_3             57
    y#2#2#2   valid_2             15
    y#2#2#2   balanc@b            57
    y#2#2#2   balanc@8            15
    y#2#2#3   BigM_33              1
    y#2#2#3   valid_3             57
    y#2#2#3   valid_2             15
    y#2#2#3   balanc@c            57
    y#2#2#3   balanc@9            15
    y#2#3#1   BigM_34              1
    y#2#3#1   valid_3             15
    y#2#3#1   valid_2             57
    y#2#3#1   balanc@a            15
    y#2#3#1   balanc@7            57
    y#2#3#2   BigM_35              1
    y#2#3#2   valid_3             15
    y#2#3#2   valid_2             57
    y#2#3#2   balanc@b            15
    y#2#3#2   balanc@8            57
    y#2#3#3   BigM_36              1
    y#2#3#3   valid_3             15
    y#2#3#3   valid_2             57
    y#2#3#3   balanc@c            15
    y#2#3#3   balanc@9            57
    y#2#4#1   BigM_37              1
    y#2#4#1   valid_3              9
    y#2#4#1   valid_2             63
    y#2#4#1   balanc@a             9
    y#2#4#1   balanc@7            63
    y#2#4#2   BigM_38              1
    y#2#4#2   valid_3              9
    y#2#4#2   valid_2             63
    y#2#4#2   balanc@b             9
    y#2#4#2   balanc@8            63
    y#2#4#3   BigM_39              1
    y#2#4#3   valid_3              9
    y#2#4#3   valid_2             63
    y#2#4#3   balanc@c             9
    y#2#4#3   balanc@9            63
    y#2#5#1   BigM_40              1
    y#2#5#1   valid_3             22
    y#2#5#1   valid_2             50
    y#2#5#1   balanc@a            22
    y#2#5#1   balanc@7            50
    y#2#5#2   BigM_41              1
    y#2#5#2   valid_3             22
    y#2#5#2   valid_2             50
    y#2#5#2   balanc@b            22
    y#2#5#2   balanc@8            50
    y#2#5#3   BigM_42              1
    y#2#5#3   valid_3             22
    y#2#5#3   valid_2             50
    y#2#5#3   balanc@c            22
    y#2#5#3   balanc@9            50
    y#2#6#1   BigM_43              1
    y#2#6#1   valid_3             32
    y#2#6#1   valid_2             40
    y#2#6#1   balanc@a            32
    y#2#6#1   balanc@7            40
    y#2#6#2   BigM_44              1
    y#2#6#2   valid_3             32
    y#2#6#2   valid_2             40
    y#2#6#2   balanc@b            32
    y#2#6#2   balanc@8            40
    y#2#6#3   BigM_45              1
    y#2#6#3   valid_3             32
    y#2#6#3   valid_2             40
    y#2#6#3   balanc@c            32
    y#2#6#3   balanc@9            40
    y#2#7#1   BigM_46              1
    y#2#7#1   valid_3             51
    y#2#7#1   valid_2             21
    y#2#7#1   balanc@a            51
    y#2#7#1   balanc@7            21
    y#2#7#2   BigM_47              1
    y#2#7#2   valid_3             51
    y#2#7#2   valid_2             21
    y#2#7#2   balanc@b            51
    y#2#7#2   balanc@8            21
    y#2#7#3   BigM_48              1
    y#2#7#3   valid_3             51
    y#2#7#3   valid_2             21
    y#2#7#3   balanc@c            51
    y#2#7#3   balanc@9            21
    y#2#8#1   BigM_49              1
    y#2#8#1   valid_3             69
    y#2#8#1   valid_2              3
    y#2#8#1   balanc@a            69
    y#2#8#1   balanc@7             3
    y#2#8#2   BigM_50              1
    y#2#8#2   valid_3             69
    y#2#8#2   valid_2              3
    y#2#8#2   balanc@b            69
    y#2#8#2   balanc@8             3
    y#2#8#3   BigM_51              1
    y#2#8#3   valid_3             69
    y#2#8#3   valid_2              3
    y#2#8#3   balanc@c            69
    y#2#8#3   balanc@9             3
    y#2#9#1   BigM_52              1
    y#2#9#1   valid_3             68
    y#2#9#1   valid_2              4
    y#2#9#1   balanc@a            68
    y#2#9#1   balanc@7             4
    y#2#9#2   BigM_53              1
    y#2#9#2   valid_3             68
    y#2#9#2   valid_2              4
    y#2#9#2   balanc@b            68
    y#2#9#2   balanc@8             4
    y#2#9#3   BigM_54              1
    y#2#9#3   valid_3             68
    y#2#9#3   valid_2              4
    y#2#9#3   balanc@c            68
    y#2#9#3   balanc@9             4
    y#3#1#1   BigM_55              1
    y#3#1#1   valid_5             43
    y#3#1#1   valid_4             29
    y#3#1#1   balan@10            43
    y#3#1#1   balanc@d            29
    y#3#1#2   BigM_56              1
    y#3#1#2   valid_5             43
    y#3#1#2   valid_4             29
    y#3#1#2   balan@11            43
    y#3#1#2   balanc@e            29
    y#3#1#3   BigM_57              1
    y#3#1#3   valid_5             43
    y#3#1#3   valid_4             29
    y#3#1#3   balan@12            43
    y#3#1#3   balanc@f            29
    y#3#2#1   BigM_58              1
    y#3#2#1   valid_5             57
    y#3#2#1   valid_4             15
    y#3#2#1   balan@10            57
    y#3#2#1   balanc@d            15
    y#3#2#2   BigM_59              1
    y#3#2#2   valid_5             57
    y#3#2#2   valid_4             15
    y#3#2#2   balan@11            57
    y#3#2#2   balanc@e            15
    y#3#2#3   BigM_60              1
    y#3#2#3   valid_5             57
    y#3#2#3   valid_4             15
    y#3#2#3   balan@12            57
    y#3#2#3   balanc@f            15
    y#3#3#1   BigM_61              1
    y#3#3#1   valid_5             15
    y#3#3#1   valid_4             57
    y#3#3#1   balan@10            15
    y#3#3#1   balanc@d            57
    y#3#3#2   BigM_62              1
    y#3#3#2   valid_5             15
    y#3#3#2   valid_4             57
    y#3#3#2   balan@11            15
    y#3#3#2   balanc@e            57
    y#3#3#3   BigM_63              1
    y#3#3#3   valid_5             15
    y#3#3#3   valid_4             57
    y#3#3#3   balan@12            15
    y#3#3#3   balanc@f            57
    y#3#4#1   BigM_64              1
    y#3#4#1   valid_5              9
    y#3#4#1   valid_4             63
    y#3#4#1   balan@10             9
    y#3#4#1   balanc@d            63
    y#3#4#2   BigM_65              1
    y#3#4#2   valid_5              9
    y#3#4#2   valid_4             63
    y#3#4#2   balan@11             9
    y#3#4#2   balanc@e            63
    y#3#4#3   BigM_66              1
    y#3#4#3   valid_5              9
    y#3#4#3   valid_4             63
    y#3#4#3   balan@12             9
    y#3#4#3   balanc@f            63
    y#3#5#1   BigM_67              1
    y#3#5#1   valid_5             22
    y#3#5#1   valid_4             50
    y#3#5#1   balan@10            22
    y#3#5#1   balanc@d            50
    y#3#5#2   BigM_68              1
    y#3#5#2   valid_5             22
    y#3#5#2   valid_4             50
    y#3#5#2   balan@11            22
    y#3#5#2   balanc@e            50
    y#3#5#3   BigM_69              1
    y#3#5#3   valid_5             22
    y#3#5#3   valid_4             50
    y#3#5#3   balan@12            22
    y#3#5#3   balanc@f            50
    y#3#6#1   BigM_70              1
    y#3#6#1   valid_5             32
    y#3#6#1   valid_4             40
    y#3#6#1   balan@10            32
    y#3#6#1   balanc@d            40
    y#3#6#2   BigM_71              1
    y#3#6#2   valid_5             32
    y#3#6#2   valid_4             40
    y#3#6#2   balan@11            32
    y#3#6#2   balanc@e            40
    y#3#6#3   BigM_72              1
    y#3#6#3   valid_5             32
    y#3#6#3   valid_4             40
    y#3#6#3   balan@12            32
    y#3#6#3   balanc@f            40
    y#3#7#1   BigM_73              1
    y#3#7#1   valid_5             51
    y#3#7#1   valid_4             21
    y#3#7#1   balan@10            51
    y#3#7#1   balanc@d            21
    y#3#7#2   BigM_74              1
    y#3#7#2   valid_5             51
    y#3#7#2   valid_4             21
    y#3#7#2   balan@11            51
    y#3#7#2   balanc@e            21
    y#3#7#3   BigM_75              1
    y#3#7#3   valid_5             51
    y#3#7#3   valid_4             21
    y#3#7#3   balan@12            51
    y#3#7#3   balanc@f            21
    y#3#8#1   BigM_76              1
    y#3#8#1   valid_5             69
    y#3#8#1   valid_4              3
    y#3#8#1   balan@10            69
    y#3#8#1   balanc@d             3
    y#3#8#2   BigM_77              1
    y#3#8#2   valid_5             69
    y#3#8#2   valid_4              3
    y#3#8#2   balan@11            69
    y#3#8#2   balanc@e             3
    y#3#8#3   BigM_78              1
    y#3#8#3   valid_5             69
    y#3#8#3   valid_4              3
    y#3#8#3   balan@12            69
    y#3#8#3   balanc@f             3
    y#3#9#1   BigM_79              1
    y#3#9#1   valid_5             68
    y#3#9#1   valid_4              4
    y#3#9#1   balan@10            68
    y#3#9#1   balanc@d             4
    y#3#9#2   BigM_80              1
    y#3#9#2   valid_5             68
    y#3#9#2   valid_4              4
    y#3#9#2   balan@11            68
    y#3#9#2   balanc@e             4
    y#3#9#3   BigM_81              1
    y#3#9#3   valid_5             68
    y#3#9#3   valid_4              4
    y#3#9#3   balan@12            68
    y#3#9#3   balanc@f             4
    y#4#1#1   BigM_82              1
    y#4#1#1   valid_6             43
    y#4#1#1   balan@16            43
    y#4#1#1   balan@13            29
    y#4#1#2   BigM_83              1
    y#4#1#2   valid_6             43
    y#4#1#2   balan@17            43
    y#4#1#2   balan@14            29
    y#4#1#3   BigM_84              1
    y#4#1#3   valid_6             43
    y#4#1#3   balan@18            43
    y#4#1#3   balan@15            29
    y#4#2#1   BigM_85              1
    y#4#2#1   valid_6             57
    y#4#2#1   balan@16            57
    y#4#2#1   balan@13            15
    y#4#2#2   BigM_86              1
    y#4#2#2   valid_6             57
    y#4#2#2   balan@17            57
    y#4#2#2   balan@14            15
    y#4#2#3   BigM_87              1
    y#4#2#3   valid_6             57
    y#4#2#3   balan@18            57
    y#4#2#3   balan@15            15
    y#4#3#1   BigM_88              1
    y#4#3#1   valid_6             15
    y#4#3#1   balan@16            15
    y#4#3#1   balan@13            57
    y#4#3#2   BigM_89              1
    y#4#3#2   valid_6             15
    y#4#3#2   balan@17            15
    y#4#3#2   balan@14            57
    y#4#3#3   BigM_90              1
    y#4#3#3   valid_6             15
    y#4#3#3   balan@18            15
    y#4#3#3   balan@15            57
    y#4#4#1   BigM_91              1
    y#4#4#1   valid_6              9
    y#4#4#1   balan@16             9
    y#4#4#1   balan@13            63
    y#4#4#2   BigM_92              1
    y#4#4#2   valid_6              9
    y#4#4#2   balan@17             9
    y#4#4#2   balan@14            63
    y#4#4#3   BigM_93              1
    y#4#4#3   valid_6              9
    y#4#4#3   balan@18             9
    y#4#4#3   balan@15            63
    y#4#5#1   BigM_94              1
    y#4#5#1   valid_6             22
    y#4#5#1   balan@16            22
    y#4#5#1   balan@13            50
    y#4#5#2   BigM_95              1
    y#4#5#2   valid_6             22
    y#4#5#2   balan@17            22
    y#4#5#2   balan@14            50
    y#4#5#3   BigM_96              1
    y#4#5#3   valid_6             22
    y#4#5#3   balan@18            22
    y#4#5#3   balan@15            50
    y#4#6#1   BigM_97              1
    y#4#6#1   valid_6             32
    y#4#6#1   balan@16            32
    y#4#6#1   balan@13            40
    y#4#6#2   BigM_98              1
    y#4#6#2   valid_6             32
    y#4#6#2   balan@17            32
    y#4#6#2   balan@14            40
    y#4#6#3   BigM_99              1
    y#4#6#3   valid_6             32
    y#4#6#3   balan@18            32
    y#4#6#3   balan@15            40
    y#4#7#1   BigM_100             1
    y#4#7#1   valid_6             51
    y#4#7#1   balan@16            51
    y#4#7#1   balan@13            21
    y#4#7#2   BigM_101             1
    y#4#7#2   valid_6             51
    y#4#7#2   balan@17            51
    y#4#7#2   balan@14            21
    y#4#7#3   BigM_102             1
    y#4#7#3   valid_6             51
    y#4#7#3   balan@18            51
    y#4#7#3   balan@15            21
    y#4#8#1   BigM_103             1
    y#4#8#1   valid_6             69
    y#4#8#1   balan@16            69
    y#4#8#1   balan@13             3
    y#4#8#2   BigM_104             1
    y#4#8#2   valid_6             69
    y#4#8#2   balan@17            69
    y#4#8#2   balan@14             3
    y#4#8#3   BigM_105             1
    y#4#8#3   valid_6             69
    y#4#8#3   balan@18            69
    y#4#8#3   balan@15             3
    y#4#9#1   BigM_106             1
    y#4#9#1   valid_6             68
    y#4#9#1   balan@16            68
    y#4#9#1   balan@13             4
    y#4#9#2   BigM_107             1
    y#4#9#2   valid_6             68
    y#4#9#2   balan@17            68
    y#4#9#2   balan@14             4
    y#4#9#3   BigM_108             1
    y#4#9#3   valid_6             68
    y#4#9#3   balan@18            68
    y#4#9#3   balan@15             4
    y#5#1#1   BigM_109             1
    y#5#1#1   valid_8             43
    y#5#1#1   valid_7             29
    y#5#1#1   balan@1c            43
    y#5#1#1   balan@19            29
    y#5#1#2   BigM_110             1
    y#5#1#2   valid_8             43
    y#5#1#2   valid_7             29
    y#5#1#2   balan@1d            43
    y#5#1#2   balan@1a            29
    y#5#1#3   BigM_111             1
    y#5#1#3   valid_8             43
    y#5#1#3   valid_7             29
    y#5#1#3   balan@1e            43
    y#5#1#3   balan@1b            29
    y#5#2#1   BigM_112             1
    y#5#2#1   valid_8             57
    y#5#2#1   valid_7             15
    y#5#2#1   balan@1c            57
    y#5#2#1   balan@19            15
    y#5#2#2   BigM_113             1
    y#5#2#2   valid_8             57
    y#5#2#2   valid_7             15
    y#5#2#2   balan@1d            57
    y#5#2#2   balan@1a            15
    y#5#2#3   BigM_114             1
    y#5#2#3   valid_8             57
    y#5#2#3   valid_7             15
    y#5#2#3   balan@1e            57
    y#5#2#3   balan@1b            15
    y#5#3#1   BigM_115             1
    y#5#3#1   valid_8             15
    y#5#3#1   valid_7             57
    y#5#3#1   balan@1c            15
    y#5#3#1   balan@19            57
    y#5#3#2   BigM_116             1
    y#5#3#2   valid_8             15
    y#5#3#2   valid_7             57
    y#5#3#2   balan@1d            15
    y#5#3#2   balan@1a            57
    y#5#3#3   BigM_117             1
    y#5#3#3   valid_8             15
    y#5#3#3   valid_7             57
    y#5#3#3   balan@1e            15
    y#5#3#3   balan@1b            57
    y#5#4#1   BigM_118             1
    y#5#4#1   valid_8              9
    y#5#4#1   valid_7             63
    y#5#4#1   balan@1c             9
    y#5#4#1   balan@19            63
    y#5#4#2   BigM_119             1
    y#5#4#2   valid_8              9
    y#5#4#2   valid_7             63
    y#5#4#2   balan@1d             9
    y#5#4#2   balan@1a            63
    y#5#4#3   BigM_120             1
    y#5#4#3   valid_8              9
    y#5#4#3   valid_7             63
    y#5#4#3   balan@1e             9
    y#5#4#3   balan@1b            63
    y#5#5#1   BigM_121             1
    y#5#5#1   valid_8             22
    y#5#5#1   valid_7             50
    y#5#5#1   balan@1c            22
    y#5#5#1   balan@19            50
    y#5#5#2   BigM_122             1
    y#5#5#2   valid_8             22
    y#5#5#2   valid_7             50
    y#5#5#2   balan@1d            22
    y#5#5#2   balan@1a            50
    y#5#5#3   BigM_123             1
    y#5#5#3   valid_8             22
    y#5#5#3   valid_7             50
    y#5#5#3   balan@1e            22
    y#5#5#3   balan@1b            50
    y#5#6#1   BigM_124             1
    y#5#6#1   valid_8             32
    y#5#6#1   valid_7             40
    y#5#6#1   balan@1c            32
    y#5#6#1   balan@19            40
    y#5#6#2   BigM_125             1
    y#5#6#2   valid_8             32
    y#5#6#2   valid_7             40
    y#5#6#2   balan@1d            32
    y#5#6#2   balan@1a            40
    y#5#6#3   BigM_126             1
    y#5#6#3   valid_8             32
    y#5#6#3   valid_7             40
    y#5#6#3   balan@1e            32
    y#5#6#3   balan@1b            40
    y#5#7#1   BigM_127             1
    y#5#7#1   valid_8             51
    y#5#7#1   valid_7             21
    y#5#7#1   balan@1c            51
    y#5#7#1   balan@19            21
    y#5#7#2   BigM_128             1
    y#5#7#2   valid_8             51
    y#5#7#2   valid_7             21
    y#5#7#2   balan@1d            51
    y#5#7#2   balan@1a            21
    y#5#7#3   BigM_129             1
    y#5#7#3   valid_8             51
    y#5#7#3   valid_7             21
    y#5#7#3   balan@1e            51
    y#5#7#3   balan@1b            21
    y#5#8#1   BigM_130             1
    y#5#8#1   valid_8             69
    y#5#8#1   valid_7              3
    y#5#8#1   balan@1c            69
    y#5#8#1   balan@19             3
    y#5#8#2   BigM_131             1
    y#5#8#2   valid_8             69
    y#5#8#2   valid_7              3
    y#5#8#2   balan@1d            69
    y#5#8#2   balan@1a             3
    y#5#8#3   BigM_132             1
    y#5#8#3   valid_8             69
    y#5#8#3   valid_7              3
    y#5#8#3   balan@1e            69
    y#5#8#3   balan@1b             3
    y#5#9#1   BigM_133             1
    y#5#9#1   valid_8             68
    y#5#9#1   valid_7              4
    y#5#9#1   balan@1c            68
    y#5#9#1   balan@19             4
    y#5#9#2   BigM_134             1
    y#5#9#2   valid_8             68
    y#5#9#2   valid_7              4
    y#5#9#2   balan@1d            68
    y#5#9#2   balan@1a             4
    y#5#9#3   BigM_135             1
    y#5#9#3   valid_8             68
    y#5#9#3   valid_7              4
    y#5#9#3   balan@1e            68
    y#5#9#3   balan@1b             4
    y#6#1#1   BigM_136             1
    y#6#1#1   valid_10            43
    y#6#1#1   valid_9             29
    y#6#1#1   balan@22            43
    y#6#1#1   balan@1f            29
    y#6#1#2   BigM_137             1
    y#6#1#2   valid_10            43
    y#6#1#2   valid_9             29
    y#6#1#2   balan@23            43
    y#6#1#2   balan@20            29
    y#6#1#3   BigM_138             1
    y#6#1#3   valid_10            43
    y#6#1#3   valid_9             29
    y#6#1#3   balan@24            43
    y#6#1#3   balan@21            29
    y#6#2#1   BigM_139             1
    y#6#2#1   valid_10            57
    y#6#2#1   valid_9             15
    y#6#2#1   balan@22            57
    y#6#2#1   balan@1f            15
    y#6#2#2   BigM_140             1
    y#6#2#2   valid_10            57
    y#6#2#2   valid_9             15
    y#6#2#2   balan@23            57
    y#6#2#2   balan@20            15
    y#6#2#3   BigM_141             1
    y#6#2#3   valid_10            57
    y#6#2#3   valid_9             15
    y#6#2#3   balan@24            57
    y#6#2#3   balan@21            15
    y#6#3#1   BigM_142             1
    y#6#3#1   valid_10            15
    y#6#3#1   valid_9             57
    y#6#3#1   balan@22            15
    y#6#3#1   balan@1f            57
    y#6#3#2   BigM_143             1
    y#6#3#2   valid_10            15
    y#6#3#2   valid_9             57
    y#6#3#2   balan@23            15
    y#6#3#2   balan@20            57
    y#6#3#3   BigM_144             1
    y#6#3#3   valid_10            15
    y#6#3#3   valid_9             57
    y#6#3#3   balan@24            15
    y#6#3#3   balan@21            57
    y#6#4#1   BigM_145             1
    y#6#4#1   valid_10             9
    y#6#4#1   valid_9             63
    y#6#4#1   balan@22             9
    y#6#4#1   balan@1f            63
    y#6#4#2   BigM_146             1
    y#6#4#2   valid_10             9
    y#6#4#2   valid_9             63
    y#6#4#2   balan@23             9
    y#6#4#2   balan@20            63
    y#6#4#3   BigM_147             1
    y#6#4#3   valid_10             9
    y#6#4#3   valid_9             63
    y#6#4#3   balan@24             9
    y#6#4#3   balan@21            63
    y#6#5#1   BigM_148             1
    y#6#5#1   valid_10            22
    y#6#5#1   valid_9             50
    y#6#5#1   balan@22            22
    y#6#5#1   balan@1f            50
    y#6#5#2   BigM_149             1
    y#6#5#2   valid_10            22
    y#6#5#2   valid_9             50
    y#6#5#2   balan@23            22
    y#6#5#2   balan@20            50
    y#6#5#3   BigM_150             1
    y#6#5#3   valid_10            22
    y#6#5#3   valid_9             50
    y#6#5#3   balan@24            22
    y#6#5#3   balan@21            50
    y#6#6#1   BigM_151             1
    y#6#6#1   valid_10            32
    y#6#6#1   valid_9             40
    y#6#6#1   balan@22            32
    y#6#6#1   balan@1f            40
    y#6#6#2   BigM_152             1
    y#6#6#2   valid_10            32
    y#6#6#2   valid_9             40
    y#6#6#2   balan@23            32
    y#6#6#2   balan@20            40
    y#6#6#3   BigM_153             1
    y#6#6#3   valid_10            32
    y#6#6#3   valid_9             40
    y#6#6#3   balan@24            32
    y#6#6#3   balan@21            40
    y#6#7#1   BigM_154             1
    y#6#7#1   valid_10            51
    y#6#7#1   valid_9             21
    y#6#7#1   balan@22            51
    y#6#7#1   balan@1f            21
    y#6#7#2   BigM_155             1
    y#6#7#2   valid_10            51
    y#6#7#2   valid_9             21
    y#6#7#2   balan@23            51
    y#6#7#2   balan@20            21
    y#6#7#3   BigM_156             1
    y#6#7#3   valid_10            51
    y#6#7#3   valid_9             21
    y#6#7#3   balan@24            51
    y#6#7#3   balan@21            21
    y#6#8#1   BigM_157             1
    y#6#8#1   valid_10            69
    y#6#8#1   valid_9              3
    y#6#8#1   balan@22            69
    y#6#8#1   balan@1f             3
    y#6#8#2   BigM_158             1
    y#6#8#2   valid_10            69
    y#6#8#2   valid_9              3
    y#6#8#2   balan@23            69
    y#6#8#2   balan@20             3
    y#6#8#3   BigM_159             1
    y#6#8#3   valid_10            69
    y#6#8#3   valid_9              3
    y#6#8#3   balan@24            69
    y#6#8#3   balan@21             3
    y#6#9#1   BigM_160             1
    y#6#9#1   valid_10            68
    y#6#9#1   valid_9              4
    y#6#9#1   balan@22            68
    y#6#9#1   balan@1f             4
    y#6#9#2   BigM_161             1
    y#6#9#2   valid_10            68
    y#6#9#2   valid_9              4
    y#6#9#2   balan@23            68
    y#6#9#2   balan@20             4
    y#6#9#3   BigM_162             1
    y#6#9#3   valid_10            68
    y#6#9#3   valid_9              4
    y#6#9#3   balan@24            68
    y#6#9#3   balan@21             4
    y#7#1#1   BigM_163             1
    y#7#1#1   valid_12            43
    y#7#1#1   valid_11            29
    y#7#1#1   balan@28            43
    y#7#1#1   balan@25            29
    y#7#1#2   BigM_164             1
    y#7#1#2   valid_12            43
    y#7#1#2   valid_11            29
    y#7#1#2   balan@29            43
    y#7#1#2   balan@26            29
    y#7#1#3   BigM_165             1
    y#7#1#3   valid_12            43
    y#7#1#3   valid_11            29
    y#7#1#3   balan@2a            43
    y#7#1#3   balan@27            29
    y#7#2#1   BigM_166             1
    y#7#2#1   valid_12            57
    y#7#2#1   valid_11            15
    y#7#2#1   balan@28            57
    y#7#2#1   balan@25            15
    y#7#2#2   BigM_167             1
    y#7#2#2   valid_12            57
    y#7#2#2   valid_11            15
    y#7#2#2   balan@29            57
    y#7#2#2   balan@26            15
    y#7#2#3   BigM_168             1
    y#7#2#3   valid_12            57
    y#7#2#3   valid_11            15
    y#7#2#3   balan@2a            57
    y#7#2#3   balan@27            15
    y#7#3#1   BigM_169             1
    y#7#3#1   valid_12            15
    y#7#3#1   valid_11            57
    y#7#3#1   balan@28            15
    y#7#3#1   balan@25            57
    y#7#3#2   BigM_170             1
    y#7#3#2   valid_12            15
    y#7#3#2   valid_11            57
    y#7#3#2   balan@29            15
    y#7#3#2   balan@26            57
    y#7#3#3   BigM_171             1
    y#7#3#3   valid_12            15
    y#7#3#3   valid_11            57
    y#7#3#3   balan@2a            15
    y#7#3#3   balan@27            57
    y#7#4#1   BigM_172             1
    y#7#4#1   valid_12             9
    y#7#4#1   valid_11            63
    y#7#4#1   balan@28             9
    y#7#4#1   balan@25            63
    y#7#4#2   BigM_173             1
    y#7#4#2   valid_12             9
    y#7#4#2   valid_11            63
    y#7#4#2   balan@29             9
    y#7#4#2   balan@26            63
    y#7#4#3   BigM_174             1
    y#7#4#3   valid_12             9
    y#7#4#3   valid_11            63
    y#7#4#3   balan@2a             9
    y#7#4#3   balan@27            63
    y#7#5#1   BigM_175             1
    y#7#5#1   valid_12            22
    y#7#5#1   valid_11            50
    y#7#5#1   balan@28            22
    y#7#5#1   balan@25            50
    y#7#5#2   BigM_176             1
    y#7#5#2   valid_12            22
    y#7#5#2   valid_11            50
    y#7#5#2   balan@29            22
    y#7#5#2   balan@26            50
    y#7#5#3   BigM_177             1
    y#7#5#3   valid_12            22
    y#7#5#3   valid_11            50
    y#7#5#3   balan@2a            22
    y#7#5#3   balan@27            50
    y#7#6#1   BigM_178             1
    y#7#6#1   valid_12            32
    y#7#6#1   valid_11            40
    y#7#6#1   balan@28            32
    y#7#6#1   balan@25            40
    y#7#6#2   BigM_179             1
    y#7#6#2   valid_12            32
    y#7#6#2   valid_11            40
    y#7#6#2   balan@29            32
    y#7#6#2   balan@26            40
    y#7#6#3   BigM_180             1
    y#7#6#3   valid_12            32
    y#7#6#3   valid_11            40
    y#7#6#3   balan@2a            32
    y#7#6#3   balan@27            40
    y#7#7#1   BigM_181             1
    y#7#7#1   valid_12            51
    y#7#7#1   valid_11            21
    y#7#7#1   balan@28            51
    y#7#7#1   balan@25            21
    y#7#7#2   BigM_182             1
    y#7#7#2   valid_12            51
    y#7#7#2   valid_11            21
    y#7#7#2   balan@29            51
    y#7#7#2   balan@26            21
    y#7#7#3   BigM_183             1
    y#7#7#3   valid_12            51
    y#7#7#3   valid_11            21
    y#7#7#3   balan@2a            51
    y#7#7#3   balan@27            21
    y#7#8#1   BigM_184             1
    y#7#8#1   valid_12            69
    y#7#8#1   valid_11             3
    y#7#8#1   balan@28            69
    y#7#8#1   balan@25             3
    y#7#8#2   BigM_185             1
    y#7#8#2   valid_12            69
    y#7#8#2   valid_11             3
    y#7#8#2   balan@29            69
    y#7#8#2   balan@26             3
    y#7#8#3   BigM_186             1
    y#7#8#3   valid_12            69
    y#7#8#3   valid_11             3
    y#7#8#3   balan@2a            69
    y#7#8#3   balan@27             3
    y#7#9#1   BigM_187             1
    y#7#9#1   valid_12            68
    y#7#9#1   valid_11             4
    y#7#9#1   balan@28            68
    y#7#9#1   balan@25             4
    y#7#9#2   BigM_188             1
    y#7#9#2   valid_12            68
    y#7#9#2   valid_11             4
    y#7#9#2   balan@29            68
    y#7#9#2   balan@26             4
    y#7#9#3   BigM_189             1
    y#7#9#3   valid_12            68
    y#7#9#3   valid_11             4
    y#7#9#3   balan@2a            68
    y#7#9#3   balan@27             4
    y#8#1#1   BigM_190             1
    y#8#1#1   valid_13            43
    y#8#1#1   balan@2e            43
    y#8#1#1   balan@2b            29
    y#8#1#2   BigM_191             1
    y#8#1#2   valid_13            43
    y#8#1#2   balan@2f            43
    y#8#1#2   balan@2c            29
    y#8#1#3   BigM_192             1
    y#8#1#3   valid_13            43
    y#8#1#3   balan@30            43
    y#8#1#3   balan@2d            29
    y#8#2#1   BigM_193             1
    y#8#2#1   valid_13            57
    y#8#2#1   balan@2e            57
    y#8#2#1   balan@2b            15
    y#8#2#2   BigM_194             1
    y#8#2#2   valid_13            57
    y#8#2#2   balan@2f            57
    y#8#2#2   balan@2c            15
    y#8#2#3   BigM_195             1
    y#8#2#3   valid_13            57
    y#8#2#3   balan@30            57
    y#8#2#3   balan@2d            15
    y#8#3#1   BigM_196             1
    y#8#3#1   valid_13            15
    y#8#3#1   balan@2e            15
    y#8#3#1   balan@2b            57
    y#8#3#2   BigM_197             1
    y#8#3#2   valid_13            15
    y#8#3#2   balan@2f            15
    y#8#3#2   balan@2c            57
    y#8#3#3   BigM_198             1
    y#8#3#3   valid_13            15
    y#8#3#3   balan@30            15
    y#8#3#3   balan@2d            57
    y#8#4#1   BigM_199             1
    y#8#4#1   valid_13             9
    y#8#4#1   balan@2e             9
    y#8#4#1   balan@2b            63
    y#8#4#2   BigM_200             1
    y#8#4#2   valid_13             9
    y#8#4#2   balan@2f             9
    y#8#4#2   balan@2c            63
    y#8#4#3   BigM_201             1
    y#8#4#3   valid_13             9
    y#8#4#3   balan@30             9
    y#8#4#3   balan@2d            63
    y#8#5#1   BigM_202             1
    y#8#5#1   valid_13            22
    y#8#5#1   balan@2e            22
    y#8#5#1   balan@2b            50
    y#8#5#2   BigM_203             1
    y#8#5#2   valid_13            22
    y#8#5#2   balan@2f            22
    y#8#5#2   balan@2c            50
    y#8#5#3   BigM_204             1
    y#8#5#3   valid_13            22
    y#8#5#3   balan@30            22
    y#8#5#3   balan@2d            50
    y#8#6#1   BigM_205             1
    y#8#6#1   valid_13            32
    y#8#6#1   balan@2e            32
    y#8#6#1   balan@2b            40
    y#8#6#2   BigM_206             1
    y#8#6#2   valid_13            32
    y#8#6#2   balan@2f            32
    y#8#6#2   balan@2c            40
    y#8#6#3   BigM_207             1
    y#8#6#3   valid_13            32
    y#8#6#3   balan@30            32
    y#8#6#3   balan@2d            40
    y#8#7#1   BigM_208             1
    y#8#7#1   valid_13            51
    y#8#7#1   balan@2e            51
    y#8#7#1   balan@2b            21
    y#8#7#2   BigM_209             1
    y#8#7#2   valid_13            51
    y#8#7#2   balan@2f            51
    y#8#7#2   balan@2c            21
    y#8#7#3   BigM_210             1
    y#8#7#3   valid_13            51
    y#8#7#3   balan@30            51
    y#8#7#3   balan@2d            21
    y#8#8#1   BigM_211             1
    y#8#8#1   valid_13            69
    y#8#8#1   balan@2e            69
    y#8#8#1   balan@2b             3
    y#8#8#2   BigM_212             1
    y#8#8#2   valid_13            69
    y#8#8#2   balan@2f            69
    y#8#8#2   balan@2c             3
    y#8#8#3   BigM_213             1
    y#8#8#3   valid_13            69
    y#8#8#3   balan@30            69
    y#8#8#3   balan@2d             3
    y#8#9#1   BigM_214             1
    y#8#9#1   valid_13            68
    y#8#9#1   balan@2e            68
    y#8#9#1   balan@2b             4
    y#8#9#2   BigM_215             1
    y#8#9#2   valid_13            68
    y#8#9#2   balan@2f            68
    y#8#9#2   balan@2c             4
    y#8#9#3   BigM_216             1
    y#8#9#3   valid_13            68
    y#8#9#3   balan@30            68
    y#8#9#3   balan@2d             4
    z#1       BigM_192           -57
    z#1       BigM_191           -57
    z#1       BigM_190           -57
    z#1       BigM_165           -78
    z#1       BigM_164           -78
    z#1       BigM_163           -78
    z#1       BigM_138           -90
    z#1       BigM_137           -90
    z#1       BigM_136           -90
    z#1       BigM_111           -96
    z#1       BigM_110           -96
    z#1       BigM_109           -96
    z#1       BigM_84            -56
    z#1       BigM_83            -56
    z#1       BigM_82            -56
    z#1       BigM_57            -33
    z#1       BigM_56            -33
    z#1       BigM_55            -33
    z#1       BigM_30            -55
    z#1       BigM_29            -55
    z#1       BigM_28            -55
    z#1       BigM_3             -46
    z#1       BigM_2             -46
    z#1       BigM_1             -46
    z#1       select_1             1
    z#2       BigM_195           -43
    z#2       BigM_194           -43
    z#2       BigM_193           -43
    z#2       BigM_168          -150
    z#2       BigM_167          -150
    z#2       BigM_166          -150
    z#2       BigM_141          -173
    z#2       BigM_140          -173
    z#2       BigM_139          -173
    z#2       BigM_114          -185
    z#2       BigM_113          -185
    z#2       BigM_112          -185
    z#2       BigM_87            -42
    z#2       BigM_86            -42
    z#2       BigM_85            -42
    z#2       BigM_60            -64
    z#2       BigM_59            -64
    z#2       BigM_58            -64
    z#2       BigM_33           -105
    z#2       BigM_32           -105
    z#2       BigM_31           -105
    z#2       BigM_6             -89
    z#2       BigM_5             -89
    z#2       BigM_4             -89
    z#2       select_1             1
    z#3       BigM_198          -162
    z#3       BigM_197          -162
    z#3       BigM_196          -162
    z#3       BigM_171           -98
    z#3       BigM_170           -98
    z#3       BigM_169           -98
    z#3       BigM_144          -128
    z#3       BigM_143          -128
    z#3       BigM_142          -128
    z#3       BigM_117           -53
    z#3       BigM_116           -53
    z#3       BigM_115           -53
    z#3       BigM_90           -158
    z#3       BigM_89           -158
    z#3       BigM_88           -158
    z#3       BigM_63            -65
    z#3       BigM_62            -65
    z#3       BigM_61            -65
    z#3       BigM_36            -59
    z#3       BigM_35            -59
    z#3       BigM_34            -59
    z#3       BigM_9             -24
    z#3       BigM_8             -24
    z#3       BigM_7             -24
    z#3       select_1             1
    z#4       BigM_201          -270
    z#4       BigM_200          -270
    z#4       BigM_199          -270
    z#4       BigM_174          -164
    z#4       BigM_173          -164
    z#4       BigM_172          -164
    z#4       BigM_147          -212
    z#4       BigM_146          -212
    z#4       BigM_145          -212
    z#4       BigM_120           -88
    z#4       BigM_119           -88
    z#4       BigM_118           -88
    z#4       BigM_93           -263
    z#4       BigM_92           -263
    z#4       BigM_91           -263
    z#4       BigM_66           -108
    z#4       BigM_65           -108
    z#4       BigM_64           -108
    z#4       BigM_39            -99
    z#4       BigM_38            -99
    z#4       BigM_37            -99
    z#4       BigM_12            -21
    z#4       BigM_11            -21
    z#4       BigM_10            -21
    z#4       select_1             1
    z#5       BigM_204          -111
    z#5       BigM_203          -111
    z#5       BigM_202          -111
    z#5       BigM_177           -67
    z#5       BigM_176           -67
    z#5       BigM_175           -67
    z#5       BigM_150           -87
    z#5       BigM_149           -87
    z#5       BigM_148           -87
    z#5       BigM_123           -56
    z#5       BigM_122           -56
    z#5       BigM_121           -56
    z#5       BigM_96           -108
    z#5       BigM_95           -108
    z#5       BigM_94           -108
    z#5       BigM_69            -44
    z#5       BigM_68            -44
    z#5       BigM_67            -44
    z#5       BigM_42            -41
    z#5       BigM_41            -41
    z#5       BigM_40            -41
    z#5       BigM_15            -27
    z#5       BigM_14            -27
    z#5       BigM_13            -27
    z#5       select_1             1
    z#6       BigM_207           -76
    z#6       BigM_206           -76
    z#6       BigM_205           -76
    z#6       BigM_180           -57
    z#6       BigM_179           -57
    z#6       BigM_178           -57
    z#6       BigM_153           -65
    z#6       BigM_152           -65
    z#6       BigM_151           -65
    z#6       BigM_126           -70
    z#6       BigM_125           -70
    z#6       BigM_124           -70
    z#6       BigM_99            -74
    z#6       BigM_98            -74
    z#6       BigM_97            -74
    z#6       BigM_72            -31
    z#6       BigM_71            -31
    z#6       BigM_70            -31
    z#6       BigM_45            -40
    z#6       BigM_44            -40
    z#6       BigM_43            -40
    z#6       BigM_18            -34
    z#6       BigM_17            -34
    z#6       BigM_16            -34
    z#6       select_1             1
    z#7       BigM_210           -48
    z#7       BigM_209           -48
    z#7       BigM_208           -48
    z#7       BigM_183          -107
    z#7       BigM_182          -107
    z#7       BigM_181          -107
    z#7       BigM_156          -124
    z#7       BigM_155          -124
    z#7       BigM_154          -124
    z#7       BigM_129          -132
    z#7       BigM_128          -132
    z#7       BigM_127          -132
    z#7       BigM_102           -47
    z#7       BigM_101           -47
    z#7       BigM_100           -47
    z#7       BigM_75            -46
    z#7       BigM_74            -46
    z#7       BigM_73            -46
    z#7       BigM_48            -75
    z#7       BigM_47            -75
    z#7       BigM_46            -75
    z#7       BigM_21            -63
    z#7       BigM_20            -63
    z#7       BigM_19            -63
    z#7       select_1             1
    z#8       BigM_213           -36
    z#8       BigM_212           -36
    z#8       BigM_211           -36
    z#8       BigM_186          -749
    z#8       BigM_185          -749
    z#8       BigM_184          -749
    z#8       BigM_159          -865
    z#8       BigM_158          -865
    z#8       BigM_157          -865
    z#8       BigM_132          -921
    z#8       BigM_131          -921
    z#8       BigM_130          -921
    z#8       BigM_105           -35
    z#8       BigM_104           -35
    z#8       BigM_103           -35
    z#8       BigM_78           -317
    z#8       BigM_77           -317
    z#8       BigM_76           -317
    z#8       BigM_51           -525
    z#8       BigM_50           -525
    z#8       BigM_49           -525
    z#8       BigM_24           -441
    z#8       BigM_23           -441
    z#8       BigM_22           -441
    z#8       select_1             1
    z#9       BigM_216           -36
    z#9       BigM_215           -36
    z#9       BigM_214           -36
    z#9       BigM_189          -562
    z#9       BigM_188          -562
    z#9       BigM_187          -562
    z#9       BigM_162          -649
    z#9       BigM_161          -649
    z#9       BigM_160          -649
    z#9       BigM_135          -691
    z#9       BigM_134          -691
    z#9       BigM_133          -691
    z#9       BigM_108           -35
    z#9       BigM_107           -35
    z#9       BigM_106           -35
    z#9       BigM_81           -238
    z#9       BigM_80           -238
    z#9       BigM_79           -238
    z#9       BigM_54           -394
    z#9       BigM_53           -394
    z#9       BigM_52           -394
    z#9       BigM_27           -331
    z#9       BigM_26           -331
    z#9       BigM_25           -331
    z#9       select_1             1
    MARK0001  'MARKER'                 'INTEND'
    r#1#1#0   init2_1              1
    r#1#1#0   balanc@1            -1
    r#1#1#1   OBJECTIV             5
    r#1#1#1   balanc@2            -1
    r#1#1#1   balanc@1             1
    r#1#1#2   OBJECTIV             5
    r#1#1#2   balanc@3            -1
    r#1#1#2   balanc@2             1
    r#1#1#3   OBJECTIV             5
    r#1#1#3   init3_1              1
    r#1#1#3   balanc@3             1
    r#1#2#0   init2_2              1
    r#1#2#0   balanc@4            -1
    r#1#2#1   OBJECTIV           5.5
    r#1#2#1   balanc@5            -1
    r#1#2#1   balanc@4             1
    r#1#2#2   OBJECTIV           5.5
    r#1#2#2   balanc@6            -1
    r#1#2#2   balanc@5             1
    r#1#2#3   OBJECTIV           5.5
    r#1#2#3   init3_2              1
    r#1#2#3   balanc@6             1
    r#2#1#0   init2_3              1
    r#2#1#0   balanc@7            -1
    r#2#1#1   OBJECTIV             5
    r#2#1#1   balanc@8            -1
    r#2#1#1   balanc@7             1
    r#2#1#2   OBJECTIV             5
    r#2#1#2   balanc@9            -1
    r#2#1#2   balanc@8             1
    r#2#1#3   OBJECTIV             5
    r#2#1#3   init3_3              1
    r#2#1#3   balanc@9             1
    r#2#2#0   init2_4              1
    r#2#2#0   balanc@a            -1
    r#2#2#1   OBJECTIV           5.5
    r#2#2#1   balanc@b            -1
    r#2#2#1   balanc@a             1
    r#2#2#2   OBJECTIV           5.5
    r#2#2#2   balanc@c            -1
    r#2#2#2   balanc@b             1
    r#2#2#3   OBJECTIV           5.5
    r#2#2#3   init3_4              1
    r#2#2#3   balanc@c             1
    r#3#1#0   init2_5              1
    r#3#1#0   balanc@d            -1
    r#3#1#1   OBJECTIV             5
    r#3#1#1   balanc@e            -1
    r#3#1#1   balanc@d             1
    r#3#1#2   OBJECTIV             5
    r#3#1#2   balanc@f            -1
    r#3#1#2   balanc@e             1
    r#3#1#3   OBJECTIV             5
    r#3#1#3   init3_5              1
    r#3#1#3   balanc@f             1
    r#3#2#0   init2_6              1
    r#3#2#0   balan@10            -1
    r#3#2#1   OBJECTIV           5.5
    r#3#2#1   balan@11            -1
    r#3#2#1   balan@10             1
    r#3#2#2   OBJECTIV           5.5
    r#3#2#2   balan@12            -1
    r#3#2#2   balan@11             1
    r#3#2#3   OBJECTIV           5.5
    r#3#2#3   init3_6              1
    r#3#2#3   balan@12             1
    r#4#1#0   init2_7              1
    r#4#1#0   balan@13            -1
    r#4#1#1   OBJECTIV             5
    r#4#1#1   balan@14            -1
    r#4#1#1   balan@13             1
    r#4#1#2   OBJECTIV             5
    r#4#1#2   balan@15            -1
    r#4#1#2   balan@14             1
    r#4#1#3   OBJECTIV             5
    r#4#1#3   init3_7              1
    r#4#1#3   balan@15             1
    r#4#2#0   init2_8              1
    r#4#2#0   balan@16            -1
    r#4#2#1   OBJECTIV           5.5
    r#4#2#1   balan@17            -1
    r#4#2#1   balan@16             1
    r#4#2#2   OBJECTIV           5.5
    r#4#2#2   balan@18            -1
    r#4#2#2   balan@17             1
    r#4#2#3   OBJECTIV           5.5
    r#4#2#3   init3_8              1
    r#4#2#3   balan@18             1
    r#5#1#0   init2_9              1
    r#5#1#0   balan@19            -1
    r#5#1#1   OBJECTIV             5
    r#5#1#1   balan@1a            -1
    r#5#1#1   balan@19             1
    r#5#1#2   OBJECTIV             5
    r#5#1#2   balan@1b            -1
    r#5#1#2   balan@1a             1
    r#5#1#3   OBJECTIV             5
    r#5#1#3   init3_9              1
    r#5#1#3   balan@1b             1
    r#5#2#0   init2_10             1
    r#5#2#0   balan@1c            -1
    r#5#2#1   OBJECTIV           5.5
    r#5#2#1   balan@1d            -1
    r#5#2#1   balan@1c             1
    r#5#2#2   OBJECTIV           5.5
    r#5#2#2   balan@1e            -1
    r#5#2#2   balan@1d             1
    r#5#2#3   OBJECTIV           5.5
    r#5#2#3   init3_10             1
    r#5#2#3   balan@1e             1
    r#6#1#0   init2_11             1
    r#6#1#0   balan@1f            -1
    r#6#1#1   OBJECTIV             5
    r#6#1#1   balan@20            -1
    r#6#1#1   balan@1f             1
    r#6#1#2   OBJECTIV             5
    r#6#1#2   balan@21            -1
    r#6#1#2   balan@20             1
    r#6#1#3   OBJECTIV             5
    r#6#1#3   init3_11             1
    r#6#1#3   balan@21             1
    r#6#2#0   init2_12             1
    r#6#2#0   balan@22            -1
    r#6#2#1   OBJECTIV           5.5
    r#6#2#1   balan@23            -1
    r#6#2#1   balan@22             1
    r#6#2#2   OBJECTIV           5.5
    r#6#2#2   balan@24            -1
    r#6#2#2   balan@23             1
    r#6#2#3   OBJECTIV           5.5
    r#6#2#3   init3_12             1
    r#6#2#3   balan@24             1
    r#7#1#0   init2_13             1
    r#7#1#0   balan@25            -1
    r#7#1#1   OBJECTIV             5
    r#7#1#1   balan@26            -1
    r#7#1#1   balan@25             1
    r#7#1#2   OBJECTIV             5
    r#7#1#2   balan@27            -1
    r#7#1#2   balan@26             1
    r#7#1#3   OBJECTIV             5
    r#7#1#3   init3_13             1
    r#7#1#3   balan@27             1
    r#7#2#0   init2_14             1
    r#7#2#0   balan@28            -1
    r#7#2#1   OBJECTIV           5.5
    r#7#2#1   balan@29            -1
    r#7#2#1   balan@28             1
    r#7#2#2   OBJECTIV           5.5
    r#7#2#2   balan@2a            -1
    r#7#2#2   balan@29             1
    r#7#2#3   OBJECTIV           5.5
    r#7#2#3   init3_14             1
    r#7#2#3   balan@2a             1
    r#8#1#0   init2_15             1
    r#8#1#0   balan@2b            -1
    r#8#1#1   OBJECTIV             5
    r#8#1#1   balan@2c            -1
    r#8#1#1   balan@2b             1
    r#8#1#2   OBJECTIV             5
    r#8#1#2   balan@2d            -1
    r#8#1#2   balan@2c             1
    r#8#1#3   OBJECTIV             5
    r#8#1#3   init3_15             1
    r#8#1#3   balan@2d             1
    r#8#2#0   init2_16             1
    r#8#2#0   balan@2e            -1
    r#8#2#1   OBJECTIV           5.5
    r#8#2#1   balan@2f            -1
    r#8#2#1   balan@2e             1
    r#8#2#2   OBJECTIV           5.5
    r#8#2#2   balan@30            -1
    r#8#2#2   balan@2f             1
    r#8#2#3   OBJECTIV           5.5
    r#8#2#3   init3_16             1
    r#8#2#3   balan@30             1
    s#1#1#0   init1_1              1
    s#1#1#0   balanc@1             1
    s#1#1#1   OBJECTIV             1
    s#1#1#1   balanc@2             1
    s#1#1#1   balanc@1            -1
    s#1#1#2   OBJECTIV             1
    s#1#1#2   balanc@3             1
    s#1#1#2   balanc@2            -1
    s#1#1#3   OBJECTIV             1
    s#1#1#3   balanc@3            -1
    s#1#2#0   init1_2              1
    s#1#2#0   balanc@4             1
    s#1#2#1   OBJECTIV           1.1
    s#1#2#1   balanc@5             1
    s#1#2#1   balanc@4            -1
    s#1#2#2   OBJECTIV           1.1
    s#1#2#2   balanc@6             1
    s#1#2#2   balanc@5            -1
    s#1#2#3   OBJECTIV           1.1
    s#1#2#3   balanc@6            -1
    s#2#1#0   init1_3              1
    s#2#1#0   balanc@7             1
    s#2#1#1   OBJECTIV             1
    s#2#1#1   balanc@8             1
    s#2#1#1   balanc@7            -1
    s#2#1#2   OBJECTIV             1
    s#2#1#2   balanc@9             1
    s#2#1#2   balanc@8            -1
    s#2#1#3   OBJECTIV             1
    s#2#1#3   balanc@9            -1
    s#2#2#0   init1_4              1
    s#2#2#0   balanc@a             1
    s#2#2#1   OBJECTIV           1.1
    s#2#2#1   balanc@b             1
    s#2#2#1   balanc@a            -1
    s#2#2#2   OBJECTIV           1.1
    s#2#2#2   balanc@c             1
    s#2#2#2   balanc@b            -1
    s#2#2#3   OBJECTIV           1.1
    s#2#2#3   balanc@c            -1
    s#3#1#0   init1_5              1
    s#3#1#0   balanc@d             1
    s#3#1#1   OBJECTIV             1
    s#3#1#1   balanc@e             1
    s#3#1#1   balanc@d            -1
    s#3#1#2   OBJECTIV             1
    s#3#1#2   balanc@f             1
    s#3#1#2   balanc@e            -1
    s#3#1#3   OBJECTIV             1
    s#3#1#3   balanc@f            -1
    s#3#2#0   init1_6              1
    s#3#2#0   balan@10             1
    s#3#2#1   OBJECTIV           1.1
    s#3#2#1   balan@11             1
    s#3#2#1   balan@10            -1
    s#3#2#2   OBJECTIV           1.1
    s#3#2#2   balan@12             1
    s#3#2#2   balan@11            -1
    s#3#2#3   OBJECTIV           1.1
    s#3#2#3   balan@12            -1
    s#4#1#0   init1_7              1
    s#4#1#0   balan@13             1
    s#4#1#1   OBJECTIV             1
    s#4#1#1   balan@14             1
    s#4#1#1   balan@13            -1
    s#4#1#2   OBJECTIV             1
    s#4#1#2   balan@15             1
    s#4#1#2   balan@14            -1
    s#4#1#3   OBJECTIV             1
    s#4#1#3   balan@15            -1
    s#4#2#0   init1_8              1
    s#4#2#0   balan@16             1
    s#4#2#1   OBJECTIV           1.1
    s#4#2#1   balan@17             1
    s#4#2#1   balan@16            -1
    s#4#2#2   OBJECTIV           1.1
    s#4#2#2   balan@18             1
    s#4#2#2   balan@17            -1
    s#4#2#3   OBJECTIV           1.1
    s#4#2#3   balan@18            -1
    s#5#1#0   init1_9              1
    s#5#1#0   balan@19             1
    s#5#1#1   OBJECTIV             1
    s#5#1#1   balan@1a             1
    s#5#1#1   balan@19            -1
    s#5#1#2   OBJECTIV             1
    s#5#1#2   balan@1b             1
    s#5#1#2   balan@1a            -1
    s#5#1#3   OBJECTIV             1
    s#5#1#3   balan@1b            -1
    s#5#2#0   init1_10             1
    s#5#2#0   balan@1c             1
    s#5#2#1   OBJECTIV           1.1
    s#5#2#1   balan@1d             1
    s#5#2#1   balan@1c            -1
    s#5#2#2   OBJECTIV           1.1
    s#5#2#2   balan@1e             1
    s#5#2#2   balan@1d            -1
    s#5#2#3   OBJECTIV           1.1
    s#5#2#3   balan@1e            -1
    s#6#1#0   init1_11             1
    s#6#1#0   balan@1f             1
    s#6#1#1   OBJECTIV             1
    s#6#1#1   balan@20             1
    s#6#1#1   balan@1f            -1
    s#6#1#2   OBJECTIV             1
    s#6#1#2   balan@21             1
    s#6#1#2   balan@20            -1
    s#6#1#3   OBJECTIV             1
    s#6#1#3   balan@21            -1
    s#6#2#0   init1_12             1
    s#6#2#0   balan@22             1
    s#6#2#1   OBJECTIV           1.1
    s#6#2#1   balan@23             1
    s#6#2#1   balan@22            -1
    s#6#2#2   OBJECTIV           1.1
    s#6#2#2   balan@24             1
    s#6#2#2   balan@23            -1
    s#6#2#3   OBJECTIV           1.1
    s#6#2#3   balan@24            -1
    s#7#1#0   init1_13             1
    s#7#1#0   balan@25             1
    s#7#1#1   OBJECTIV             1
    s#7#1#1   balan@26             1
    s#7#1#1   balan@25            -1
    s#7#1#2   OBJECTIV             1
    s#7#1#2   balan@27             1
    s#7#1#2   balan@26            -1
    s#7#1#3   OBJECTIV             1
    s#7#1#3   balan@27            -1
    s#7#2#0   init1_14             1
    s#7#2#0   balan@28             1
    s#7#2#1   OBJECTIV           1.1
    s#7#2#1   balan@29             1
    s#7#2#1   balan@28            -1
    s#7#2#2   OBJECTIV           1.1
    s#7#2#2   balan@2a             1
    s#7#2#2   balan@29            -1
    s#7#2#3   OBJECTIV           1.1
    s#7#2#3   balan@2a            -1
    s#8#1#0   init1_15             1
    s#8#1#0   balan@2b             1
    s#8#1#1   OBJECTIV             1
    s#8#1#1   balan@2c             1
    s#8#1#1   balan@2b            -1
    s#8#1#2   OBJECTIV             1
    s#8#1#2   balan@2d             1
    s#8#1#2   balan@2c            -1
    s#8#1#3   OBJECTIV             1
    s#8#1#3   balan@2d            -1
    s#8#2#0   init1_16             1
    s#8#2#0   balan@2e             1
    s#8#2#1   OBJECTIV           1.1
    s#8#2#1   balan@2f             1
    s#8#2#1   balan@2e            -1
    s#8#2#2   OBJECTIV           1.1
    s#8#2#2   balan@30             1
    s#8#2#2   balan@2f            -1
    s#8#2#3   OBJECTIV           1.1
    s#8#2#3   balan@30            -1
RHS
    RHS       select_1             1
    RHS       balanc@1           964
    RHS       balanc@2            21
    RHS       balanc@3           337
    RHS       balanc@7           333
    RHS       balanc@8           776
    RHS       balanc@9           466
    RHS       balanc@a           239
    RHS       balanc@b           425
    RHS       balanc@c           220
    RHS       balanc@d           136
    RHS       balanc@e           621
    RHS       balanc@f           192
    RHS       balan@10             7
    RHS       balan@11            27
    RHS       balan@12           934
    RHS       balan@16           914
    RHS       balan@17           988
    RHS       balan@18           465
    RHS       balan@19           936
    RHS       balan@1a           931
    RHS       balan@1b           895
    RHS       balan@1c           249
    RHS       balan@1d           352
    RHS       balan@1e           188
    RHS       balan@1f           892
    RHS       balan@20           869
    RHS       balan@21           833
    RHS       balan@22           956
    RHS       balan@23           226
    RHS       balan@24           725
    RHS       balan@25           852
    RHS       balan@26           583
    RHS       balan@27           812
    RHS       balan@28           256
    RHS       balan@29           358
    RHS       balan@2a           854
    RHS       balan@2e           972
    RHS       balan@2f           832
    RHS       balan@30           622
    RHS       valid_1           1322
    RHS       valid_2           1575
    RHS       valid_3            884
    RHS       valid_4            949
    RHS       valid_5            968
    RHS       valid_6           2367
    RHS       valid_7           2762
    RHS       valid_8            789
    RHS       valid_9           2594
    RHS       valid_10          1907
    RHS       valid_11          2247
    RHS       valid_12          1468
    RHS       valid_13          2426
BOUNDS
 LO BOUND     r#1#1#0              0
 PL BOUND     r#1#1#0 
 LO BOUND     r#1#1#1              0
 PL BOUND     r#1#1#1 
 LO BOUND     r#1#1#2              0
 PL BOUND     r#1#1#2 
 LO BOUND     r#1#1#3              0
 PL BOUND     r#1#1#3 
 LO BOUND     r#1#2#0              0
 PL BOUND     r#1#2#0 
 LO BOUND     r#1#2#1              0
 PL BOUND     r#1#2#1 
 LO BOUND     r#1#2#2              0
 PL BOUND     r#1#2#2 
 LO BOUND     r#1#2#3              0
 PL BOUND     r#1#2#3 
 LO BOUND     r#2#1#0              0
 PL BOUND     r#2#1#0 
 LO BOUND     r#2#1#1              0
 PL BOUND     r#2#1#1 
 LO BOUND     r#2#1#2              0
 PL BOUND     r#2#1#2 
 LO BOUND     r#2#1#3              0
 PL BOUND     r#2#1#3 
 LO BOUND     r#2#2#0              0
 PL BOUND     r#2#2#0 
 LO BOUND     r#2#2#1              0
 PL BOUND     r#2#2#1 
 LO BOUND     r#2#2#2              0
 PL BOUND     r#2#2#2 
 LO BOUND     r#2#2#3              0
 PL BOUND     r#2#2#3 
 LO BOUND     r#3#1#0              0
 PL BOUND     r#3#1#0 
 LO BOUND     r#3#1#1              0
 PL BOUND     r#3#1#1 
 LO BOUND     r#3#1#2              0
 PL BOUND     r#3#1#2 
 LO BOUND     r#3#1#3              0
 PL BOUND     r#3#1#3 
 LO BOUND     r#3#2#0              0
 PL BOUND     r#3#2#0 
 LO BOUND     r#3#2#1              0
 PL BOUND     r#3#2#1 
 LO BOUND     r#3#2#2              0
 PL BOUND     r#3#2#2 
 LO BOUND     r#3#2#3              0
 PL BOUND     r#3#2#3 
 LO BOUND     r#4#1#0              0
 PL BOUND     r#4#1#0 
 LO BOUND     r#4#1#1              0
 PL BOUND     r#4#1#1 
 LO BOUND     r#4#1#2              0
 PL BOUND     r#4#1#2 
 LO BOUND     r#4#1#3              0
 PL BOUND     r#4#1#3 
 LO BOUND     r#4#2#0              0
 PL BOUND     r#4#2#0 
 LO BOUND     r#4#2#1              0
 PL BOUND     r#4#2#1 
 LO BOUND     r#4#2#2              0
 PL BOUND     r#4#2#2 
 LO BOUND     r#4#2#3              0
 PL BOUND     r#4#2#3 
 LO BOUND     r#5#1#0              0
 PL BOUND     r#5#1#0 
 LO BOUND     r#5#1#1              0
 PL BOUND     r#5#1#1 
 LO BOUND     r#5#1#2              0
 PL BOUND     r#5#1#2 
 LO BOUND     r#5#1#3              0
 PL BOUND     r#5#1#3 
 LO BOUND     r#5#2#0              0
 PL BOUND     r#5#2#0 
 LO BOUND     r#5#2#1              0
 PL BOUND     r#5#2#1 
 LO BOUND     r#5#2#2              0
 PL BOUND     r#5#2#2 
 LO BOUND     r#5#2#3              0
 PL BOUND     r#5#2#3 
 LO BOUND     r#6#1#0              0
 PL BOUND     r#6#1#0 
 LO BOUND     r#6#1#1              0
 PL BOUND     r#6#1#1 
 LO BOUND     r#6#1#2              0
 PL BOUND     r#6#1#2 
 LO BOUND     r#6#1#3              0
 PL BOUND     r#6#1#3 
 LO BOUND     r#6#2#0              0
 PL BOUND     r#6#2#0 
 LO BOUND     r#6#2#1              0
 PL BOUND     r#6#2#1 
 LO BOUND     r#6#2#2              0
 PL BOUND     r#6#2#2 
 LO BOUND     r#6#2#3              0
 PL BOUND     r#6#2#3 
 LO BOUND     r#7#1#0              0
 PL BOUND     r#7#1#0 
 LO BOUND     r#7#1#1              0
 PL BOUND     r#7#1#1 
 LO BOUND     r#7#1#2              0
 PL BOUND     r#7#1#2 
 LO BOUND     r#7#1#3              0
 PL BOUND     r#7#1#3 
 LO BOUND     r#7#2#0              0
 PL BOUND     r#7#2#0 
 LO BOUND     r#7#2#1              0
 PL BOUND     r#7#2#1 
 LO BOUND     r#7#2#2              0
 PL BOUND     r#7#2#2 
 LO BOUND     r#7#2#3              0
 PL BOUND     r#7#2#3 
 LO BOUND     r#8#1#0              0
 PL BOUND     r#8#1#0 
 LO BOUND     r#8#1#1              0
 PL BOUND     r#8#1#1 
 LO BOUND     r#8#1#2              0
 PL BOUND     r#8#1#2 
 LO BOUND     r#8#1#3              0
 PL BOUND     r#8#1#3 
 LO BOUND     r#8#2#0              0
 PL BOUND     r#8#2#0 
 LO BOUND     r#8#2#1              0
 PL BOUND     r#8#2#1 
 LO BOUND     r#8#2#2              0
 PL BOUND     r#8#2#2 
 LO BOUND     r#8#2#3              0
 PL BOUND     r#8#2#3 
 LO BOUND     s#1#1#0              0
 PL BOUND     s#1#1#0 
 LO BOUND     s#1#1#1              0
 PL BOUND     s#1#1#1 
 LO BOUND     s#1#1#2              0
 PL BOUND     s#1#1#2 
 LO BOUND     s#1#1#3              0
 PL BOUND     s#1#1#3 
 LO BOUND     s#1#2#0              0
 PL BOUND     s#1#2#0 
 LO BOUND     s#1#2#1              0
 PL BOUND     s#1#2#1 
 LO BOUND     s#1#2#2              0
 PL BOUND     s#1#2#2 
 LO BOUND     s#1#2#3              0
 PL BOUND     s#1#2#3 
 LO BOUND     s#2#1#0              0
 PL BOUND     s#2#1#0 
 LO BOUND     s#2#1#1              0
 PL BOUND     s#2#1#1 
 LO BOUND     s#2#1#2              0
 PL BOUND     s#2#1#2 
 LO BOUND     s#2#1#3              0
 PL BOUND     s#2#1#3 
 LO BOUND     s#2#2#0              0
 PL BOUND     s#2#2#0 
 LO BOUND     s#2#2#1              0
 PL BOUND     s#2#2#1 
 LO BOUND     s#2#2#2              0
 PL BOUND     s#2#2#2 
 LO BOUND     s#2#2#3              0
 PL BOUND     s#2#2#3 
 LO BOUND     s#3#1#0              0
 PL BOUND     s#3#1#0 
 LO BOUND     s#3#1#1              0
 PL BOUND     s#3#1#1 
 LO BOUND     s#3#1#2              0
 PL BOUND     s#3#1#2 
 LO BOUND     s#3#1#3              0
 PL BOUND     s#3#1#3 
 LO BOUND     s#3#2#0              0
 PL BOUND     s#3#2#0 
 LO BOUND     s#3#2#1              0
 PL BOUND     s#3#2#1 
 LO BOUND     s#3#2#2              0
 PL BOUND     s#3#2#2 
 LO BOUND     s#3#2#3              0
 PL BOUND     s#3#2#3 
 LO BOUND     s#4#1#0              0
 PL BOUND     s#4#1#0 
 LO BOUND     s#4#1#1              0
 PL BOUND     s#4#1#1 
 LO BOUND     s#4#1#2              0
 PL BOUND     s#4#1#2 
 LO BOUND     s#4#1#3              0
 PL BOUND     s#4#1#3 
 LO BOUND     s#4#2#0              0
 PL BOUND     s#4#2#0 
 LO BOUND     s#4#2#1              0
 PL BOUND     s#4#2#1 
 LO BOUND     s#4#2#2              0
 PL BOUND     s#4#2#2 
 LO BOUND     s#4#2#3              0
 PL BOUND     s#4#2#3 
 LO BOUND     s#5#1#0              0
 PL BOUND     s#5#1#0 
 LO BOUND     s#5#1#1              0
 PL BOUND     s#5#1#1 
 LO BOUND     s#5#1#2              0
 PL BOUND     s#5#1#2 
 LO BOUND     s#5#1#3              0
 PL BOUND     s#5#1#3 
 LO BOUND     s#5#2#0              0
 PL BOUND     s#5#2#0 
 LO BOUND     s#5#2#1              0
 PL BOUND     s#5#2#1 
 LO BOUND     s#5#2#2              0
 PL BOUND     s#5#2#2 
 LO BOUND     s#5#2#3              0
 PL BOUND     s#5#2#3 
 LO BOUND     s#6#1#0              0
 PL BOUND     s#6#1#0 
 LO BOUND     s#6#1#1              0
 PL BOUND     s#6#1#1 
 LO BOUND     s#6#1#2              0
 PL BOUND     s#6#1#2 
 LO BOUND     s#6#1#3              0
 PL BOUND     s#6#1#3 
 LO BOUND     s#6#2#0              0
 PL BOUND     s#6#2#0 
 LO BOUND     s#6#2#1              0
 PL BOUND     s#6#2#1 
 LO BOUND     s#6#2#2              0
 PL BOUND     s#6#2#2 
 LO BOUND     s#6#2#3              0
 PL BOUND     s#6#2#3 
 LO BOUND     s#7#1#0              0
 PL BOUND     s#7#1#0 
 LO BOUND     s#7#1#1              0
 PL BOUND     s#7#1#1 
 LO BOUND     s#7#1#2              0
 PL BOUND     s#7#1#2 
 LO BOUND     s#7#1#3              0
 PL BOUND     s#7#1#3 
 LO BOUND     s#7#2#0              0
 PL BOUND     s#7#2#0 
 LO BOUND     s#7#2#1              0
 PL BOUND     s#7#2#1 
 LO BOUND     s#7#2#2              0
 PL BOUND     s#7#2#2 
 LO BOUND     s#7#2#3              0
 PL BOUND     s#7#2#3 
 LO BOUND     s#8#1#0              0
 PL BOUND     s#8#1#0 
 LO BOUND     s#8#1#1              0
 PL BOUND     s#8#1#1 
 LO BOUND     s#8#1#2              0
 PL BOUND     s#8#1#2 
 LO BOUND     s#8#1#3              0
 PL BOUND     s#8#1#3 
 LO BOUND     s#8#2#0              0
 PL BOUND     s#8#2#0 
 LO BOUND     s#8#2#1              0
 PL BOUND     s#8#2#1 
 LO BOUND     s#8#2#2              0
 PL BOUND     s#8#2#2 
 LO BOUND     s#8#2#3              0
 PL BOUND     s#8#2#3 
 LO BOUND     x#1#1#1              0
 PL BOUND     x#1#1#1 
 LO BOUND     x#1#1#2              0
 PL BOUND     x#1#1#2 
 LO BOUND     x#1#1#3              0
 PL BOUND     x#1#1#3 
 LO BOUND     x#1#2#1              0
 PL BOUND     x#1#2#1 
 LO BOUND     x#1#2#2              0
 PL BOUND     x#1#2#2 
 LO BOUND     x#1#2#3              0
 PL BOUND     x#1#2#3 
 LO BOUND     x#2#1#1              0
 PL BOUND     x#2#1#1 
 LO BOUND     x#2#1#2              0
 PL BOUND     x#2#1#2 
 LO BOUND     x#2#1#3              0
 PL BOUND     x#2#1#3 
 LO BOUND     x#2#2#1              0
 PL BOUND     x#2#2#1 
 LO BOUND     x#2#2#2              0
 PL BOUND     x#2#2#2 
 LO BOUND     x#2#2#3              0
 PL BOUND     x#2#2#3 
 LO BOUND     x#3#1#1              0
 PL BOUND     x#3#1#1 
 LO BOUND     x#3#1#2              0
 PL BOUND     x#3#1#2 
 LO BOUND     x#3#1#3              0
 PL BOUND     x#3#1#3 
 LO BOUND     x#3#2#1              0
 PL BOUND     x#3#2#1 
 LO BOUND     x#3#2#2              0
 PL BOUND     x#3#2#2 
 LO BOUND     x#3#2#3              0
 PL BOUND     x#3#2#3 
 LO BOUND     x#4#1#1              0
 PL BOUND     x#4#1#1 
 LO BOUND     x#4#1#2              0
 PL BOUND     x#4#1#2 
 LO BOUND     x#4#1#3              0
 PL BOUND     x#4#1#3 
 LO BOUND     x#4#2#1              0
 PL BOUND     x#4#2#1 
 LO BOUND     x#4#2#2              0
 PL BOUND     x#4#2#2 
 LO BOUND     x#4#2#3              0
 PL BOUND     x#4#2#3 
 LO BOUND     x#5#1#1              0
 PL BOUND     x#5#1#1 
 LO BOUND     x#5#1#2              0
 PL BOUND     x#5#1#2 
 LO BOUND     x#5#1#3              0
 PL BOUND     x#5#1#3 
 LO BOUND     x#5#2#1              0
 PL BOUND     x#5#2#1 
 LO BOUND     x#5#2#2              0
 PL BOUND     x#5#2#2 
 LO BOUND     x#5#2#3              0
 PL BOUND     x#5#2#3 
 LO BOUND     x#6#1#1              0
 PL BOUND     x#6#1#1 
 LO BOUND     x#6#1#2              0
 PL BOUND     x#6#1#2 
 LO BOUND     x#6#1#3              0
 PL BOUND     x#6#1#3 
 LO BOUND     x#6#2#1              0
 PL BOUND     x#6#2#1 
 LO BOUND     x#6#2#2              0
 PL BOUND     x#6#2#2 
 LO BOUND     x#6#2#3              0
 PL BOUND     x#6#2#3 
 LO BOUND     x#7#1#1              0
 PL BOUND     x#7#1#1 
 LO BOUND     x#7#1#2              0
 PL BOUND     x#7#1#2 
 LO BOUND     x#7#1#3              0
 PL BOUND     x#7#1#3 
 LO BOUND     x#7#2#1              0
 PL BOUND     x#7#2#1 
 LO BOUND     x#7#2#2              0
 PL BOUND     x#7#2#2 
 LO BOUND     x#7#2#3              0
 PL BOUND     x#7#2#3 
 LO BOUND     x#8#1#1              0
 PL BOUND     x#8#1#1 
 LO BOUND     x#8#1#2              0
 PL BOUND     x#8#1#2 
 LO BOUND     x#8#1#3              0
 PL BOUND     x#8#1#3 
 LO BOUND     x#8#2#1              0
 PL BOUND     x#8#2#1 
 LO BOUND     x#8#2#2              0
 PL BOUND     x#8#2#2 
 LO BOUND     x#8#2#3              0
 PL BOUND     x#8#2#3 
 LO BOUND     y#1#1#1              0
 PL BOUND     y#1#1#1 
 LO BOUND     y#1#1#2              0
 PL BOUND     y#1#1#2 
 LO BOUND     y#1#1#3              0
 PL BOUND     y#1#1#3 
 LO BOUND     y#1#2#1              0
 PL BOUND     y#1#2#1 
 LO BOUND     y#1#2#2              0
 PL BOUND     y#1#2#2 
 LO BOUND     y#1#2#3              0
 PL BOUND     y#1#2#3 
 LO BOUND     y#1#3#1              0
 PL BOUND     y#1#3#1 
 LO BOUND     y#1#3#2              0
 PL BOUND     y#1#3#2 
 LO BOUND     y#1#3#3              0
 PL BOUND     y#1#3#3 
 LO BOUND     y#1#4#1              0
 PL BOUND     y#1#4#1 
 LO BOUND     y#1#4#2              0
 PL BOUND     y#1#4#2 
 LO BOUND     y#1#4#3              0
 PL BOUND     y#1#4#3 
 LO BOUND     y#1#5#1              0
 PL BOUND     y#1#5#1 
 LO BOUND     y#1#5#2              0
 PL BOUND     y#1#5#2 
 LO BOUND     y#1#5#3              0
 PL BOUND     y#1#5#3 
 LO BOUND     y#1#6#1              0
 PL BOUND     y#1#6#1 
 LO BOUND     y#1#6#2              0
 PL BOUND     y#1#6#2 
 LO BOUND     y#1#6#3              0
 PL BOUND     y#1#6#3 
 LO BOUND     y#1#7#1              0
 PL BOUND     y#1#7#1 
 LO BOUND     y#1#7#2              0
 PL BOUND     y#1#7#2 
 LO BOUND     y#1#7#3              0
 PL BOUND     y#1#7#3 
 LO BOUND     y#1#8#1              0
 PL BOUND     y#1#8#1 
 LO BOUND     y#1#8#2              0
 PL BOUND     y#1#8#2 
 LO BOUND     y#1#8#3              0
 PL BOUND     y#1#8#3 
 LO BOUND     y#1#9#1              0
 PL BOUND     y#1#9#1 
 LO BOUND     y#1#9#2              0
 PL BOUND     y#1#9#2 
 LO BOUND     y#1#9#3              0
 PL BOUND     y#1#9#3 
 LO BOUND     y#2#1#1              0
 PL BOUND     y#2#1#1 
 LO BOUND     y#2#1#2              0
 PL BOUND     y#2#1#2 
 LO BOUND     y#2#1#3              0
 PL BOUND     y#2#1#3 
 LO BOUND     y#2#2#1              0
 PL BOUND     y#2#2#1 
 LO BOUND     y#2#2#2              0
 PL BOUND     y#2#2#2 
 LO BOUND     y#2#2#3              0
 PL BOUND     y#2#2#3 
 LO BOUND     y#2#3#1              0
 PL BOUND     y#2#3#1 
 LO BOUND     y#2#3#2              0
 PL BOUND     y#2#3#2 
 LO BOUND     y#2#3#3              0
 PL BOUND     y#2#3#3 
 LO BOUND     y#2#4#1              0
 PL BOUND     y#2#4#1 
 LO BOUND     y#2#4#2              0
 PL BOUND     y#2#4#2 
 LO BOUND     y#2#4#3              0
 PL BOUND     y#2#4#3 
 LO BOUND     y#2#5#1              0
 PL BOUND     y#2#5#1 
 LO BOUND     y#2#5#2              0
 PL BOUND     y#2#5#2 
 LO BOUND     y#2#5#3              0
 PL BOUND     y#2#5#3 
 LO BOUND     y#2#6#1              0
 PL BOUND     y#2#6#1 
 LO BOUND     y#2#6#2              0
 PL BOUND     y#2#6#2 
 LO BOUND     y#2#6#3              0
 PL BOUND     y#2#6#3 
 LO BOUND     y#2#7#1              0
 PL BOUND     y#2#7#1 
 LO BOUND     y#2#7#2              0
 PL BOUND     y#2#7#2 
 LO BOUND     y#2#7#3              0
 PL BOUND     y#2#7#3 
 LO BOUND     y#2#8#1              0
 PL BOUND     y#2#8#1 
 LO BOUND     y#2#8#2              0
 PL BOUND     y#2#8#2 
 LO BOUND     y#2#8#3              0
 PL BOUND     y#2#8#3 
 LO BOUND     y#2#9#1              0
 PL BOUND     y#2#9#1 
 LO BOUND     y#2#9#2              0
 PL BOUND     y#2#9#2 
 LO BOUND     y#2#9#3              0
 PL BOUND     y#2#9#3 
 LO BOUND     y#3#1#1              0
 PL BOUND     y#3#1#1 
 LO BOUND     y#3#1#2              0
 PL BOUND     y#3#1#2 
 LO BOUND     y#3#1#3              0
 PL BOUND     y#3#1#3 
 LO BOUND     y#3#2#1              0
 PL BOUND     y#3#2#1 
 LO BOUND     y#3#2#2              0
 PL BOUND     y#3#2#2 
 LO BOUND     y#3#2#3              0
 PL BOUND     y#3#2#3 
 LO BOUND     y#3#3#1              0
 PL BOUND     y#3#3#1 
 LO BOUND     y#3#3#2              0
 PL BOUND     y#3#3#2 
 LO BOUND     y#3#3#3              0
 PL BOUND     y#3#3#3 
 LO BOUND     y#3#4#1              0
 PL BOUND     y#3#4#1 
 LO BOUND     y#3#4#2              0
 PL BOUND     y#3#4#2 
 LO BOUND     y#3#4#3              0
 PL BOUND     y#3#4#3 
 LO BOUND     y#3#5#1              0
 PL BOUND     y#3#5#1 
 LO BOUND     y#3#5#2              0
 PL BOUND     y#3#5#2 
 LO BOUND     y#3#5#3              0
 PL BOUND     y#3#5#3 
 LO BOUND     y#3#6#1              0
 PL BOUND     y#3#6#1 
 LO BOUND     y#3#6#2              0
 PL BOUND     y#3#6#2 
 LO BOUND     y#3#6#3              0
 PL BOUND     y#3#6#3 
 LO BOUND     y#3#7#1              0
 PL BOUND     y#3#7#1 
 LO BOUND     y#3#7#2              0
 PL BOUND     y#3#7#2 
 LO BOUND     y#3#7#3              0
 PL BOUND     y#3#7#3 
 LO BOUND     y#3#8#1              0
 PL BOUND     y#3#8#1 
 LO BOUND     y#3#8#2              0
 PL BOUND     y#3#8#2 
 LO BOUND     y#3#8#3              0
 PL BOUND     y#3#8#3 
 LO BOUND     y#3#9#1              0
 PL BOUND     y#3#9#1 
 LO BOUND     y#3#9#2              0
 PL BOUND     y#3#9#2 
 LO BOUND     y#3#9#3              0
 PL BOUND     y#3#9#3 
 LO BOUND     y#4#1#1              0
 PL BOUND     y#4#1#1 
 LO BOUND     y#4#1#2              0
 PL BOUND     y#4#1#2 
 LO BOUND     y#4#1#3              0
 PL BOUND     y#4#1#3 
 LO BOUND     y#4#2#1              0
 PL BOUND     y#4#2#1 
 LO BOUND     y#4#2#2              0
 PL BOUND     y#4#2#2 
 LO BOUND     y#4#2#3              0
 PL BOUND     y#4#2#3 
 LO BOUND     y#4#3#1              0
 PL BOUND     y#4#3#1 
 LO BOUND     y#4#3#2              0
 PL BOUND     y#4#3#2 
 LO BOUND     y#4#3#3              0
 PL BOUND     y#4#3#3 
 LO BOUND     y#4#4#1              0
 PL BOUND     y#4#4#1 
 LO BOUND     y#4#4#2              0
 PL BOUND     y#4#4#2 
 LO BOUND     y#4#4#3              0
 PL BOUND     y#4#4#3 
 LO BOUND     y#4#5#1              0
 PL BOUND     y#4#5#1 
 LO BOUND     y#4#5#2              0
 PL BOUND     y#4#5#2 
 LO BOUND     y#4#5#3              0
 PL BOUND     y#4#5#3 
 LO BOUND     y#4#6#1              0
 PL BOUND     y#4#6#1 
 LO BOUND     y#4#6#2              0
 PL BOUND     y#4#6#2 
 LO BOUND     y#4#6#3              0
 PL BOUND     y#4#6#3 
 LO BOUND     y#4#7#1              0
 PL BOUND     y#4#7#1 
 LO BOUND     y#4#7#2              0
 PL BOUND     y#4#7#2 
 LO BOUND     y#4#7#3              0
 PL BOUND     y#4#7#3 
 LO BOUND     y#4#8#1              0
 PL BOUND     y#4#8#1 
 LO BOUND     y#4#8#2              0
 PL BOUND     y#4#8#2 
 LO BOUND     y#4#8#3              0
 PL BOUND     y#4#8#3 
 LO BOUND     y#4#9#1              0
 PL BOUND     y#4#9#1 
 LO BOUND     y#4#9#2              0
 PL BOUND     y#4#9#2 
 LO BOUND     y#4#9#3              0
 PL BOUND     y#4#9#3 
 LO BOUND     y#5#1#1              0
 PL BOUND     y#5#1#1 
 LO BOUND     y#5#1#2              0
 PL BOUND     y#5#1#2 
 LO BOUND     y#5#1#3              0
 PL BOUND     y#5#1#3 
 LO BOUND     y#5#2#1              0
 PL BOUND     y#5#2#1 
 LO BOUND     y#5#2#2              0
 PL BOUND     y#5#2#2 
 LO BOUND     y#5#2#3              0
 PL BOUND     y#5#2#3 
 LO BOUND     y#5#3#1              0
 PL BOUND     y#5#3#1 
 LO BOUND     y#5#3#2              0
 PL BOUND     y#5#3#2 
 LO BOUND     y#5#3#3              0
 PL BOUND     y#5#3#3 
 LO BOUND     y#5#4#1              0
 PL BOUND     y#5#4#1 
 LO BOUND     y#5#4#2              0
 PL BOUND     y#5#4#2 
 LO BOUND     y#5#4#3              0
 PL BOUND     y#5#4#3 
 LO BOUND     y#5#5#1              0
 PL BOUND     y#5#5#1 
 LO BOUND     y#5#5#2              0
 PL BOUND     y#5#5#2 
 LO BOUND     y#5#5#3              0
 PL BOUND     y#5#5#3 
 LO BOUND     y#5#6#1              0
 PL BOUND     y#5#6#1 
 LO BOUND     y#5#6#2              0
 PL BOUND     y#5#6#2 
 LO BOUND     y#5#6#3              0
 PL BOUND     y#5#6#3 
 LO BOUND     y#5#7#1              0
 PL BOUND     y#5#7#1 
 LO BOUND     y#5#7#2              0
 PL BOUND     y#5#7#2 
 LO BOUND     y#5#7#3              0
 PL BOUND     y#5#7#3 
 LO BOUND     y#5#8#1              0
 PL BOUND     y#5#8#1 
 LO BOUND     y#5#8#2              0
 PL BOUND     y#5#8#2 
 LO BOUND     y#5#8#3              0
 PL BOUND     y#5#8#3 
 LO BOUND     y#5#9#1              0
 PL BOUND     y#5#9#1 
 LO BOUND     y#5#9#2              0
 PL BOUND     y#5#9#2 
 LO BOUND     y#5#9#3              0
 PL BOUND     y#5#9#3 
 LO BOUND     y#6#1#1              0
 PL BOUND     y#6#1#1 
 LO BOUND     y#6#1#2              0
 PL BOUND     y#6#1#2 
 LO BOUND     y#6#1#3              0
 PL BOUND     y#6#1#3 
 LO BOUND     y#6#2#1              0
 PL BOUND     y#6#2#1 
 LO BOUND     y#6#2#2              0
 PL BOUND     y#6#2#2 
 LO BOUND     y#6#2#3              0
 PL BOUND     y#6#2#3 
 LO BOUND     y#6#3#1              0
 PL BOUND     y#6#3#1 
 LO BOUND     y#6#3#2              0
 PL BOUND     y#6#3#2 
 LO BOUND     y#6#3#3              0
 PL BOUND     y#6#3#3 
 LO BOUND     y#6#4#1              0
 PL BOUND     y#6#4#1 
 LO BOUND     y#6#4#2              0
 PL BOUND     y#6#4#2 
 LO BOUND     y#6#4#3              0
 PL BOUND     y#6#4#3 
 LO BOUND     y#6#5#1              0
 PL BOUND     y#6#5#1 
 LO BOUND     y#6#5#2              0
 PL BOUND     y#6#5#2 
 LO BOUND     y#6#5#3              0
 PL BOUND     y#6#5#3 
 LO BOUND     y#6#6#1              0
 PL BOUND     y#6#6#1 
 LO BOUND     y#6#6#2              0
 PL BOUND     y#6#6#2 
 LO BOUND     y#6#6#3              0
 PL BOUND     y#6#6#3 
 LO BOUND     y#6#7#1              0
 PL BOUND     y#6#7#1 
 LO BOUND     y#6#7#2              0
 PL BOUND     y#6#7#2 
 LO BOUND     y#6#7#3              0
 PL BOUND     y#6#7#3 
 LO BOUND     y#6#8#1              0
 PL BOUND     y#6#8#1 
 LO BOUND     y#6#8#2              0
 PL BOUND     y#6#8#2 
 LO BOUND     y#6#8#3              0
 PL BOUND     y#6#8#3 
 LO BOUND     y#6#9#1              0
 PL BOUND     y#6#9#1 
 LO BOUND     y#6#9#2              0
 PL BOUND     y#6#9#2 
 LO BOUND     y#6#9#3              0
 PL BOUND     y#6#9#3 
 LO BOUND     y#7#1#1              0
 PL BOUND     y#7#1#1 
 LO BOUND     y#7#1#2              0
 PL BOUND     y#7#1#2 
 LO BOUND     y#7#1#3              0
 PL BOUND     y#7#1#3 
 LO BOUND     y#7#2#1              0
 PL BOUND     y#7#2#1 
 LO BOUND     y#7#2#2              0
 PL BOUND     y#7#2#2 
 LO BOUND     y#7#2#3              0
 PL BOUND     y#7#2#3 
 LO BOUND     y#7#3#1              0
 PL BOUND     y#7#3#1 
 LO BOUND     y#7#3#2              0
 PL BOUND     y#7#3#2 
 LO BOUND     y#7#3#3              0
 PL BOUND     y#7#3#3 
 LO BOUND     y#7#4#1              0
 PL BOUND     y#7#4#1 
 LO BOUND     y#7#4#2              0
 PL BOUND     y#7#4#2 
 LO BOUND     y#7#4#3              0
 PL BOUND     y#7#4#3 
 LO BOUND     y#7#5#1              0
 PL BOUND     y#7#5#1 
 LO BOUND     y#7#5#2              0
 PL BOUND     y#7#5#2 
 LO BOUND     y#7#5#3              0
 PL BOUND     y#7#5#3 
 LO BOUND     y#7#6#1              0
 PL BOUND     y#7#6#1 
 LO BOUND     y#7#6#2              0
 PL BOUND     y#7#6#2 
 LO BOUND     y#7#6#3              0
 PL BOUND     y#7#6#3 
 LO BOUND     y#7#7#1              0
 PL BOUND     y#7#7#1 
 LO BOUND     y#7#7#2              0
 PL BOUND     y#7#7#2 
 LO BOUND     y#7#7#3              0
 PL BOUND     y#7#7#3 
 LO BOUND     y#7#8#1              0
 PL BOUND     y#7#8#1 
 LO BOUND     y#7#8#2              0
 PL BOUND     y#7#8#2 
 LO BOUND     y#7#8#3              0
 PL BOUND     y#7#8#3 
 LO BOUND     y#7#9#1              0
 PL BOUND     y#7#9#1 
 LO BOUND     y#7#9#2              0
 PL BOUND     y#7#9#2 
 LO BOUND     y#7#9#3              0
 PL BOUND     y#7#9#3 
 LO BOUND     y#8#1#1              0
 PL BOUND     y#8#1#1 
 LO BOUND     y#8#1#2              0
 PL BOUND     y#8#1#2 
 LO BOUND     y#8#1#3              0
 PL BOUND     y#8#1#3 
 LO BOUND     y#8#2#1              0
 PL BOUND     y#8#2#1 
 LO BOUND     y#8#2#2              0
 PL BOUND     y#8#2#2 
 LO BOUND     y#8#2#3              0
 PL BOUND     y#8#2#3 
 LO BOUND     y#8#3#1              0
 PL BOUND     y#8#3#1 
 LO BOUND     y#8#3#2              0
 PL BOUND     y#8#3#2 
 LO BOUND     y#8#3#3              0
 PL BOUND     y#8#3#3 
 LO BOUND     y#8#4#1              0
 PL BOUND     y#8#4#1 
 LO BOUND     y#8#4#2              0
 PL BOUND     y#8#4#2 
 LO BOUND     y#8#4#3              0
 PL BOUND     y#8#4#3 
 LO BOUND     y#8#5#1              0
 PL BOUND     y#8#5#1 
 LO BOUND     y#8#5#2              0
 PL BOUND     y#8#5#2 
 LO BOUND     y#8#5#3              0
 PL BOUND     y#8#5#3 
 LO BOUND     y#8#6#1              0
 PL BOUND     y#8#6#1 
 LO BOUND     y#8#6#2              0
 PL BOUND     y#8#6#2 
 LO BOUND     y#8#6#3              0
 PL BOUND     y#8#6#3 
 LO BOUND     y#8#7#1              0
 PL BOUND     y#8#7#1 
 LO BOUND     y#8#7#2              0
 PL BOUND     y#8#7#2 
 LO BOUND     y#8#7#3              0
 PL BOUND     y#8#7#3 
 LO BOUND     y#8#8#1              0
 PL BOUND     y#8#8#1 
 LO BOUND     y#8#8#2              0
 PL BOUND     y#8#8#2 
 LO BOUND     y#8#8#3              0
 PL BOUND     y#8#8#3 
 LO BOUND     y#8#9#1              0
 PL BOUND     y#8#9#1 
 LO BOUND     y#8#9#2              0
 PL BOUND     y#8#9#2 
 LO BOUND     y#8#9#3              0
 PL BOUND     y#8#9#3 
 LO BOUND     z#1                  0
 UP BOUND     z#1                  1
 LO BOUND     z#2                  0
 UP BOUND     z#2                  1
 LO BOUND     z#3                  0
 UP BOUND     z#3                  1
 LO BOUND     z#4                  0
 UP BOUND     z#4                  1
 LO BOUND     z#5                  0
 UP BOUND     z#5                  1
 LO BOUND     z#6                  0
 UP BOUND     z#6                  1
 LO BOUND     z#7                  0
 UP BOUND     z#7                  1
 LO BOUND     z#8                  0
 UP BOUND     z#8                  1
 LO BOUND     z#9                  0
 UP BOUND     z#9                  1
ENDATA
